### ISSUE TITLE
java.util.MissingFormatArgumentException: Format specifier '%d'

### ISSUE THREAD

**Issue by ProfessorVenkman** [Electron-Cash/Electron-Cash#2358] opened 2021-11-06 14:23 UTC
Crash Report
============

This crash report was reported through the automatic crash reporting system 🤖

Traceback
--------------

```Python traceback
	at java.util.Formatter.format(Formatter.java:2523)
	at java.util.Formatter.format(Formatter.java:2459)
	at java.lang.String.format(String.java:2911)
	at android.content.res.Resources.getQuantityString(Resources.java:610)
	at org.electroncash.electroncash3.UtilKt.getQuantityString(Util.kt:99)
	at org.electroncash.electroncash3.UtilKt.getQuantityString1(Util.kt:103)
	at org.electroncash.electroncash3.CaptionKt.getCaption(Caption.kt:74)
	at org.electroncash.electroncash3.CaptionKt.access$getCaption(Caption.kt:1)
	at org.electroncash.electroncash3.CaptionKt$caption$1$1.invoke(Caption.kt:23)
	at org.electroncash.electroncash3.CaptionKt$caption$1$1.invoke(Unknown Source:2)
	at org.electroncash.electroncash3.BackgroundLiveData$refreshNow$1.run(LiveData.kt:97)
	at java.lang.Thread.run(Thread.java:923)
java.util.MissingFormatArgumentException: Format specifier '%d'
```

Reporter
------------

This issue was reported by 1 user(s):

| Electron Cash Version  | Python Version | Operating System  | Wallet Type  | Locale |
|---|---|---|---|---|
| 4.2.5-5  | 3.8.6 (default, Jan 17 2021, 16:48:53)  [Clang 7.0.2 (https://android.googlesource.com/toolchain/clang 003100370607242d | Android 11 on Xiaomi M2101K9AG (courbet) | unknown | tr_TR | 

Additional Information
------------------------

The reporting user(s) did not provide additional information.

**Comment by mhsmith** [comment] 2021-11-12 13:08
Caused by a mis-formatted translation on Crowdin, similar to #1899. I'll try to come up with a way to check this during the build.

**Comment by mhsmith** [comment] 2021-11-23 14:58
Fixed on Crowdin: https://crowdin.com/translate/electron-cash/532/en-tr#29464. See #1899 for further discussion.

**Closed by mhsmith** 2021-11-23 14:58 UTC
Labels: android
