### ISSUE TITLE
java.lang.RuntimeException: java.lang.reflect.InvocationTargetException

### ISSUE THREAD

**Issue by ProfessorVenkman** [Electron-Cash/Electron-Cash#2072] opened 2020-11-24 22:35 UTC
Crash Report
============

This crash report was reported through the automatic crash reporting system 🤖

Traceback
--------------

```Python traceback
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1386)
Caused by: java.lang.reflect.InvocationTargetException
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1496)
	... 1 more
Caused by: org.electroncash.electroncash3.ToastException: Bu cüzdanı sadece izliyorsunuz.
	at org.electroncash.electroncash3.SendDialog.<init>(Send.kt:41)
	at org.electroncash.electroncash3.MainActivity.onOptionsItemSelected(Main.kt:255)
	at android.app.Activity.onMenuItemSelected(Activity.java:3383)
	at androidx.fragment.app.FragmentActivity.onMenuItemSelected(FragmentActivity.java:384)
	at androidx.appcompat.app.AppCompatActivity.onMenuItemSelected(AppCompatActivity.java:219)
	at androidx.appcompat.view.WindowCallbackWrapper.onMenuItemSelected(WindowCallbackWrapper.java:109)
	at androidx.appcompat.view.WindowCallbackWrapper.onMenuItemSelected(WindowCallbackWrapper.java:109)
	at androidx.appcompat.app.ToolbarActionBar$2.onMenuItemClick(ToolbarActionBar.java:64)
	at androidx.appcompat.widget.Toolbar$1.onMenuItemClick(Toolbar.java:207)
	at androidx.appcompat.widget.ActionMenuView$MenuBuilderCallback.onMenuItemSelected(ActionMenuView.java:781)
	at androidx.appcompat.view.menu.MenuBuilder.dispatchMenuItemSelected(MenuBuilder.java:840)
	at androidx.appcompat.view.menu.MenuItemImpl.invoke(MenuItemImpl.java:158)
	at androidx.appcompat.view.menu.MenuBuilder.performItemAction(MenuBuilder.java:991)
	at androidx.appcompat.view.menu.MenuPopup.onItemClick(MenuPopup.java:128)
	at android.widget.AdapterView.performItemClick(AdapterView.java:339)
	at android.widget.AbsListView.performItemClick(AbsListView.java:1705)
	at android.widget.AbsListView$PerformClick.run(AbsListView.java:4171)
	at android.widget.AbsListView.onTouchUp(AbsListView.java:6751)
	at android.widget.AbsListView.onTouchEvent(AbsListView.java:6498)
	at android.widget.ListView.onTouchEvent(ListView.java:1648)
	at androidx.appcompat.widget.DropDownListView.onTouchEvent(DropDownListView.java:217)
	at androidx.appcompat.widget.MenuPopupWindow$MenuDropDownListView.onTouchEvent(MenuPopupWindow.java:135)
	at android.view.View.dispatchTouchEvent(View.java:10775)
	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2859)
	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2535)
	at android.widget.AbsListView.dispatchTouchEvent(AbsListView.java:6402)
	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2865)
	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2550)
	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2865)
	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2550)
	at android.widget.PopupWindow$PopupDecorView.dispatchTouchEvent(PopupWindow.java:2501)
	at android.view.View.dispatchPointerEvent(View.java:11004)
	at android.view.ViewRootImpl$ViewPostImeInputStage.processPointerEvent(ViewRootImpl.java:5124)
	at android.view.ViewRootImpl$ViewPostImeInputStage.onProcess(ViewRootImpl.java:4976)
	at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:4501)
	at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:4554)
	at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:4520)
	at android.view.ViewRootImpl$AsyncInputStage.forward(ViewRootImpl.java:4653)
	at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:4528)
	at android.view.ViewRootImpl$AsyncInputStage.apply(ViewRootImpl.java:4710)
	at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:4501)
	at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:4554)
	at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:4520)
	at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:4528)
	at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:4501)
	at android.view.ViewRootImpl.deliverInputEvent(ViewRootImpl.java:7022)
	at android.view.ViewRootImpl.doProcessInputEvents(ViewRootImpl.java:6947)
	at android.view.ViewRootImpl.enqueueInputEvent(ViewRootImpl.java:6908)
	at android.view.ViewRootImpl$WindowInputEventReceiver.onInputEvent(ViewRootImpl.java:7132)
	at android.view.InputEventReceiver.dispatchInputEvent(InputEventReceiver.java:185)
	at android.view.InputEventReceiver.nativeConsumeBatchedInputEvents(Native Method)
	at android.view.InputEventReceiver.consumeBatchedInputEvents(InputEventReceiver.java:176)
	at android.view.ViewRootImpl.doConsumeBatchedInput(ViewRootImpl.java:7096)
	at android.view.ViewRootImpl$ConsumeBatchedInputRunnable.run(ViewRootImpl.java:7159)
	at android.view.Choreographer$CallbackRecord.run(Choreographer.java:927)
	at android.view.Choreographer.doCallbacks(Choreographer.java:702)
	at android.view.Choreographer.doFrame(Choreographer.java:632)
	at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:913)
	at android.os.Handler.handleCallback(Handler.java:751)
	at android.os.Handler.dispatchMessage(Handler.java:95)
	at android.os.Looper.loop(Looper.java:154)
	at android.app.ActivityThread.main(ActivityThread.java:6780)
	... 3 more
java.lang.RuntimeException: java.lang.reflect.InvocationTargetException
```

Reporter
------------

This issue was reported by 1 user(s):

| Electron Cash Version  | Python Version | Operating System  | Wallet Type  | Locale |
|---|---|---|---|---|
| 4.2.0-0  | 3.6.5 (default, Sep 11 2019, 15:30:12)  [GCC 4.9] | Android 7.0 on samsung SM-T817 (gts210lte) | unknown | tr_TR | 

Additional Information
------------------------

The reporting user(s) did not provide additional information.

**Comment by mhsmith** [comment] 2020-11-26 04:16
Duplicate of #2032.

**Closed by mhsmith** 2020-11-26 04:16 UTC
