### ISSUE TITLE
AppImage reproducibility fails

### ISSUE THREAD

**Issue by margre8** [Electron-Cash/Electron-Cash#1778] opened 2020-01-21 20:41 UTC
Good evening, I have discovered problem with reproducibility. At first in original Electrum (https://github.com/spesmilo/electrum/issues/5859), and now in Electron-cash too. After unpack AppImages and compare via `diff` I see a lot of different files (include `hidraw.cpython-36m-x86_64-linux-gnu.so` and` hid.cpython-36m-x86_64-linux-gnu.so`).

**Comment by cculianu** [comment] 2020-01-22 00:08
Thanks for reporting this @margre8  -- I appreciate the diligence here. We'll look into it.

**Comment by cculianu** [comment] 2020-01-22 00:10
Which Electron Cash did you build? The latest 4.0.12 tagged one?

**Comment by margre8** [comment] 2020-01-22 02:46
@cculianu I compiled Electron-cash 4.0.12

**Comment by EchterAgo** [comment] 2020-01-22 04:54
@margre8 please share your generated AppImage with me and I will tryto find out what is wrong. I think we already fixed the issue Electrum are having. However I am seeing a different problem right now, but that is caused by starting the build on a master checkout.

**Comment by EchterAgo** [comment] 2020-01-22 05:09
Reproducing 4.0.12 works, however some precautions have to be taken:

```
git checkout -b release_repro 4.0.12
./contrib/build-linux/appimage/build.sh 4.0.12
```
This makes sure you are actually on a 4.0.12 checkout before building, which is important as our Dockerfile recently changed in master, which would change the build has. This builds this binary for me:

```
sha256sum dist/Electron-Cash-4.0.12-x86_64.AppImage 
0f88a37493f6dedabb92ec50fab3a327cab0e4931397e38b63d7032304465a38  dist/Electron-Cash-4.0.12-x86_64.AppImage
```

This situation is not ideal and we will look into how to improve this.

**Comment by cculianu** [comment] 2020-01-22 06:56
Well since it's currently still reproducible (you just have to be sure to be on the right checked-out repo version frist) -- I'm going to go ahead and close this.

**Comment by cculianu** [comment] 2020-01-22 06:57
Thanks @EchterAgo for looking into it!

**Comment by cculianu** [comment] 2020-01-22 08:29
Nope -- there is still an issue and it affects Electrum too.  Has to do with not specifying the exact Cython version.  We're making a fix now.

**Comment by EchterAgo** [comment] 2020-01-22 08:38
No, this is not because of the Cython issue. 4.0.12 was built using the latest Cython available, therefore is reproducible.

**Comment by cculianu** [comment] 2020-01-22 08:42
Ok, #1780 fixes this but note that older builds will use the older scheme and still not be reproducible.  They will be going forward, however, in new releases.

**Closed by cculianu** 2020-01-22 08:42 UTC
Labels: Linux, packaging

**Comment by cculianu** [comment] 2020-01-22 09:04
> No, this is not because of the Cython issue. 4.0.12 was built using the latest Cython available, therefore is reproducible.

Right but it won't be reproducible in the future if a new Cython is released tomorrow or in the intervening time.  It *currently* is reproducible...
