### ISSUE TITLE
android.view.WindowManager$BadTokenException: Unable to add window -- token android.os.BinderProxy@623e9a7 is not valid; is your activity running?

### ISSUE THREAD

**Issue by ProfessorVenkman** [Electron-Cash/Electron-Cash#1579] opened 2019-08-12 17:16 UTC
Crash Report
============

This crash report was reported through the automatic crash reporting system 🤖

Traceback
--------------

```Python traceback
	at android.view.ViewRootImpl.setView(ViewRootImpl.java:697)
	at android.view.WindowManagerGlobal.addView(WindowManagerGlobal.java:342)
	at android.view.WindowManagerImpl.addView(WindowManagerImpl.java:93)
	at android.widget.Toast$TN.handleShow(Toast.java:459)
	at android.widget.Toast$TN$2.handleMessage(Toast.java:342)
	at android.os.Handler.dispatchMessage(Handler.java:102)
	at android.os.Looper.loop(Looper.java:154)
	at android.app.ActivityThread.main(ActivityThread.java:6165)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:888)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:778)
android.view.WindowManager$BadTokenException: Unable to add window -- token android.os.BinderProxy@623e9a7 is not valid; is your activity running?
```

Reporter
------------

This issue was reported by 1 user(s):

| Electron Cash Version  | Python Version | Operating System  | Wallet Type  | Locale |
|---|---|---|---|---|
| 4.0.8-0  | 3.6.5 (default, Dec  7 2018, 13:59:54)  [GCC 4.9] | Android 7.1.1 on motorola Moto G Play (harpia) | unknown | en_US | 

Additional Information
------------------------

The reporting user(s) did not provide additional information.

**Comment by mhsmith** [comment] 2019-08-13 09:18
Duplicate of #1528. Since we've had reports from two different devices now, I'll see if I can come up with a workaround.

**Comment by cculianu** [comment] 2019-08-13 11:54
Ok, closing this one, re-opened the original one

**Closed by cculianu** 2019-08-13 11:54 UTC
Labels: android, duplicate
