### ISSUE TITLE
Crash opening some wallets

### ISSUE THREAD

**Issue by dkaparis** [Electron-Cash/Electron-Cash#2541] opened 2023-01-22 19:38 UTC
After updating to release 4.2.13 Electron-Cash crashes when attempting to open some wallets. A newly created, empty wallet and also some wallets with transactions load fine, however most of my wallets with lots of transactions crash. This is the traceback from console:

```
Traceback (most recent call last):
  File "/usr/lib/python3.10/site-packages/electroncash/wallet.py", line 2597, in get_sorted_requests
    return sorted(m, key=f)
  File "/usr/lib/python3.10/site-packages/electroncash/wallet.py", line 2589, in <lambda>
    m = map(lambda x: self.get_payment_request(x, config), self.receive_requests.keys())
  File "/usr/lib/python3.10/site-packages/electroncash/wallet.py", line 2426, in get_payment_request
    status, conf, tx_hashes = self.get_request_status(addr)
  File "/usr/lib/python3.10/site-packages/electroncash/wallet.py", line 2471, in get_request_status
    paid, conf, tx_hashes = self.get_payment_status(address, amount)
  File "/usr/lib/python3.10/site-packages/electroncash/wallet.py", line 2405, in get_payment_status
    if vsum >= amount:
TypeError: '>=' not supported between instances of 'int' and 'NoneType'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.10/site-packages/electroncash_gui/qt/__init__.py", line 676, in start_new_window
    w = self.create_window_for_wallet(wallet)
  File "/usr/lib/python3.10/site-packages/electroncash_gui/qt/__init__.py", line 564, in create_window_for_wallet
    w = ElectrumWindow(self, wallet)
  File "/usr/lib/python3.10/site-packages/electroncash_gui/qt/main_window.py", line 243, in __init__
    self.load_wallet()
  File "/usr/lib/python3.10/site-packages/electroncash_gui/qt/main_window.py", line 496, in load_wallet
    self.request_list.update()
  File "/usr/lib/python3.10/site-packages/electroncash_gui/qt/util.py", line 749, in update
    self.on_update()
  File "/usr/lib/python3.10/site-packages/electroncash_gui/qt/request_list.py", line 118, in on_update
    for req in self.wallet.get_sorted_requests(self.config):
  File "/usr/lib/python3.10/site-packages/electroncash/wallet.py", line 2605, in get_sorted_requests
    return list(m)
  File "/usr/lib/python3.10/site-packages/electroncash/wallet.py", line 2589, in <lambda>
    m = map(lambda x: self.get_payment_request(x, config), self.receive_requests.keys())
  File "/usr/lib/python3.10/site-packages/electroncash/wallet.py", line 2426, in get_payment_request
    status, conf, tx_hashes = self.get_request_status(addr)
  File "/usr/lib/python3.10/site-packages/electroncash/wallet.py", line 2471, in get_request_status
    paid, conf, tx_hashes = self.get_payment_status(address, amount)
  File "/usr/lib/python3.10/site-packages/electroncash/wallet.py", line 2405, in get_payment_status
    if vsum >= amount:
TypeError: '>=' not supported between instances of 'int' and 'NoneType'
```

Running under Arch Linux.

**Comment by cculianu** [comment] 2023-01-24 02:50
Yes, it was a bug due to how payment requests are handled and we fixed this on master. There is a demo build here with the fix included: https://c3-soft.com/downloads/BitcoinCash/Electron-Cash/testing/4.2.13-24-gafe5bb2cb/

Let me know if that fixes it for you. 

Or if you use the "installed" version just pull master and re-run setup.py install..

Dupe of #2542

**Comment by cculianu** [comment] 2023-01-24 02:50
By the way we are doing a release now. 4.2.14 will have this fixed.

**Closed by cculianu** 2023-01-24 02:50 UTC
