### ISSUE TITLE
java.lang.RuntimeException: java.lang.reflect.InvocationTargetException

### ISSUE THREAD

**Issue by ProfessorVenkman** [Electron-Cash/Electron-Cash#2041] opened 2020-11-10 17:38 UTC
Crash Report
============

This crash report was reported through the automatic crash reporting system 🤖

Traceback
--------------

```Python traceback
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:794)
Caused by: java.lang.reflect.InvocationTargetException
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:904)
	... 1 more
Caused by: org.electroncash.electroncash3.ToastException: This wallet is watching-only.
	at org.electroncash.electroncash3.SendDialog.<init>(Send.kt:41)
	at org.electroncash.electroncash3.MainActivity.onOptionsItemSelected(Main.kt:255)
	at android.app.Activity.onMenuItemSelected(Activity.java:3381)
	at androidx.fragment.app.FragmentActivity.onMenuItemSelected(FragmentActivity.java:384)
	at androidx.appcompat.app.AppCompatActivity.onMenuItemSelected(AppCompatActivity.java:219)
	at androidx.appcompat.view.WindowCallbackWrapper.onMenuItemSelected(WindowCallbackWrapper.java:109)
	at androidx.appcompat.view.WindowCallbackWrapper.onMenuItemSelected(WindowCallbackWrapper.java:109)
	at androidx.appcompat.app.ToolbarActionBar$2.onMenuItemClick(ToolbarActionBar.java:64)
	at androidx.appcompat.widget.Toolbar$1.onMenuItemClick(Toolbar.java:207)
	at androidx.appcompat.widget.ActionMenuView$MenuBuilderCallback.onMenuItemSelected(ActionMenuView.java:781)
	at androidx.appcompat.view.menu.MenuBuilder.dispatchMenuItemSelected(MenuBuilder.java:840)
	at androidx.appcompat.view.menu.MenuItemImpl.invoke(MenuItemImpl.java:158)
	at androidx.appcompat.view.menu.MenuBuilder.performItemAction(MenuBuilder.java:991)
	at androidx.appcompat.view.menu.MenuPopup.onItemClick(MenuPopup.java:128)
	at android.widget.AdapterView.performItemClick(AdapterView.java:310)
	at android.widget.AbsListView.performItemClick(AbsListView.java:1164)
	at android.widget.AbsListView$PerformClick.run(AbsListView.java:3154)
	at android.widget.AbsListView.onTouchUp(AbsListView.java:4109)
	at android.widget.AbsListView.onTouchEvent(AbsListView.java:3841)
	at androidx.appcompat.widget.DropDownListView.onTouchEvent(DropDownListView.java:217)
	at androidx.appcompat.widget.MenuPopupWindow$MenuDropDownListView.onTouchEvent(MenuPopupWindow.java:135)
	at android.view.View.dispatchTouchEvent(View.java:10036)
	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2628)
	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2307)
	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2634)
	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2321)
	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2634)
	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2321)
	at android.widget.PopupWindow$PopupDecorView.dispatchTouchEvent(PopupWindow.java:2277)
	at android.view.View.dispatchPointerEvent(View.java:10258)
	at android.view.ViewRootImpl$ViewPostImeInputStage.processPointerEvent(ViewRootImpl.java:4505)
	at android.view.ViewRootImpl$ViewPostImeInputStage.onProcess(ViewRootImpl.java:4370)
	at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:3910)
	at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:3963)
	at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:3929)
	at android.view.ViewRootImpl$AsyncInputStage.forward(ViewRootImpl.java:4056)
	at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:3937)
	at android.view.ViewRootImpl$AsyncInputStage.apply(ViewRootImpl.java:4113)
	at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:3910)
	at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:3963)
	at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:3929)
	at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:3937)
	at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:3910)
	at android.view.ViewRootImpl.deliverInputEvent(ViewRootImpl.java:6314)
	at android.view.ViewRootImpl.doProcessInputEvents(ViewRootImpl.java:6288)
	at android.view.ViewRootImpl.enqueueInputEvent(ViewRootImpl.java:6249)
	at android.view.ViewRootImpl$WindowInputEventReceiver.onInputEvent(ViewRootImpl.java:6420)
	at android.view.InputEventReceiver.dispatchInputEvent(InputEventReceiver.java:187)
	at android.os.MessageQueue.nativePollOnce(Native Method)
	at android.os.MessageQueue.next(MessageQueue.java:323)
	at android.os.Looper.loop(Looper.java:142)
	at android.app.ActivityThread.main(ActivityThread.java:6205)
	... 3 more
java.lang.RuntimeException: java.lang.reflect.InvocationTargetException
```

Reporter
------------

This issue was reported by 1 user(s):

| Electron Cash Version  | Python Version | Operating System  | Wallet Type  | Locale |
|---|---|---|---|---|
| 4.2.0-0  | 3.6.5 (default, Sep 11 2019, 15:39:45)  [GCC 4.9] | Android 7.1.2 on Xiaomi Redmi 5A (riva) | unknown | in_ID | 

Additional Information
------------------------

The reporting user(s) did not provide additional information.

**Comment by mhsmith** [comment] 2020-11-16 14:20
Duplicate of #2032.

**Closed by mhsmith** 2020-11-16 14:20 UTC
