### ISSUE TITLE
TypeError: 'NoneType' object is not subscriptable

### ISSUE THREAD

**Issue by ProfessorVenkman** [Electron-Cash/Electron-Cash#975] opened 2018-11-24 14:17 UTC
Crash Report
============

This crash report was reported through the automatic crash reporting system 🤖

Traceback
--------------

```Python traceback
  File "site-packages\electron_cash-3.3.1-py3.5.egg\electroncash\util.py", line 645, in run_with_except_hook
  File "site-packages\electron_cash-3.3.1-py3.5.egg\electroncash\network.py", line 962, in run
  File "site-packages\electron_cash-3.3.1-py3.5.egg\electroncash\network.py", line 929, in wait_on_sockets
  File "site-packages\electron_cash-3.3.1-py3.5.egg\electroncash\network.py", line 612, in process_responses
  File "site-packages\electron_cash-3.3.1-py3.5.egg\electroncash\network.py", line 556, in process_response
  File "site-packages\electron_cash-3.3.1-py3.5.egg\electroncash\network.py", line 764, in on_block_headers
  File "site-packages\electron_cash-3.3.1-py3.5.egg\electroncash\blockchain.py", line 457, in connect_chunk
  File "site-packages\electron_cash-3.3.1-py3.5.egg\electroncash\blockchain.py", line 214, in verify_chunk
  File "site-packages\electron_cash-3.3.1-py3.5.egg\electroncash\blockchain.py", line 349, in get_bits

TypeError: 'NoneType' object is not subscriptable
```

Reporter
------------

This issue was reported by 2 user(s):

| Electron Cash Version  | Python Version | Operating System  | Wallet Type  | Locale |
|---|---|---|---|---|
| 3.3.1  | 3.5.4 (v3.5.4:3f56838, Aug  8 2017, 02:07:06) [MSC v.1900 32 bit (Intel)] | Windows-10-10.0.14393 | standard | zh_CN | 
| 3.3.1  | 3.6.4 (default, Aug 30 2018, 19:40:05)  [GCC 4.2.1 Compatible Apple LLVM 8.0.0 (clang-800.0.42.1)] | Darwin-18.2.0-x86_64-i386-64bit | standard | en_US | 

Additional Information
------------------------

The reporting user(s) did not provide additional information.

**Comment by cculianu** [comment] 2019-01-17 17:56
I suspect race conditions in the blockchain code. Needs verification/investigation.

**Comment by cculianu** [comment] 2019-02-12 20:14
Duplicate of #843, fixed by https://github.com/Electron-Cash/Electron-Cash/commit/076d0072c714ba70d467cc01afcfc77751d29e2c

**Closed by cculianu** 2019-02-12 20:14 UTC
Labels: duplicate
