### ISSUE TITLE
TypeError: '>=' not supported between instances of 'int' and 'NoneType'

### ISSUE THREAD

**Issue by ProfessorVenkman** [Electron-Cash/Electron-Cash#2543] opened 2023-01-23 11:09 UTC
Crash Report
============

This crash report was reported through the automatic crash reporting system 🤖

Traceback
--------------

```Python traceback
  File "electroncash_gui/qt/__init__.py", line 676, in start_new_window
  File "electroncash_gui/qt/__init__.py", line 564, in create_window_for_wallet
  File "electroncash_gui/qt/main_window.py", line 243, in __init__
  File "electroncash_gui/qt/main_window.py", line 496, in load_wallet
  File "electroncash_gui/qt/util.py", line 749, in update
  File "electroncash_gui/qt/request_list.py", line 118, in on_update
  File "electroncash/wallet.py", line 2605, in get_sorted_requests
  File "electroncash/wallet.py", line 2589, in <lambda>
  File "electroncash/wallet.py", line 2426, in get_payment_request
  File "electroncash/wallet.py", line 2471, in get_request_status
  File "electroncash/wallet.py", line 2405, in get_payment_status

TypeError: '>=' not supported between instances of 'int' and 'NoneType'
```

Reporter
------------

This issue was reported by 2 user(s):

| Electron Cash Version  | Python Version | Operating System  | Wallet Type  | Locale | Stack |
|---|---|---|---|---|---|
| 4.2.13  | 3.8.9 (default, Jan 12 2023, 13:58:59)  [Clang 11.0.0 (clang-1100.0.33.17)] | macOS-10.16-x86_64-i386-64bit | 2of3,2of4 |  | [ℹ](https://crashhub.electroncash.org//crash/2102) | 
| 4.2.13  | 3.8.9 (default, Jan 12 2023, 13:58:59)  [Clang 11.0.0 (clang-1100.0.33.17)] | macOS-10.16-x86_64-i386-64bit | 2of4,2of3 |  | [ℹ](https://crashhub.electroncash.org//crash/2103) | 

Additional Information
------------------------

> vanessa@bitcoin.com 
> Updated Electron Cash to the latest version and now I am unable to login to this wallet. No issues with opening other wallet though 

---

**Comment by cculianu** [comment] 2023-01-24 02:48
This is basically a dupe of #2542

**Closed by cculianu** 2023-01-24 02:48 UTC
