### ISSUE TITLE
MemoryError: 

### ISSUE THREAD

**Issue by ProfessorVenkman** [Electron-Cash/Electron-Cash#1869] opened 2020-05-05 03:08 UTC
Crash Report
============

This crash report was reported through the automatic crash reporting system 🤖

Traceback
--------------

```Python traceback
  File "site-packages\electron_cash_slp-3.6.1-py3.6.egg\electroncash\util.py", line 870, in run_with_except_hook
  File "site-packages\electron_cash_slp-3.6.1-py3.6.egg\electroncash\network.py", line 1465, in run
  File "site-packages\electron_cash_slp-3.6.1-py3.6.egg\electroncash\network.py", line 1439, in wait_on_sockets
  File "site-packages\electron_cash_slp-3.6.1-py3.6.egg\electroncash\network.py", line 817, in process_responses
  File "site-packages\electron_cash_slp-3.6.1-py3.6.egg\electroncash\interface.py", line 367, in get_responses
  File "site-packages\electron_cash_slp-3.6.1-py3.6.egg\electroncash\util.py", line 832, in get

MemoryError: 
```

Reporter
------------

This issue was reported by 1 user(s):

| Electron Cash Version  | Python Version | Operating System  | Wallet Type  | Locale |
|---|---|---|---|---|
| 3.6.1  | 3.6.8 (tags/v3.6.8:3c6b436a57, Dec 23 2018, 23:31:17) [MSC v.1916 32 bit (Intel)] | Windows-10-10.0.18362-SP0 | imported_addr,slp_imported_addr | de_DE | 

Additional Information
------------------------

> BABY636@OUTLOOK.DE

---

**Comment by cculianu** [comment] 2020-05-07 09:21
User is on Windows which is a 32-bit build currently.  MemoryError can only be raised if the process fails to allocate memory, which can happen on Windows 32-bit quite easily on a huge wallet.  This is not something we should worry about fixing.  Instead, we should focus on deprecating 32-bit and doing 64-bit only Windows builds.

**Comment by cculianu** [comment] 2020-05-07 09:21
Duplicate of #1871 #1868 #1867

**Closed by cculianu** 2020-05-07 09:21 UTC
Labels: SLP

**Comment by ProfessorVenkman** [comment] 2021-03-09 14:28
Good afternoon @cculianu,

I just received another crash report related to this issue. The crash occured on Electron Cash 3.6.6.
I'm not sure which versions of Electron Cash include the fix but this is the first report from anything
newer than 3.6.1 since you closed the issue.

Could you please check if this issue really is resolved? Here is the traceback that I just collected:

```Python traceback
  File "site-packages\electron_cash_slp-3.6.6-py3.6.egg\electroncash\util.py", line 870, in run_with_except_hook
  File "site-packages\electron_cash_slp-3.6.6-py3.6.egg\electroncash\network.py", line 1464, in run
  File "site-packages\electron_cash_slp-3.6.6-py3.6.egg\electroncash\network.py", line 1438, in wait_on_sockets
  File "site-packages\electron_cash_slp-3.6.6-py3.6.egg\electroncash\network.py", line 816, in process_responses
  File "site-packages\electron_cash_slp-3.6.6-py3.6.egg\electroncash\interface.py", line 367, in get_responses
  File "site-packages\electron_cash_slp-3.6.6-py3.6.egg\electroncash\util.py", line 832, in get

MemoryError: 
```


~ _With robotic wishes_
