### ISSUE TITLE
AssertionError: 

### ISSUE THREAD

**Issue by ProfessorVenkman** [Electron-Cash/Electron-Cash#1032] opened 2018-12-10 13:35 UTC
Crash Report
============

This crash report was reported through the automatic crash reporting system 🤖

Traceback
--------------

```Python traceback
  File "site-packages\electron_cash-3.3.1-py3.5.egg\electroncash_gui\qt\network_dialog.py", line 462, in set_proxy
  File "site-packages\electron_cash-3.3.1-py3.5.egg\electroncash\network.py", line 457, in set_parameters
  File "site-packages\electron_cash-3.3.1-py3.5.egg\electroncash\network.py", line 416, in start_network

AssertionError: 
```

Reporter
------------

This issue was reported by 1 user(s):

| Electron Cash Version  | Python Version | Operating System  | Wallet Type  | Locale |
|---|---|---|---|---|
| 3.3.1  | 3.5.4 (v3.5.4:3f56838, Aug  8 2017, 02:07:06) [MSC v.1900 32 bit (Intel)] | Windows-7-6.1.7601-SP1 | standard | en_US | 

Additional Information
------------------------

The reporting user(s) did not provide additional information.

**Comment by dagurval** [comment] 2019-01-11 21:57
Duplicate of #722 and #636.

Looks like it crashes when user restarts the network interfaces with qt thread as a side effect of setting a parameter.

**Comment by cculianu** [comment] 2019-01-11 22:58
Yep. There's a race condition with the UI thread and the network thread.  I think I know how to fix this... let me take a stab at it now.

**Comment by cculianu** [comment] 2019-01-11 23:09
Ok, fixed in latest commit

**Closed by cculianu** 2019-01-11 23:09 UTC
