### ISSUE TITLE
CashFusion Tor dialog prompts user every time EC is opened

### ISSUE THREAD

**Issue by georgedonnelly** [Electron-Cash/Electron-Cash#1969] opened 2020-08-20 18:44 UTC
EC 4.1.0 MacOs

Every time EC is opened, the "CashFusion requires Tor to operate..." dialog pops up, despite the fact that user has not previously used CF and despite that user has repeatedly selected No previously.

im_uname#100🍋, [20.08.20 13:39]
okay, able to reproduce - it seems like the behavior was triggered by "cashfusion" unable to detect a working tor port. On my machine it doesn't trigger because i also have a systemwide Tor client.

desired behavior should  be that the check only triggers when cashfusion is either enabled by hand, or starting EC with cashfusion already enabled.

Relevant conversation: https://t.me/electroncashwallet/63818

Thank you!

**Comment by cculianu** [comment] 2020-08-20 18:48
Cashfusion is always on by default but disabled but running . This is not a bug per se.

**Comment by imaginaryusername** [comment] 2020-08-20 18:51
Can confirm, able to reproduce. 

Observed behavior: Prompt triggers at program start even when Cashfusion is off, as long as plugin is checked in Optional Features. 

Expected behavior: Prompt should only trigger either when starting with Cashfusion on, or at manual enable of Cashfusion via button on the bottom right. 

Workaround: Before there's a fix, if one does not want to use Fusion at all one can go to Tools -> Optional Features -> uncheck Cashfusion. This is less flexible but can probably get rid of the prompt in many cases.

**Comment by cculianu** [comment] 2020-08-20 18:53
This is not a bug. You guys specified some stuff as behavior — months ago -/ and now are surprised .

I’m closing this issue since this is working as intended.

If you want the behavior changed Please open a new issue and define it as a feature change and spec it out as to what you want exactly.

That& you.

**Closed by cculianu** 2020-08-20 18:53 UTC
Labels: wontfix
