### ISSUE TITLE
electrum cash

### ISSUE THREAD

**Issue by sirgarrison2** [Electron-Cash/Electron-Cash#1134] opened 2019-01-29 22:07 UTC
who can I contact about the electrum cash wallet?after bifurcating the chain I have a problem with translations....I have a write-off of BAB when making the transfer BSV

**Comment by cculianu** [comment] 2019-01-29 22:10
1. It's called Electron Cash, not Electrum Cash
2. The cryptocurrency you are concerned with is commonly referred to as BCH, not BAB. BAB is generally regarded as a pejorative term.
3. I don't really understand what your question is. I'm closing this issue as it looks like a support request.  Feel free to continue to communicate here, though, and please elaborate on what you are asking.

**Closed by cculianu** 2019-01-29 22:10 UTC
Labels: support-request

**Comment by sirgarrison2** [comment] 2019-01-29 22:15
Yes , I need support....I did send 3 BSV but I had a write-off of BCH or Bitcoin ABC along with this ,what to do ?

**Comment by cculianu** [comment] 2019-01-29 22:44
I am not sure I understand what you are asking, exactly.  I would be willing to help, but you need to write something clear and intelligible.  I honestly do not understand what you are saying.  You need to elaborate.

May I suggest you get on reddit or a forum and ask other people for help?  This issue tracker is really designed for reporting bugs to the developers of the software and is not intended to be the primary support channel for questions related to splitting BSV.

**Comment by sirgarrison2** [comment] 2019-01-29 22:51
I think this is a software error,I used electron cash 3.3.2  I sent bsv, in the lower right corner there is a chain selection , but the withdrawal occurred in both blocks were affected as well and Bitcoin abc in the same amount I don't write well in English sorry

**Comment by sirgarrison2** [comment] 2019-01-29 23:44
https://blockchair.com/bitcoin-cash/transaction/70600b6c2ef07561a23a58e278675b966a51611ab6a46fdba709c004a26f7b37

https://blockchair.com/bitcoin-sv/transaction/70600b6c2ef07561a23a58e278675b966a51611ab6a46fdba709c004a26f7b37

let's try so, my operation is not authorized , in one chain ,but in electron cash write-off occurred, what to do ?

**Comment by sirgarrison2** [comment] 2019-01-30 00:00
help me please tell me where to find a contact support this wallet, maybe there is some order of action, your help will make my search more productive, thank you

**Comment by cculianu** [comment] 2019-01-30 07:55
Ah, I see. Thank you for elaborating.

Ok, so this **is** a software issue, indeed.  But it is not a software issue with Electron Cash.  It's a problem with the BSV chain with respect to the BCH chain. 

Your transaction was sent on the BSV chain but the problem is that transactions can be relayed between the two chains (usually it's safe to send on BCH then send on BSV later).  But if you send on BSV without having split your coins -- both chains run the risk of seeing the same transaction.

I'm sorry this happened to you -- it is a situation beyond our control.

This has happened to many people and it's because BSV did not implement replay protection versus the BCH chain.  Had they done so, this wouldn't have happened to you.

**Comment by cculianu** [comment] 2019-01-30 07:56
Your only option at this point is to see if the person or business you sent the BCH to inadvertently is willing to refund you those funds that were sent to them.  They are the ones that control the funds now.

This is why it is important that you do a coin split.  You can use Mark Lundeberg's coinsplitter version of Electron Cash to properly split coins.  

https://github.com/markblundeberg/coinsplitter/releases

**Comment by sirgarrison2** [comment] 2019-01-30 08:39
I sent bsv to bitfinex exchange, I received a response from technical support.they can not return the money back, I was told that you need to contact the hardware developers, where I sent my funds. I have two such transactions and don't know how to get the funds back , I was thinking maybe you that any would advise

**Comment by sirgarrison2** [comment] 2019-01-30 08:41
if this problem is known then why is it not solved ?  does no one really care about that ? there is no clear instructions how and in what order to send bsv or bitcoin abc

**Comment by imaginaryusername** [comment] 2019-01-30 09:37
It's not really the fault of electron-cash or BCH developers that BSV decided to not implement replay protection, nor our fault that you decided to use Bitfinex, an exchange known to not rescue replayed coins. The fact that BSV decided to split without replay protection meant they went on a course that dooms uninformed users like you to losing money from day 1. Please go bug them for the horrible decision, we did not make it.

_And_ despite all these, we still released and widely circulated a splitting tool helping people split their coins safely: https://github.com/markblundeberg/coinsplitter/releases

None of this is the responsibility of any of us, nor are you entitled to any assistance or care - we could've just ignored the existence of BSV completely and let adventurous people deal with it themselves. I'll recommend not further annoying us by calling BCH any other name, and acting less entitled next time.

As for your lost funds, they are under bitfinex's control now, you should ask them. If they don't honor it, sorry for your loss.

**Comment by sirgarrison2** [comment] 2019-01-30 09:44
thank you for your answer and your position I respect your opinion and
write in support of the exchange bitfinex , I did not want to annoy you and
call bch a different name ,it also does not depend on me , each resource
has its own name and I , as a user , horrified by how extensive the range
of these names , I will be happy to communicate in your language and
support your name.

ср, 30 янв. 2019 г. в 10:37, imaginaryusername <notifications@github.com>:

**Comment by cculianu** [comment] 2019-01-30 10:43
Heh, no worries @sirgarrison2  -- your first message initially annoyed me then I realized you didn't mean harm and that you actually were just confused.

In my estimation the BSV developers and the BSV camp has hurt this space by intentionally creating confusion in naming and also allowing this huge hole to exist -- lack of replay protection.

You are not the only person hit by this, @sirgarrison2 -- many users have lost money and as @imaginaryusername has said, it's not on us.

They are the ones that created this chaos.

Thanks for understanding and good luck retrieving your funds!
