### ISSUE TITLE
java.util.FormatFlagsConversionMismatchException: Conversion = s, Flags =  

### ISSUE THREAD

**Issue by ProfessorVenkman** [Electron-Cash/Electron-Cash#1899] opened 2020-06-17 08:12 UTC
Crash Report
============

This crash report was reported through the automatic crash reporting system 🤖

Traceback
--------------

```Python traceback
	at java.util.Formatter$FormatSpecifier.failMismatch(Formatter.java:4398)
	at java.util.Formatter$FormatSpecifier.checkBadFlags(Formatter.java:3091)
	at java.util.Formatter$FormatSpecifier.checkGeneral(Formatter.java:3049)
	at java.util.Formatter$FormatSpecifier.<init>(Formatter.java:2816)
	at java.util.Formatter$FormatSpecifierParser.<init>(Formatter.java:2624)
	at java.util.Formatter.parse(Formatter.java:2557)
	at java.util.Formatter.format(Formatter.java:2504)
	at java.util.Formatter.format(Formatter.java:2458)
	at java.lang.String.format(String.java:2883)
	at android.content.res.Resources.getString(Resources.java:466)
	at androidx.fragment.app.Fragment.getString(Fragment.java:873)
	at org.electroncash.electroncash3.WalletDeleteConfirmDialog.onBuildDialog(Main.kt:443)
	at org.electroncash.electroncash3.AlertDialogFragment.onCreateDialog(Dialog.kt:39)
	at org.electroncash.electroncash3.AlertDialogFragment.onCreateDialog(Dialog.kt:27)
	at androidx.fragment.app.DialogFragment.onGetLayoutInflater(DialogFragment.java:380)
	at androidx.fragment.app.Fragment.performGetLayoutInflater(Fragment.java:1412)
	at androidx.fragment.app.FragmentManagerImpl.moveToState(FragmentManagerImpl.java:881)
	at androidx.fragment.app.FragmentManagerImpl.moveFragmentToExpectedState(FragmentManagerImpl.java:1238)
	at androidx.fragment.app.FragmentManagerImpl.moveToState(FragmentManagerImpl.java:1303)
	at androidx.fragment.app.BackStackRecord.executeOps(BackStackRecord.java:439)
	at androidx.fragment.app.FragmentManagerImpl.executeOps(FragmentManagerImpl.java:2079)
	at androidx.fragment.app.FragmentManagerImpl.executeOpsTogether(FragmentManagerImpl.java:1869)
	at androidx.fragment.app.FragmentManagerImpl.removeRedundantOperationsAndExecute(FragmentManagerImpl.java:1824)
	at androidx.fragment.app.FragmentManagerImpl.execSingleAction(FragmentManagerImpl.java:1696)
	at androidx.fragment.app.BackStackRecord.commitNow(BackStackRecord.java:293)
	at androidx.fragment.app.DialogFragment.showNow(DialogFragment.java:192)
	at org.electroncash.electroncash3.UtilKt.showDialog(Util.kt:73)
	at org.electroncash.electroncash3.UtilKt.showDialog$default(Util.kt:66)
	at org.electroncash.electroncash3.WalletOpenDialog$onShowDialog$3.onClick(Main.kt:431)
	at android.view.View.performClick(View.java:6615)
	at android.view.View.performClickInternal(View.java:6592)
	at android.view.View.access$3100(View.java:778)
	at android.view.View$PerformClick.run(View.java:25907)
	at android.os.Handler.handleCallback(Handler.java:873)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loop(Looper.java:198)
	at android.app.ActivityThread.main(ActivityThread.java:6732)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858)
java.util.FormatFlagsConversionMismatchException: Conversion = s, Flags =  
```

Reporter
------------

This issue was reported by 14 user(s):

| Electron Cash Version  | Python Version | Operating System  | Wallet Type  | Locale |
|---|---|---|---|---|
| 4.0.14-0  | 3.6.5 (default, Sep 11 2019, 15:39:45)  [GCC 4.9] | Android 9 on asus ASUS_X00QD (ASUS_X00QD) | unknown | fr_BE | 
| 4.0.14-0  | 3.6.5 (default, Sep 11 2019, 15:39:45)  [GCC 4.9] | Android 8.1.0 on HUAWEI BKK-LX2 (HWBKK-Q) | unknown | fr_FR | 
| 4.0.14-0  | 3.6.5 (default, Sep 11 2019, 15:39:45)  [GCC 4.9] | Android 8.1.0 on HUAWEI BKK-LX2 (HWBKK-Q) | unknown | fr_FR | 
| 4.0.14-0  | 3.6.5 (default, Sep 11 2019, 15:30:12)  [GCC 4.9] | Android 9 on samsung SM-J330FN (j3y17lte) | unknown | fr_FR | 
| 4.0.14-0  | 3.6.5 (default, Sep 11 2019, 15:39:45)  [GCC 4.9] | Android 8.1.0 on HUAWEI BKK-LX2 (HWBKK-Q) | unknown | fr_FR | 
| 4.0.14-0  | 3.6.5 (default, Sep 11 2019, 15:30:12)  [GCC 4.9] | Android 9 on ITEL MOBILE LIMITED itel W5505 (itel-W5505) | unknown | fr_FR | 
| 4.0.14-0  | 3.6.5 (default, Sep 11 2019, 15:30:12)  [GCC 4.9] | Android 8.1.0 on itel itel A32F (itel-A32F) | unknown | fr_CI | 
| 4.0.14-0  | 3.6.5 (default, Sep 11 2019, 15:30:12)  [GCC 4.9] | Android 8.1.0 on itel itel A32F (itel-A32F) | unknown | fr_CI | 
| 4.0.14-0  | 3.6.5 (default, Sep 11 2019, 15:30:12)  [GCC 4.9] | Android 9 on TECNO MOBILE LIMITED TECNO KC6 (TECNO-KC6) | unknown | fr_FR | 
| 4.0.14-0  | 3.6.5 (default, Sep 11 2019, 15:30:12)  [GCC 4.9] | Android 9 on itel itel W6002E (itel-W6002E) | unknown | fr_CM | 
| 4.0.14-0  | 3.6.5 (default, Sep 11 2019, 15:30:12)  [GCC 4.9] | Android 9 on itel itel W6002E (itel-W6002E) | unknown | fr_CM | 
| 4.0.14-0  | 3.6.5 (default, Sep 11 2019, 15:30:12)  [GCC 4.9] | Android 9 on itel itel W6002E (itel-W6002E) | unknown | fr_CM | 
| 4.0.14-0  | 3.6.5 (default, Sep 11 2019, 15:30:12)  [GCC 4.9] | Android 9 on itel itel W6002E (itel-W6002E) | unknown | fr_CM | 
| 4.0.14-0  | 3.6.5 (default, Sep 11 2019, 15:30:12)  [GCC 4.9] | Android 8.1.0 on samsung SM-G390F (xcover4lte) | unknown | fr_FR | 

Additional Information
------------------------

> unitile

---

> unitile

---

> le wallet était ouvert (aprés avoir tapé le modt de pass / pin) puis j'ai cliqué pour supprimer le portefeuille et ça a planté !

---

**Comment by mhsmith** [comment] 2020-09-27 22:50
Only happening on French devices, so maybe there was something wrong with the translation of that string. I'll investigate.

**Comment by mhsmith** [comment] 2020-09-27 22:56
The translation was:

> Voulez-vous vraiment supprimer votre portefeuille '% s'?

The extra space between the `%` and the `s` caused it to break. This has since been fixed on Crowdin.

**Closed by mhsmith** 2020-09-27 22:56 UTC

**Comment by EchterAgo** [comment] 2021-11-12 15:31
I submitted a fixed version of this string because crowdin already flagged it as an issue, but because it was not approved it seems like the version with the space was picked. I marked the fixed string as approved now.

**Comment by mhsmith** [comment] 2021-11-24 13:57
@EchterAgo: In which version of Electron Cash was the bad string picked? 

The string was updated last year in the [electrum-locale repository](https://github.com/Electron-Cash/electrum-locale/commit/848004f800821a3bceaa23d00eeccf78ddb94eb5#diff-d30b76749f954e94bfe3774a9fbc148783a108a076c21e48528c176a962870c1), which is used by the Windows and Linux builds. The Android build, which runs the make_locale script to download strings directly from Crowdin, also had the corrected string at that time, and I think the Mac and iOS builds work the same way.

When a string has multiple translations and none of them are approved, it looks like Crowdin gives priority to the most recently-added one. However, the downloaded .po files aren't updated until a project manager runs the "build" command (green button on the project home page). It looks like a build is also triggered by the make_locale script, if it has access to the API key.

**Comment by mhsmith** [comment] 2021-11-24 14:19
@EchterAgo @cculianu @fyookball: As it stands, any random Crowdin user can submit any string in any language, and unless the string has an approved translation, it'll be built into the next release without any further checks. I think we need to improve this process.

For example, one Turkish translator misunderstood how the plural system worked, and submitted many translations where both the "one" and the "other" translations were in the "one" box. This caused the Android app to crash when set to Turkish, because the string required two fields and the code only passed one (#2358).

This issue (#1899) is another crash on Android caused by bad translations, and there have been at least two in the desktop app  as well (#1821, #1925).

As well as crashes, misformatted translations can also cause UI problems. There are three examples of this in the Turkish transaction dialog in the current desktop app:

<img src="https://user-images.githubusercontent.com/166954/143253990-bcb11fea-81b5-4f0d-97b5-0e6aa8b1edd9.png" width="650"/>

* "%s" appears near the top instead of the transaction date. This was caused by {} syntax being used in the source string but % syntax in the translation.
* "%Girdi" in the middle was supposed to be "&Girdi", i.e. a keyboard accelerator.
* A duplicated plural translation in the button at the bottom, complete with the Turkish words for "one" and "other".

I've updated the Android string conversion script to detect some of these things, fixed all the errors it found, and messaged a couple of translators who were repeatedly making the same mistakes.

But if bad translations can crash the app or cause information to disappear from the UI, then I think we should treat them more like pull requests. Crowdin has an approval system for this purpose, but we aren't currently using it, except in German. So here's what I suggest we do:

* Mass-approve all the existing strings.
* Enable the "Export only approved translations" setting.
* Before each release, give all the new strings a basic syntax check before approving them. Crowdin has a "side-by-side" or "proofreading" mode which allows this to be done quickly.

What do you think?

**Comment by cculianu** [comment] 2021-11-24 14:59
I agree -- the situation is bad and even a security hazard.  I agree with ALL of your recommendations.

@EchterAgo Do you agree? Maybe we should change the settings now right away...

**Comment by EchterAgo** [comment] 2021-11-27 07:31
I think what @mhsmith suggested makes sense, I don't see a better way to prevent this at the moment.

Crowdin also has a way to check for problems in the translation strings which can catch some issues. I once went over the translations with this and fixed many problematic ones. I will do this again soon.

I'll also see if I can come up with some tool to better detect these.

**Comment by cculianu** [comment] 2021-11-27 14:42
Ok, sounds good. In the meantime I changed the project setting to "Only export approved strings".  I will also try and approve strings for languages I am familiar enough with (English + the Romance languages French, Italian, Spanish, Romanian).

I also set the crowding notifications to notify (via email) when new strings appear.  If this proves onerous and spammy let me know we can disable the notifications.

**Comment by EchterAgo** [comment] 2021-11-27 15:21
IIRC the notifications are already enabled. Translators can opt out on a per-project basis if they do not wish to receive notifications.

**Comment by mhsmith** [comment] 2021-11-27 18:17
> I'll also see if I can come up with some tool to better detect these.

You can have a look at android/app/generate_strings.py, but it currently only reports problems which are likely to cause a crash, like a translation referring to fields which weren't in the original. Crowdin is supposed to warn about this, but it doesn't always work because it doesn't recognize empty `{}` markers as being fields. I've fixed all the examples which existed as of a few days ago.

The reverse (a translation with fewer fields than the original) sometimes indicates a translation mistake and sometimes not, but shouldn't lead to a crash.
