### ISSUE TITLE
com.chaquo.python.PyException: AttributeError: 'NoneType' object has no attribute 'endswith'

### ISSUE THREAD

**Issue by ProfessorVenkman** [Electron-Cash/Electron-Cash#1794] opened 2020-01-30 18:59 UTC
Crash Report
============

This crash report was reported through the automatic crash reporting system 🤖

Traceback
--------------

```Python traceback
	at <python>.electroncash.network.process_responses(network.py:856)
	at <python>.electroncash.network.wait_on_sockets(network.py:1436)
	at <python>.electroncash.network.run(network.py:1463)
	at <python>.electroncash_gui.android.daemon.run(daemon.py:34)
	at <python>.six.reraise(six.py:693)
	at <python>.electroncash_gui.android.daemon.run(daemon.py:25)
	at <python>.chaquopy_java.call(chaquopy_java.pyx:283)
	at <python>.chaquopy_java.Java_com_chaquo_python_PyObject_callAttrThrows(chaquopy_java.pyx:255)
	at com.chaquo.python.PyObject.callAttrThrows(Native Method)
	at com.chaquo.python.PyInvocationHandler.invoke(PyInvocationHandler.java:31)
	at java.lang.reflect.Proxy.invoke(Proxy.java:1006)
	at $Proxy4.run(Unknown Source)
	at android.os.Handler.handleCallback(Handler.java:883)
	at android.os.Handler.dispatchMessage(Handler.java:100)
	at android.os.Looper.loop(Looper.java:214)
	at android.app.ActivityThread.main(ActivityThread.java:7682)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:516)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:950)
com.chaquo.python.PyException: AttributeError: 'NoneType' object has no attribute 'endswith'
```

Reporter
------------

This issue was reported by 2 user(s):

| Electron Cash Version  | Python Version | Operating System  | Wallet Type  | Locale |
|---|---|---|---|---|
| 4.0.11-0  | 3.6.5 (default, Sep 11 2019, 15:39:45)  [GCC 4.9] | Android 10 on OnePlus ONEPLUS A6013 (OnePlus6T) | unknown | fr_FR | 
| 4.0.11-0  | 3.6.5 (default, Sep 11 2019, 15:39:45)  [GCC 4.9] | Android 9 on samsung SM-G960F (starlte) | unknown | cs_CZ | 

Additional Information
------------------------

The reporting user(s) did not provide additional information.

**Comment by mhsmith** [comment] 2020-01-31 11:17
Duplicate of #1774.

**Closed by mhsmith** 2020-01-31 11:17 UTC

**Comment by cculianu** [comment] 2020-01-31 17:16
So I spent a little time looking at the code: This is so mysterious to me.  I can't see how thus execution path could end up with 'method' being `None` there.  Like if it was a real request -- it must have had a string `method`.  If it was a notification.. another execution path would have been taken.

I'm still investigating but on the surface I can't come up with a cogent theory in my mind how this can happen.

And it doesn't look like it can happen as the result of a misbehaving server.

On Android all the network requests go through standard calls right? Like no funny touching of private data in the Network class to enqueue requests right? (I wouldn't imagine that code does this, but I figured it's worth asking).

**Comment by mhsmith** [comment] 2020-01-31 17:28
I'm pretty sure it only uses standard calls, yes (search for `callAttr` in [Network.kt](https://github.com/Electron-Cash/Electron-Cash/blob/master/android/app/src/main/java/org/electroncash/electroncash3/Network.kt)).

**Comment by cculianu** [comment] 2020-02-01 20:11
Hey @mhsmith so I solved it.  Turns out the new Fulcrum server behaves a little differently and Electron Cash totally drops the ball when this happens.

I added commits to fix this and will update Fulcrum very soon to not confuse older clients as well.
