### ISSUE TITLE
java.lang.IllegalArgumentException: reportSizeConfigurations: ActivityRecord not found for: Token{ad63df7 null}

### ISSUE THREAD

**Issue by ProfessorVenkman** [Electron-Cash/Electron-Cash#1653] opened 2019-10-18 11:19 UTC
Crash Report
============

This crash report was reported through the automatic crash reporting system 🤖

Traceback
--------------

```Python traceback
	at android.os.Parcel.readException(Parcel.java:1958)
	at android.os.Parcel.readException(Parcel.java:1900)
	at android.app.IActivityManager$Stub$Proxy.reportSizeConfigurations(IActivityManager.java:9358)
	at android.app.ActivityThread.reportSizeConfigurations(ActivityThread.java:3478)
	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3421)
	at android.app.ActivityThread.handleRelaunchActivity(ActivityThread.java:5477)
	at android.app.ActivityThread.-wrap19(Unknown Source:0)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2000)
	at android.os.Handler.dispatchMessage(Handler.java:108)
	at android.os.Looper.loop(Looper.java:166)
	at android.app.ActivityThread.main(ActivityThread.java:7529)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:245)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:921)
java.lang.IllegalArgumentException: reportSizeConfigurations: ActivityRecord not found for: Token{ad63df7 null}
```

Reporter
------------

This issue was reported by 1 user(s):

| Electron Cash Version  | Python Version | Operating System  | Wallet Type  | Locale |
|---|---|---|---|---|
| 4.0.11-0  | 3.6.5 (default, Sep 11 2019, 15:39:45)  [GCC 4.9] | Android 8.0.0 on HUAWEI LDN-L21 (HWLDN-Q) | unknown | de_DE | 

Additional Information
------------------------

The reporting user(s) did not provide additional information.

**Comment by cculianu** [comment] 2019-10-18 12:03
Paging @mhsmith

**Comment by mhsmith** [comment] 2019-10-20 20:50
Looks like a known bug in Android ([StackOverflow](https://stackoverflow.com/questions/46309428/), [Google issue tracker](https://issuetracker.google.com/issues/62427912)). Possibly triggered by updating the app: there's another possible scenario on the SO page, but it's not relevant to us. 

I don't see any other suggestions for an app-level fix, and none of our own code is on the stack, so I don't think there's much we can do unless someone provides instructions to reproduce it.

**Comment by cculianu** [comment] 2019-10-20 22:13
Yeah, let's just close it. I'm satisfied. :)

**Closed by cculianu** 2019-10-20 22:13 UTC
Labels: android

**Comment by mhsmith** [comment] 2020-11-29 21:30
[According to Google](https://issuetracker.google.com/issues/62427912#comment75), this has been fixed in a "future Android release", which probably means Android 11 or 12.
