### ISSUE TITLE
kotlin.KotlinNullPointerException: 

### ISSUE THREAD

**Issue by ProfessorVenkman** [Electron-Cash/Electron-Cash#1843] opened 2020-03-27 10:17 UTC
Crash Report
============

This crash report was reported through the automatic crash reporting system 🤖

Traceback
--------------

```Python traceback
	at org.electroncash.electroncash3.CloseWalletDialog.onPreExecute(Main.kt:422)
	at org.electroncash.electroncash3.TaskDialog.onStart(Dialog.kt:181)
	at androidx.fragment.app.Fragment.performStart(Fragment.java:2632)
	at androidx.fragment.app.FragmentManagerImpl.moveToState(FragmentManagerImpl.java:915)
	at androidx.fragment.app.FragmentManagerImpl.moveFragmentToExpectedState(FragmentManagerImpl.java:1238)
	at androidx.fragment.app.FragmentManagerImpl.moveToState(FragmentManagerImpl.java:1303)
	at androidx.fragment.app.FragmentManagerImpl.dispatchStateChange(FragmentManagerImpl.java:2659)
	at androidx.fragment.app.FragmentManagerImpl.dispatchStart(FragmentManagerImpl.java:2619)
	at androidx.fragment.app.FragmentController.dispatchStart(FragmentController.java:257)
	at androidx.fragment.app.FragmentActivity.onStart(FragmentActivity.java:551)
	at androidx.appcompat.app.AppCompatActivity.onStart(AppCompatActivity.java:201)
	at android.app.Instrumentation.callActivityOnStart(Instrumentation.java:1395)
	at android.app.Activity.performStart(Activity.java:7356)
	at android.app.ActivityThread.handleStartActivity(ActivityThread.java:3159)
	at android.app.servertransaction.TransactionExecutor.performLifecycleSequence(TransactionExecutor.java:180)
	at android.app.servertransaction.TransactionExecutor.cycleToPath(TransactionExecutor.java:165)
	at android.app.servertransaction.TransactionExecutor.executeLifecycleState(TransactionExecutor.java:142)
	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:70)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1969)
	at android.os.Handler.dispatchMessage(Handler.java:106)
	at android.os.Looper.loop(Looper.java:214)
	at android.app.ActivityThread.main(ActivityThread.java:7124)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:494)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:975)
kotlin.KotlinNullPointerException: 
```

Reporter
------------

This issue was reported by 1 user(s):

| Electron Cash Version  | Python Version | Operating System  | Wallet Type  | Locale |
|---|---|---|---|---|
| 4.0.11-0  | 3.6.5 (default, Sep 11 2019, 15:39:45)  [GCC 4.9] | Android 9 on samsung SM-A205U (a20p) | unknown | en_US | 

Additional Information
------------------------

The reporting user(s) did not provide additional information.

**Comment by mhsmith** [comment] 2020-05-18 20:51
Duplicate of #1872

**Closed by mhsmith** 2020-05-18 20:51 UTC
Labels: android
