### ISSUE TITLE
[Android] Problem with BitPay invoice

### ISSUE THREAD

**Issue by jonas-lundqvist** [Electron-Cash/Electron-Cash#812] opened 2018-07-27 17:36 UTC
Yesterday I had some issues paying a BitPay invoice using the Android version of Electron Cash (3.3 "Classic", latest on Google Play Store). This is the first time I used anything else then the desktop (Linux) version for BitPay invoices.

At checkout at the merchant the QR code on the invoice was show and I scanned it with my phone successfully. I then entered my PIN code and sent the transaction but I got an error message (in the web browser) after 5-ish seconds that the invoice had expired from BitPay.

I think less approximately 2 minute had passed between the time the invoice was shown and the error message appeared, which is way less then the 15 minute timeout that is the default.

I had a mail discussion with the BitPay support and received a refund. I could the successfully pay the same item with the desktop Linux version (3.3.1) of Electron Cash.

BitPay could not find any issues on their side and wanted me to contact Electron Cash (you guys). I can send the mail conversation containing txid's and stuff if you provide a mail address .

Phone: Nokia 8 (TA-1008)
OS: Android 8.1.0, July 1 security patch level

**Comment by fyookball** [comment] 2018-07-27 17:53
I don't know if Android supports Bip70.

**Comment by jonas-lundqvist** [comment] 2018-07-27 18:34
I would call that a quite serious issue since Electron Cash is listed as supported on the BitPay website. The UX of a failed payment that needs to be refunded by BitPay is pretty catastrophic to users.

If I had time over I would like to look into this issue, but sadly spare time is not something I have much of. Is there any news/updates concerning the native Android app that I think I heard about at Reddit? If I would find time it would be a shame if it were a waste since that code would be obsolete.

**Comment by fyookball** [comment] 2018-07-27 18:58
native android wont be ready for a bit although its coming along. we can look into fixing this for classic android

**Comment by rt121212121** [comment] 2018-07-28 18:54
What we can do in the short term is get Bitpay to make sure only desktop and maybe if it supports it, ios, are noted as supporting payment requests.

**Comment by jonas-lundqvist** [comment] 2018-07-29 08:48
On July 28, 2018 8:54:18 PM GMT+02:00, Roger Taylor <notifications@github.com> wrote:
>What we can do in the short term is get Bitpay to make sure only
>desktop and maybe if it supports it, ios, are noted as supporting
>payment requests.

Personally I think it is better as a short term (emergency) "fix" to abort and present an error message on Android whenever a BIP70 address is encountered. I'm quite certain that BitPay has no idea of the client used and the wallet will broadcast the transaction either way. BitPay stating on the website that the Android version of Electron Cash is not supported is not sufficient, people are lazy and don't read everything.

**Comment by dbilitch** [comment] 2018-08-28 02:28
I just stumbled across this as well. (Wish I'd have seen the issue before.)  Anyways, the error from the Bitpay web page was that I didn't pay using a payment protocol supporting wallet.  I've sent off to Bitpay to get a refund and will report any additional information here.

As an aside, I tried to install the Windows version on a Windows 7 machine.  The install fails due to missing DLLs.

**Comment by pieterpoorthuis** [comment] 2018-09-03 11:29
Pieter from BitPay here. Most common issues with payment protocol are:
1) Transaction is broadcasted to the P2P network before the server (BitPay in this case) has responded with HTTP 200 to the client.
2) Transaction contains unconfirmed inputs
3) Transaction is sent with RBF

(1) is rejected by BitPay in the way that OP describes. So this is likely happening with Android Electron Cash. It can be fixed by following payment protocol to the end and thus sending the transaction to the server before broadcasting the transaction to the P2P network.
(2) and (3) will display an error on the BitPay invoice.

BitPay has written a technical write up about a JSON implementation of PayPro here: https://github.com/bitpay/jsonPaymentProtocol/blob/master/specification.md

We are working on improving the messaging in the invoice on our end, so issues can be found easier.

**Comment by jonas-lundqvist** [comment] 2018-09-10 20:01
@pieterpoorthuis 
Just out of curiosity... is the HTTP 200 you speak about an "invisible" arrow from 'Merchant Server' back to the 'Wallet App' after the payment is submitted in the BIP-70 specification (https://raw.githubusercontent.com/bitcoin/bips/master/bip-0070/Protocol_Sequence.png) but before the wallet app broadcasts the transaction?

**Comment by pieterpoorthuis** [comment] 2018-09-11 07:00
I'm talking about the PaymentACK, after the wallet sends the payment to the server.
The BIP70 spec is not clear on what should happen if the server rejects the payment. We have clarified this here: https://github.com/bitpay/jsonPaymentProtocol/blob/master/specification.md

Most important clarification is that the wallet should not broadcast the payment to the P2P network until the server has accepted the payment.

**Comment by jonas-lundqvist** [comment] 2018-09-30 19:58
I have done some investigations on this issue and noticed that it also affects the desktop version of Electron Cash where a transaction might reach BitPay via the P2P network before it is posted as a BIP-70 payment. I was able to trigger that behavior on the master branch using test.bitpay.com where the payment failed but the wallet had already broadcasted the transaction.

However I twist and turn it the requirement of the user to *not* broadcast the transaction before the merchant has acked it seems to be non compliant with Payment Protocol (BIP-70). That being said, I do agree that BitPays requirement makes sense and provides a much better UX. Does this break any other service using BIP-70? Perhaps some merchants are using a BIP-70 service that actually waits for the transaction to be received via the P2P network before considering the invoice paid. That would be "less" of a problem because the user has not lost any money. Still bad because the payment failed and it was not the users fault.
@pieterpoorthuis Have you considered increasing the "payment_details_version" so wallets can distinguish between the standard BIP-70 behavior and BitPay behavior? Obviously that would need a new BIP and community consensus.

The PR that is linked to this issue should fix BitPay invoices for the desktop version. I have not done the work needed in the Android code but I feel like this is something that should be taken seriously and fixed!

**Closed** 2018-10-03 21:29 UTC
