### ISSUE TITLE
java.lang.RuntimeException: java.lang.reflect.InvocationTargetException

### ISSUE THREAD

**Issue by ProfessorVenkman** [Electron-Cash/Electron-Cash#2046] opened 2020-11-12 23:06 UTC
Crash Report
============

This crash report was reported through the automatic crash reporting system 🤖

Traceback
--------------

```Python traceback
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:921)
Caused by: java.lang.reflect.InvocationTargetException
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:245)
	... 1 more
Caused by: org.electroncash.electroncash3.ToastException: Diese Geldbörse ist im Beobachtungsmodus.
	at org.electroncash.electroncash3.SendDialog.<init>(Send.kt:41)
	at org.electroncash.electroncash3.MainActivity.onOptionsItemSelected(Main.kt:255)
	at android.app.Activity.onMenuItemSelected(Activity.java:3707)
	at androidx.fragment.app.FragmentActivity.onMenuItemSelected(FragmentActivity.java:384)
	at androidx.appcompat.app.AppCompatActivity.onMenuItemSelected(AppCompatActivity.java:219)
	at androidx.appcompat.view.WindowCallbackWrapper.onMenuItemSelected(WindowCallbackWrapper.java:109)
	at androidx.appcompat.view.WindowCallbackWrapper.onMenuItemSelected(WindowCallbackWrapper.java:109)
	at androidx.appcompat.app.ToolbarActionBar$2.onMenuItemClick(ToolbarActionBar.java:64)
	at androidx.appcompat.widget.Toolbar$1.onMenuItemClick(Toolbar.java:207)
	at androidx.appcompat.widget.ActionMenuView$MenuBuilderCallback.onMenuItemSelected(ActionMenuView.java:781)
	at androidx.appcompat.view.menu.MenuBuilder.dispatchMenuItemSelected(MenuBuilder.java:840)
	at androidx.appcompat.view.menu.MenuItemImpl.invoke(MenuItemImpl.java:158)
	at androidx.appcompat.view.menu.MenuBuilder.performItemAction(MenuBuilder.java:991)
	at androidx.appcompat.view.menu.MenuPopup.onItemClick(MenuPopup.java:128)
	at android.widget.AdapterView.performItemClick(AdapterView.java:321)
	at android.widget.AbsListView.performItemClick(AbsListView.java:1217)
	at android.widget.AbsListView$PerformClick.run(AbsListView.java:3203)
	at android.widget.AbsListView$3.run(AbsListView.java:4151)
	at android.os.Handler.handleCallback(Handler.java:808)
	at android.os.Handler.dispatchMessage(Handler.java:101)
	at android.os.Looper.loop(Looper.java:166)
	at android.app.ActivityThread.main(ActivityThread.java:7529)
	... 3 more
java.lang.RuntimeException: java.lang.reflect.InvocationTargetException
```

Reporter
------------

This issue was reported by 1 user(s):

| Electron Cash Version  | Python Version | Operating System  | Wallet Type  | Locale |
|---|---|---|---|---|
| 4.2.0-0  | 3.6.5 (default, Sep 11 2019, 15:39:45)  [GCC 4.9] | Android 8.0.0 on HUAWEI LDN-L21 (HWLDN-Q) | unknown | de_DE | 

Additional Information
------------------------

> Warum kann ich nicht meine Transactionen signieren... Bitte aktivieren Sie GitHub da haben Sie die Möglichkeit! Es ist alles bestätigt
> 
> Email Adresse reufrujevic750@gmail.com und GitHub Adresse ist Reuf12
> Verifizierung machen Sie bitte... 

---

**Comment by mhsmith** [comment] 2020-11-16 14:20
Duplicate of #2032.

@Reuf12 sorry about this. The crash will be fixed in the next version of Electron Cash. However, you still won't be able to sign a transaction from a watching-only wallet, because it doesn't have any private keys.

**Closed by mhsmith** 2020-11-16 14:20 UTC
