### ISSUE TITLE
OSError: [Errno 22] Invalid argument: 'C:\\Users\\Alex7\\Downloads\\electron_cash_data\\certs\\bch.imaginary.cash.temp'

### ISSUE THREAD

**Issue by ProfessorVenkman** [Electron-Cash/Electron-Cash#1100] opened 2019-01-10 00:01 UTC
Crash Report
============

This crash report was reported through the automatic crash reporting system 🤖

Traceback
--------------

```Python traceback
  File "site-packages\electron_cash-3.3.1cs-py3.5.egg\electroncash\util.py", line 609, in run_with_except_hook
  File "site-packages\electron_cash-3.3.1cs-py3.5.egg\electroncash\interface.py", line 240, in run
  File "site-packages\electron_cash-3.3.1cs-py3.5.egg\electroncash\interface.py", line 179, in get_socket

OSError: [Errno 22] Invalid argument: 'C:\\Users\\Alex7\\Downloads\\electron_cash_data\\certs\\bch.imaginary.cash.temp'
```

Reporter
------------

This issue was reported by 1 user(s):

| Electron Cash Version  | Python Version | Operating System  | Wallet Type  | Locale |
|---|---|---|---|---|
| 3.3.1CS  | 3.5.4 (v3.5.4:3f56838, Aug  8 2017, 02:07:06) [MSC v.1900 32 bit (Intel)] | Windows-7-6.1.7601-SP1 | standard | ru_RU | 

Additional Information
------------------------

The reporting user(s) did not provide additional information.

**Comment by cculianu** [comment] 2019-01-18 02:42
Dupe of #631

**Closed by cculianu** 2019-01-18 02:42 UTC
Labels: duplicate

**Comment by ProfessorVenkman** [comment] 2019-02-03 00:48
Good morning @cculianu,

I just received another crash report related to this issue. The crash occured on Electron Cash 3.3.3.
I'm not sure which versions of Electron Cash include the fix but this is the first report from anything
newer than 3.3.1CS since you closed the issue.

Could you please check if this issue really is resolved? Here is the traceback that I just collected:

```Python traceback
  File "/usr/local/lib/python3.6/dist-packages/Electron_Cash-3.3.3-py3.6.egg/electroncash/util.py", line 598, in run_with_except_hook
    run_original(*args2, **kwargs2)
  File "/usr/local/lib/python3.6/dist-packages/Electron_Cash-3.3.3-py3.6.egg/electroncash/interface.py", line 240, in run
    socket = self.get_socket()
  File "/usr/local/lib/python3.6/dist-packages/Electron_Cash-3.3.3-py3.6.egg/electroncash/interface.py", line 182, in get_socket
    os.fsync(f.fileno())

OSError: [Errno 28] No space left on device
```


~ _With robotic wishes_
