### ISSUE TITLE
com.chaquo.python.PyException: FileExistsError: /data/data/org.electroncash.wallet/files/data/wallets/new

### ISSUE THREAD

**Issue by ProfessorVenkman** [Electron-Cash/Electron-Cash#1625] opened 2019-09-20 17:53 UTC
Crash Report
============

This crash report was reported through the automatic crash reporting system 🤖

Traceback
--------------

```Python traceback
	at <python>.create(/android_asset/chaquopy/app.zip/electroncash_gui/android/console.py:152)
	at <python>.chaquopy_java.call(chaquopy_java.pyx:282)
	at <python>.chaquopy_java.Java_com_chaquo_python_PyObject_callAttrThrows(chaquopy_java.pyx:254)
	at com.chaquo.python.PyObject.callAttrThrows(Native Method)
	at com.chaquo.python.PyObject.callAttr(PyObject.java:207)
	at org.electroncash.electroncash3.NewWalletSeedDialog.onCreateWallet(NewWallet.kt:155)
	at org.electroncash.electroncash3.NewWalletDialog2$onShowDialog$1$1.run(NewWallet.kt:106)
	at java.lang.Thread.run(Thread.java:761)
com.chaquo.python.PyException: FileExistsError: /data/data/org.electroncash.wallet/files/data/wallets/new
```

Reporter
------------

This issue was reported by 1 user(s):

| Electron Cash Version  | Python Version | Operating System  | Wallet Type  | Locale |
|---|---|---|---|---|
| 4.0.9-0  | 3.6.5 (default, Dec  7 2018, 14:06:05)  [GCC 4.9] | Android 7.1.1 on google HP Chromebook x360 11 G1 EE (snappy_cheets) | unknown | en_US | 

Additional Information
------------------------

The reporting user(s) did not provide additional information.

**Comment by mhsmith** [comment] 2019-09-22 12:43
Duplicate of #1497, please close.

**Comment by cculianu** [comment] 2019-09-22 13:17
Ok.

**Closed by cculianu** 2019-09-22 13:17 UTC
Labels: android, duplicate
