### ISSUE TITLE
TypeError: unorderable types: NoneType() < int()

### ISSUE THREAD

**Issue by ProfessorVenkman** [Electron-Cash/Electron-Cash#1059] opened 2018-12-19 22:52 UTC
Crash Report
============

This crash report was reported through the automatic crash reporting system 🤖

Traceback
--------------

```Python traceback
  File "_ctypes/callbacks.c", line 234, in 'calling callback function'
  File "/var/containers/Bundle/Application/C55C4F5A-66B7-4AB4-852D-63F135C58639/Electron-Cash.app/Library/Application Support/com.c3-soft.ElectronCash/app_packages/rubicon/objc/runtime.py", line 1065, in _objc_method
    result = f(py_self, *args)
  File "/private/var/containers/Bundle/Application/C55C4F5A-66B7-4AB4-852D-63F135C58639/Electron-Cash.app/Library/Application Support/com.c3-soft.ElectronCash/app/ElectronCash/electroncash_gui/ios_native/newwallet.py", line 1185, in doChkFormOk
    item = _ImportItemify(x)
  File "/private/var/containers/Bundle/Application/C55C4F5A-66B7-4AB4-852D-63F135C58639/Electron-Cash.app/Library/Application Support/com.c3-soft.ElectronCash/app/ElectronCash/electroncash_gui/ios_native/newwallet.py", line 1302, in _ImportItemify
    info = PublicKey.from_WIF_privkey(item).address
  File "/private/var/containers/Bundle/Application/C55C4F5A-66B7-4AB4-852D-63F135C58639/Electron-Cash.app/Library/Application Support/com.c3-soft.ElectronCash/app/ElectronCash/electroncash/address.py", line 168, in from_WIF_privkey
    ec_key = EC_KEY(privkey)
  File "/private/var/containers/Bundle/Application/C55C4F5A-66B7-4AB4-852D-63F135C58639/Electron-Cash.app/Library/Application Support/com.c3-soft.ElectronCash/app/ElectronCash/electroncash/bitcoin.py", line 598, in __init__
    self.pubkey = ecdsa.ecdsa.Public_key( generator_secp256k1, generator_secp256k1 * secret )
  File "/var/containers/Bundle/Application/C55C4F5A-66B7-4AB4-852D-63F135C58639/Electron-Cash.app/Library/Application Support/com.c3-soft.ElectronCash/app_packages/ecdsa/ecdsa.py", line 89, in __init__
    if point.x() < 0 or n <= point.x() or point.y() < 0 or n <= point.y():

TypeError: unorderable types: NoneType() < int()
```

Reporter
------------

This issue was reported by 1 user(s):

| Electron Cash Version  | Python Version | Operating System  | Wallet Type  | Locale |
|---|---|---|---|---|
| 3.3.1 (iOS Build: 320)  | 3.5.5+ (default, Jul  5 2018, 10:38:23)  [GCC 4.2.1 Compatible Apple LLVM 9.1.0 (clang-902.0.39.2)] | Darwin-18.2.0-iPad6,11-64bit iOS 12.1 iPad (24089EF0-0302-45A4-A716-2F555CC867AF) | unknown | ru_RU | 

Additional Information
------------------------

The reporting user(s) did not provide additional information.

**Comment by cculianu** [comment] 2019-01-17 17:07
I've seen this a few times already.

**Comment by cculianu** [comment] 2019-01-17 17:09
Dupe of #813

**Closed** 2019-01-17 17:09 UTC
Labels: bug, ios
