### ISSUE TITLE
ProcessError: Failed to compile input

### ISSUE THREAD

**Issue by vermorel** [Electron-Cash/Electron-Cash#1961] opened 2020-08-15 08:15 UTC
I am facing a modal dialog box error which says `ProcessError: Failed to compile input` when trying to sign with the last signature in a multisig wallet.

My environment:

* Windows 10
* Electron Cash 4.1.0
* Trezor Bridge 2.0.27
* Trezor firmware (last version)

Steps to reproduce:

* Create a new multisig wallet  => OK
* Trezor connected green => OK
* Other cosigners send bits of money => They appear on Electron Cash main dialog.
* CTRL+T load the text transaction generated by another cosigner => this part works well, the dialog box open, the details of the intended transaction are fine.
* Click _Sign_, two confirmations on Trezor device follow.
* Just after the last Trezor confirmation, Electron Cash opens a modal dialog box `ProcessError: Failed to compile input`.

Could someone help me to get this problem solved?

Also, if I just try to send cash via _Send >> Pay To_, Electron Cash, I will be ask twice for confirmation on the Trezor device, and then, Electron Cash fails again with the same modal dialog both prompting `ProcessError: Failed to compile input`. This behavior is somewhat baffling because as the wallet is multisig, I don't even understand why Electron Cash is letting me attempt to send money without the cosigning process.

**Comment by cculianu** [comment] 2020-08-15 08:28
Thanks for the detailed report.

**Comment by prusnak** [comment] 2020-08-15 10:03
The coins are stored on invalid paths. For BCH they need to be stored at `m/44'/145'`. If you need to spend BCH coins on Bitcoin path `m/44'/1'` try downgrading the firmware to previous version.

**Comment by cculianu** [comment] 2020-08-15 10:18
Thanks for chiming in here @prusnak

**Comment by cculianu** [comment] 2020-08-15 10:21
Since this is a firmware restriction, rather than an actual bug, I am going to mark this as "Wontfix" because the issue is not one.. that we can control.

I will be pinning this issue however in case others have this issue.

**Closed by cculianu** 2020-08-15 10:21 UTC
Labels: bug, hardware wallets, multisig wallets

**Comment by cculianu** [comment] 2020-08-15 10:44
I created this issue #1963 to address this new firmware restriction.  @prusnak so the `m/44'/145'` restriction is on *all* wallet types (multisig or not) -- or just  for multisig?

**Comment by prusnak** [comment] 2020-08-15 10:49
No, `m/44'/145'` is for non-multisig (regular) accounts.
For multisig you need to use the multisig scheme: `m/48'/145'.

**Comment by cculianu** [comment] 2020-08-15 10:52
Thank you Pavel. 👍
