### ISSUE TITLE
Exiting Electron-Cash-4.4.0-portable will delete the wallet files it created

### ISSUE THREAD

**Issue by uccuh** [Electron-Cash/Electron-Cash#2828] opened 2024-04-08 02:55 UTC
Electron-Cash-4.4.0-portable will create wallet files in AppData\Local\Temp by default. Exiting Electron Cash will delete the wallet files, I think it's dangerous.

**Comment by Torsten42** [comment] 2024-04-13 13:20
I have the same Issue with Electron-Cash-4.4.0-portable (OS Windows 10). My analysis showed the following: The "electron_cash_data" directory is apparently created within the temp folder (C:\Users\<username>\AppData\Local\Temp\MEI<random-number>). The temp folder is of course recreated every time Electron is started. Therefore, neither the config nor the wallet is saved permanently in this version. In previous versions I found the "electron_cash_data" directory permanently in the directory where the portable exe file was executed.

**Comment by PiRK** [comment] 2024-04-14 09:57
This is caused by a change in behavior in pyinstaller. Previously pyinstaller resolved the `__file__` variable in the main script as the location of the exe file. Now it resolves it as the temp directory where some stuff is extracted while the program is running.
https://github.com/Electron-Cash/Electron-Cash/blob/master/electron-cash#L61

**Comment by cculianu** [comment] 2024-04-14 10:53
Thanks for the info @PiRK .. I will work on a fix, backporting part of how you guys fixed it.

**Comment by cculianu** [comment] 2024-04-17 15:07
This has been fixed by #2833

**Closed** 2024-04-17 15:07 UTC
