### ISSUE TITLE
java.util.FormatFlagsConversionMismatchException: Conversion = s, Flags =  

### ISSUE THREAD

**Issue by ProfessorVenkman** [Electron-Cash/Electron-Cash#1897] opened 2020-06-14 03:30 UTC
Crash Report
============

This crash report was reported through the automatic crash reporting system 🤖

Traceback
--------------

```Python traceback
	at java.util.Formatter$FormatSpecifier.failMismatch(Formatter.java:4131)
	at java.util.Formatter$FormatSpecifier.checkBadFlags(Formatter.java:3035)
	at java.util.Formatter$FormatSpecifier.checkGeneral(Formatter.java:2993)
	at java.util.Formatter$FormatSpecifier.<init>(Formatter.java:2764)
	at java.util.Formatter$FormatSpecifierParser.<init>(Formatter.java:2591)
	at java.util.Formatter.parse(Formatter.java:2524)
	at java.util.Formatter.format(Formatter.java:2472)
	at java.util.Formatter.format(Formatter.java:2426)
	at java.lang.String.format(String.java:2670)
	at android.content.res.Resources.getString(Resources.java:1249)
	at androidx.fragment.app.Fragment.getString(Fragment.java:873)
	at org.electroncash.electroncash3.WalletDeleteConfirmDialog.onBuildDialog(Main.kt:443)
	at org.electroncash.electroncash3.AlertDialogFragment.onCreateDialog(Dialog.kt:39)
	at org.electroncash.electroncash3.AlertDialogFragment.onCreateDialog(Dialog.kt:27)
	at androidx.fragment.app.DialogFragment.onGetLayoutInflater(DialogFragment.java:380)
	at androidx.fragment.app.Fragment.performGetLayoutInflater(Fragment.java:1412)
	at androidx.fragment.app.FragmentManagerImpl.moveToState(FragmentManagerImpl.java:881)
	at androidx.fragment.app.FragmentManagerImpl.moveFragmentToExpectedState(FragmentManagerImpl.java:1238)
	at androidx.fragment.app.FragmentManagerImpl.moveToState(FragmentManagerImpl.java:1303)
	at androidx.fragment.app.BackStackRecord.executeOps(BackStackRecord.java:439)
	at androidx.fragment.app.FragmentManagerImpl.executeOps(FragmentManagerImpl.java:2079)
	at androidx.fragment.app.FragmentManagerImpl.executeOpsTogether(FragmentManagerImpl.java:1869)
	at androidx.fragment.app.FragmentManagerImpl.removeRedundantOperationsAndExecute(FragmentManagerImpl.java:1824)
	at androidx.fragment.app.FragmentManagerImpl.execSingleAction(FragmentManagerImpl.java:1696)
	at androidx.fragment.app.BackStackRecord.commitNow(BackStackRecord.java:293)
	at androidx.fragment.app.DialogFragment.showNow(DialogFragment.java:192)
	at org.electroncash.electroncash3.UtilKt.showDialog(Util.kt:73)
	at org.electroncash.electroncash3.UtilKt.showDialog$default(Util.kt:66)
	at org.electroncash.electroncash3.MainActivity.onOptionsItemSelected(Main.kt:242)
	at android.app.Activity.onMenuItemSelected(Activity.java:3379)
	at androidx.fragment.app.FragmentActivity.onMenuItemSelected(FragmentActivity.java:384)
	at androidx.appcompat.app.AppCompatActivity.onMenuItemSelected(AppCompatActivity.java:219)
	at androidx.appcompat.view.WindowCallbackWrapper.onMenuItemSelected(WindowCallbackWrapper.java:109)
	at androidx.appcompat.view.WindowCallbackWrapper.onMenuItemSelected(WindowCallbackWrapper.java:109)
	at androidx.appcompat.app.ToolbarActionBar$2.onMenuItemClick(ToolbarActionBar.java:64)
	at androidx.appcompat.widget.Toolbar$1.onMenuItemClick(Toolbar.java:207)
	at androidx.appcompat.widget.ActionMenuView$MenuBuilderCallback.onMenuItemSelected(ActionMenuView.java:781)
	at androidx.appcompat.view.menu.MenuBuilder.dispatchMenuItemSelected(MenuBuilder.java:840)
	at androidx.appcompat.view.menu.MenuItemImpl.invoke(MenuItemImpl.java:158)
	at androidx.appcompat.view.menu.MenuBuilder.performItemAction(MenuBuilder.java:991)
	at androidx.appcompat.view.menu.MenuPopup.onItemClick(MenuPopup.java:128)
	at android.widget.AdapterView.performItemClick(AdapterView.java:339)
	at android.widget.AbsListView.performItemClick(AbsListView.java:1705)
	at android.widget.AbsListView$PerformClick.run(AbsListView.java:4171)
	at android.widget.AbsListView$13.run(AbsListView.java:6734)
	at android.os.Handler.handleCallback(Handler.java:751)
	at android.os.Handler.dispatchMessage(Handler.java:95)
	at android.os.Looper.loop(Looper.java:154)
	at android.app.ActivityThread.main(ActivityThread.java:6682)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1520)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1410)
java.util.FormatFlagsConversionMismatchException: Conversion = s, Flags =  
```

Reporter
------------

This issue was reported by 2 user(s):

| Electron Cash Version  | Python Version | Operating System  | Wallet Type  | Locale |
|---|---|---|---|---|
| 4.0.14-0  | 3.6.5 (default, Sep 11 2019, 15:39:45)  [GCC 4.9] | Android 7.0 on samsung SM-G920F (zeroflte) | unknown | fr_FR | 
| 4.0.14-0  | 3.6.5 (default, Sep 11 2019, 15:39:45)  [GCC 4.9] | Android 7.0 on TP-Link Neffos X1 (X1) | unknown | fr_FR | 

Additional Information
------------------------

> rien

---

**Comment by mhsmith** [comment] 2020-09-27 22:49
Duplicate of #1899.

**Closed by mhsmith** 2020-09-27 22:49 UTC
