### ISSUE TITLE
java.lang.IllegalArgumentException: reportSizeConfigurations: ActivityRecord not found for: Token{b1c904 ActivityRecord{206a117 u0 org.electroncash.wallet/org.electroncash.electroncash3.MainActivity t-1 f}}

### ISSUE THREAD

**Issue by ProfessorVenkman** [Electron-Cash/Electron-Cash#2076] opened 2020-11-28 20:07 UTC
Crash Report
============

This crash report was reported through the automatic crash reporting system 🤖

Traceback
--------------

```Python traceback
	at android.os.Parcel.readException(Parcel.java:2017)
	at android.os.Parcel.readException(Parcel.java:1959)
	at android.app.IActivityManager$Stub$Proxy.reportSizeConfigurations(IActivityManager.java:9262)
	at android.app.ActivityThread.reportSizeConfigurations(ActivityThread.java:2958)
	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2901)
	at android.app.ActivityThread.-wrap11(Unknown Source:0)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1623)
	at android.os.Handler.dispatchMessage(Handler.java:106)
	at android.os.Looper.loop(Looper.java:164)
	at android.app.ActivityThread.main(ActivityThread.java:6548)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:438)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:857)
java.lang.IllegalArgumentException: reportSizeConfigurations: ActivityRecord not found for: Token{b1c904 ActivityRecord{206a117 u0 org.electroncash.wallet/org.electroncash.electroncash3.MainActivity t-1 f}}
```

Reporter
------------

This issue was reported by 1 user(s):

| Electron Cash Version  | Python Version | Operating System  | Wallet Type  | Locale |
|---|---|---|---|---|
| 4.2.0-0  | 3.6.5 (default, Sep 11 2019, 15:30:12)  [GCC 4.9] | Android 8.1.0 on LUSH_MINT LM5184G (LM5184G) | unknown | en_US | 

Additional Information
------------------------

The reporting user(s) did not provide additional information.

**Comment by mhsmith** [comment] 2020-11-29 21:30
Duplicate of #1653.

**Closed by mhsmith** 2020-11-29 21:30 UTC
