### ISSUE TITLE
MemoryError: 

### ISSUE THREAD

**Issue by ProfessorVenkman** [Electron-Cash/Electron-Cash#1868] opened 2020-05-05 01:59 UTC
Crash Report
============

This crash report was reported through the automatic crash reporting system 🤖

Traceback
--------------

```Python traceback
  File "site-packages\electron_cash_slp-3.6.1-py3.6.egg\electroncash_gui\qt\main_window.py", line 898, in timer_actions
  File "site-packages\electron_cash_slp-3.6.1-py3.6.egg\electroncash_gui\qt\main_window.py", line 1103, in _update_wallet
  File "site-packages\electron_cash_slp-3.6.1-py3.6.egg\electroncash_gui\qt\util.py", line 1222, in wrapper
  File "site-packages\electron_cash_slp-3.6.1-py3.6.egg\electroncash_gui\qt\util.py", line 1162, in invoke
  File "site-packages\electron_cash_slp-3.6.1-py3.6.egg\electroncash_gui\qt\util.py", line 1065, in invoke
  File "site-packages\electron_cash_slp-3.6.1-py3.6.egg\electroncash_gui\qt\util.py", line 1077, in _invoke
  File "site-packages\electron_cash_slp-3.6.1-py3.6.egg\electroncash_gui\qt\util.py", line 1106, in _doIt
  File "site-packages\electron_cash_slp-3.6.1-py3.6.egg\electroncash_gui\qt\util.py", line 1180, in _call_func_for_all
  File "site-packages\electron_cash_slp-3.6.1-py3.6.egg\electroncash_gui\qt\main_window.py", line 1108, in update_tabs
  File "site-packages\electron_cash_slp-3.6.1-py3.6.egg\electroncash_gui\qt\util.py", line 1222, in wrapper
  File "site-packages\electron_cash_slp-3.6.1-py3.6.egg\electroncash_gui\qt\util.py", line 1162, in invoke
  File "site-packages\electron_cash_slp-3.6.1-py3.6.egg\electroncash_gui\qt\util.py", line 1065, in invoke
  File "site-packages\electron_cash_slp-3.6.1-py3.6.egg\electroncash_gui\qt\util.py", line 1077, in _invoke
  File "site-packages\electron_cash_slp-3.6.1-py3.6.egg\electroncash_gui\qt\util.py", line 1106, in _doIt
  File "site-packages\electron_cash_slp-3.6.1-py3.6.egg\electroncash_gui\qt\util.py", line 1180, in _call_func_for_all
  File "site-packages\electron_cash_slp-3.6.1-py3.6.egg\electroncash_gui\qt\history_list.py", line 83, in update
  File "site-packages\electron_cash_slp-3.6.1-py3.6.egg\electroncash_gui\qt\util.py", line 724, in update
  File "site-packages\electron_cash_slp-3.6.1-py3.6.egg\electroncash\util.py", line 344, in <lambda>
  File "site-packages\electron_cash_slp-3.6.1-py3.6.egg\electroncash\util.py", line 340, in do_profile
  File "site-packages\electron_cash_slp-3.6.1-py3.6.egg\electroncash_gui\qt\history_list.py", line 155, in on_update
  File "site-packages\electron_cash_slp-3.6.1-py3.6.egg\electroncash_gui\qt\history_list.py", line 99, in addTopLevelItem
  File "c:\python3.6.8\lib\weakref.py", line 168, in __setitem__

MemoryError: 
```

Reporter
------------

This issue was reported by 1 user(s):

| Electron Cash Version  | Python Version | Operating System  | Wallet Type  | Locale |
|---|---|---|---|---|
| 3.6.1  | 3.6.8 (tags/v3.6.8:3c6b436a57, Dec 23 2018, 23:31:17) [MSC v.1916 32 bit (Intel)] | Windows-10-10.0.18362-SP0 | slp_imported_addr,imported_addr | de_DE | 

Additional Information
------------------------

> baby636@outlook.de

---

**Comment by cculianu** [comment] 2020-05-07 09:22
Duplicate of #1871, #1869 , #1867

**Closed by cculianu** 2020-05-07 09:22 UTC
Labels: SLP
