### ISSUE TITLE
SSL certificate likely race condition on SSL error (FileNotFoundError)

### ISSUE THREAD

**Issue by ProfessorVenkman** [Electron-Cash/Electron-Cash#631] opened 2018-04-04 21:21 UTC
Crash Report
============

This crash report was reported through the automatic crash reporting system 🤖

Traceback
--------------

```Python traceback
  File "site-packages\electron_cash-3.1.6-py3.5.egg\electroncash\util.py", line 613, in run_with_except_hook
  File "site-packages\electron_cash-3.1.6-py3.5.egg\electroncash\interface.py", line 233, in run
  File "site-packages\electron_cash-3.1.6-py3.5.egg\electroncash\interface.py", line 200, in get_socket

FileNotFoundError: [WinError 2] The system cannot find the file specified: 'C:\\Users\\kids stalker\\AppData\\Roaming\\ElectronCash\\certs\\crypto.mldlabs.com.temp' -> 'C:\\Users\\kids stalker\\AppData\\Roaming\\ElectronCash\\certs\\crypto.mldlabs.com.rej'
```

Reporter
------------

This issue was reported by 3 user(s):

| Electrum Version  | Operating System  | Wallet Type  | Locale |
|---|---|---|---|
| 3.1.6  | Windows-8.1-6.3.9600 | standard | en_AU |
| 3.2  | Linux-4.15.0-2-amd64-x86_64-with-debian-9.4 | standard | en_US |
| 3.1.6  | Linux-4.17.6-1-ARCH-x86_64-with-arch | standard | de_DE |

Additional Information
------------------------

The reporting user(s) did not provide additional information.

**Comment by cculianu** [comment] 2019-01-18 02:43
I think this is a dupe of #1100 and #1011. Closed those but keeping this open.

**Closed** 2024-09-15 19:03 UTC
Labels: bug
