### ISSUE TITLE
PermissionError: [WinError 5] Access is denied: 'C:\\Program Files\\electrum cash\\electron_cash_data\\certs\\crypto.mldlabs.com.temp' -> 'C:\\Program Files\\electrum cash\\electron_cash_data\\certs\\crypto.mldlabs.com'

### ISSUE THREAD

**Issue by ProfessorVenkman** [Electron-Cash/Electron-Cash#922] opened 2018-11-08 02:43 UTC
Crash Report
============

This crash report was reported through the automatic crash reporting system 🤖

Traceback
--------------

```Python traceback
  File "site-packages\electron_cash-3.1.6-py3.5.egg\electroncash\util.py", line 613, in run_with_except_hook
  File "site-packages\electron_cash-3.1.6-py3.5.egg\electroncash\interface.py", line 233, in run
  File "site-packages\electron_cash-3.1.6-py3.5.egg\electroncash\interface.py", line 228, in get_socket

PermissionError: [WinError 5] Access is denied: 'C:\\Program Files\\electrum cash\\electron_cash_data\\certs\\crypto.mldlabs.com.temp' -> 'C:\\Program Files\\electrum cash\\electron_cash_data\\certs\\crypto.mldlabs.com'
```

Reporter
------------

This issue was reported by 5 user(s):

| Electron Cash Version  | Python Version | Operating System  | Wallet Type  | Locale |
|---|---|---|---|---|
| 3.1.6  |  | Windows-7-6.1.7601-SP1 | standard | en_US | 
| 3.1.6  |  | Windows-7-6.1.7601-SP1 | standard | en_US | 
| 3.3.2  | 3.5.4 (v3.5.4:3f56838, Aug  8 2017, 02:07:06) [MSC v.1900 32 bit (Intel)] | Windows-10-10.0.17134 | imported_privkey | pl_PL | 
| 3.3.2  | 3.5.4 (v3.5.4:3f56838, Aug  8 2017, 02:07:06) [MSC v.1900 32 bit (Intel)] | Windows-10-10.0.17134 | standard | es_CO | 
| 3.3.2  | 3.5.4 (v3.5.4:3f56838, Aug  8 2017, 02:07:06) [MSC v.1900 32 bit (Intel)] | Windows-10-10.0.17134 | standard | es_CO | 

Additional Information
------------------------

The reporting user(s) did not provide additional information.

**Comment by cculianu** [comment] 2019-01-18 02:15
I'm pretty sure this is a dupe of #948.

There are race conditions in this code where I think it tries to connect to the same server in multiple threads at the same time.

**Closed by cculianu** 2019-01-18 02:15 UTC
Labels: duplicate

**Comment by ProfessorVenkman** [comment] 2019-02-21 07:48
Good morning @cculianu,

I just received another crash report related to this issue. The crash occured on Electron Cash 3.3.4CS.
I'm not sure which versions of Electron Cash include the fix but this is the first report from anything
newer than 3.3.2 since you closed the issue.

Could you please check if this issue really is resolved? Here is the traceback that I just collected:

```Python traceback
  File "site-packages\electron_cash-3.3.4cs-py3.5.egg\electroncash\util.py", line 630, in run_with_except_hook
  File "site-packages\electron_cash-3.3.4cs-py3.5.egg\electroncash\interface.py", line 240, in run
  File "site-packages\electron_cash-3.3.4cs-py3.5.egg\electroncash\interface.py", line 235, in get_socket

PermissionError: [WinError 5] 拒绝访问。: 'C:\\WINDOWS\\system32\\electron_cash_data\\certs\\bitcoincash.quangld.com.temp' -> 'C:\\WINDOWS\\system32\\electron_cash_data\\certs\\bitcoincash.quangld.com'
```


~ _With robotic wishes_
