### ISSUE TITLE
android.view.WindowManager$BadTokenException: Unable to add window -- token android.os.BinderProxy@5a66d5f is not valid; is your activity running?

### ISSUE THREAD

**Issue by ProfessorVenkman** [Electron-Cash/Electron-Cash#1626] opened 2019-09-20 18:37 UTC
Crash Report
============

This crash report was reported through the automatic crash reporting system 🤖

Traceback
--------------

```Python traceback
	at android.view.ViewRootImpl.setView(ViewRootImpl.java:689)
	at android.view.WindowManagerGlobal.addView(WindowManagerGlobal.java:342)
	at android.view.WindowManagerImpl.addView(WindowManagerImpl.java:94)
	at android.widget.Toast$TN.handleShow(Toast.java:511)
	at android.widget.Toast$TN$2.handleMessage(Toast.java:385)
	at android.os.Handler.dispatchMessage(Handler.java:102)
	at android.os.Looper.loop(Looper.java:163)
	at android.app.ActivityThread.main(ActivityThread.java:6228)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:886)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:776)
android.view.WindowManager$BadTokenException: Unable to add window -- token android.os.BinderProxy@5a66d5f is not valid; is your activity running?
```

Reporter
------------

This issue was reported by 1 user(s):

| Electron Cash Version  | Python Version | Operating System  | Wallet Type  | Locale |
|---|---|---|---|---|
| 4.0.9-0  | 3.6.5 (default, Dec  7 2018, 13:59:54)  [GCC 4.9] | Android 7.1.1 on ZTE Z839 (sweet) | unknown | en_US | 

Additional Information
------------------------

> Attempting to send a BCH payment to a Payment Protocol QR code,  maxed out the fee 

---

**Comment by mhsmith** [comment] 2019-09-22 12:44
Duplicate of #1528, please close.

**Comment by cculianu** [comment] 2019-09-22 13:17
Ok, thank you for the follow-up.

**Closed by cculianu** 2019-09-22 13:17 UTC
Labels: android, duplicate
