### ISSUE TITLE
AttributeError: 'str' object has no attribute 'get'

### ISSUE THREAD

**Issue by ProfessorVenkman** [Electron-Cash/Electron-Cash#1156] opened 2019-02-13 07:57 UTC
Crash Report
============

This crash report was reported through the automatic crash reporting system 🤖

Traceback
--------------

```Python traceback
  File "site-packages\electron_cash-3.1.6-py3.5.egg\electroncash\util.py", line 613, in run_with_except_hook
  File "site-packages\electron_cash-3.1.6-py3.5.egg\electroncash\network.py", line 960, in run
  File "site-packages\electron_cash-3.1.6-py3.5.egg\electroncash\network.py", line 927, in wait_on_sockets
  File "site-packages\electron_cash-3.1.6-py3.5.egg\electroncash\network.py", line 615, in process_responses
  File "site-packages\electron_cash-3.1.6-py3.5.egg\electroncash\network.py", line 535, in process_response
  File "site-packages\electron_cash-3.1.6-py3.5.egg\electroncash\network.py", line 968, in on_notify_header

AttributeError: 'str' object has no attribute 'get'
```

Reporter
------------

This issue was reported by 1 user(s):

| Electron Cash Version  | Python Version | Operating System  | Wallet Type  | Locale |
|---|---|---|---|---|
| 3.1.6  |  | Windows-7-6.1.7601-SP1 | standard | ru_RU | 

Additional Information
------------------------

The reporting user(s) did not provide additional information.

**Comment by cculianu** [comment] 2019-02-13 08:23
Duplicate of #1154 . Has been since fixed in newer code.

**Closed by cculianu** 2019-02-13 08:23 UTC
Labels: duplicate
