### ISSUE TITLE
Electron 4.2.4 fails to run on Debian stable

### ISSUE THREAD

**Issue by X3KT0** [Electron-Cash/Electron-Cash#2263] opened 2021-04-30 21:39 UTC
The new Electron AppImage fails to run on Debian Buster (stable), and, probably on earlier Debian versions:

[code]user@machine:~$ bin/Electron-Cash-4.2.4-x86_64.AppImage 
qt.qpa.plugin: Could not load the Qt platform plugin "xcb" in "" even though it was found.
This application failed to start because no Qt platform plugin could be initialized. Reinstalling the application may fix this problem.

Available platform plugins are: eglfs, linuxfb, minimal, minimalegl, offscreen, vnc, wayland-egl, wayland, wayland-xcomposite-egl, wayland-xcomposite-glx, webgl, xcb.

Abort
user@machine:~$[/code]

After small investigation, it seems highly likely™ that the problem is generated by an absence of libxcb-util.so.1 on Debian Buster and all earlier Debian releases. They have only libxcb-util.so.0

**Comment by EchterAgo** [comment] 2021-05-01 04:14
Fixed by #2197 and #2245

**Comment by EchterAgo** [comment] 2021-05-01 04:15
Duplicate of #2189

**Closed** 2021-05-01 11:35 UTC
Labels: Fixed
