### ISSUE TITLE
java.lang.RuntimeException: Unable to create application org.electroncash.electroncash3.App: com.chaquo.python.PyException: FileNotFoundError: [Errno 2] No such file or directory: '/data/user/0/org.electroncash.wallet/cache/chaquopy/tmp/tmphbyi5bc8'

### ISSUE THREAD

**Issue by ProfessorVenkman** [Electron-Cash/Electron-Cash#1606] opened 2019-09-02 19:36 UTC
Crash Report
============

This crash report was reported through the automatic crash reporting system 🤖

Traceback
--------------

```Python traceback
	at android.app.ActivityThread.handleBindApplication(ActivityThread.java:5718)
	at android.app.ActivityThread.-wrap2(ActivityThread.java)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1691)
	at android.os.Handler.dispatchMessage(Handler.java:102)
	at android.os.Looper.loop(Looper.java:186)
	at android.app.ActivityThread.main(ActivityThread.java:6509)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:914)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:804)
Caused by: com.chaquo.python.PyException: FileNotFoundError: [Errno 2] No such file or directory: '/data/user/0/org.electroncash.wallet/cache/chaquopy/tmp/tmphbyi5bc8'
	at <python>._mkstemp_inner(stdlib/tempfile.py:260)
	at <python>.NamedTemporaryFile(stdlib/tempfile.py:549)
	at <python>.load_pycryptodome_raw_lib(/android_asset/chaquopy/requirements-common.zip/Cryptodome/Util/_raw_api.py:270)
	at <python>.<module>(/android_asset/chaquopy/requirements-common.zip/Cryptodome/Hash/SHA384.py:47)
	at <python>.load_module_impl(/data/user/0/org.electroncash.wallet/files/chaquopy/bootstrap.zip/java/android/importer.py:435)
	at <python>.load_module(/data/user/0/org.electroncash.wallet/files/chaquopy/bootstrap.zip/java/android/importer.py:353)
	at <python>._load_backward_compatible(<frozen importlib._bootstrap>:626)
	at <python>._load_unlocked(<frozen importlib._bootstrap>:656)
	at <python>._find_and_load_unlocked(<frozen importlib._bootstrap>:955)
	at <python>._find_and_load(<frozen importlib._bootstrap>:971)
	at <python>.java.chaquopy.import_override(import.pxi:18)
	at <python>.<module>(/android_asset/chaquopy/requirements-common.zip/dns/dnssec.py:487)
	at <python>.load_module_impl(/data/user/0/org.electroncash.wallet/files/chaquopy/bootstrap.zip/java/android/importer.py:435)
	at <python>.load_module(/data/user/0/org.electroncash.wallet/files/chaquopy/bootstrap.zip/java/android/importer.py:353)
	at <python>._load_backward_compatible(<frozen importlib._bootstrap>:626)
	at <python>._load_unlocked(<frozen importlib._bootstrap>:656)
	at <python>._find_and_load_unlocked(<frozen importlib._bootstrap>:955)
	at <python>._find_and_load(<frozen importlib._bootstrap>:971)
	at <python>.java.chaquopy.import_override(import.pxi:18)
	at <python>.<module>(/android_asset/chaquopy/app.zip/electroncash/dnssec.py:42)
	at <python>.load_module_impl(/data/user/0/org.electroncash.wallet/files/chaquopy/bootstrap.zip/java/android/importer.py:435)
	at <python>.load_module(/data/user/0/org.electroncash.wallet/files/chaquopy/bootstrap.zip/java/android/importer.py:353)
	at <python>._load_backward_compatible(<frozen importlib._bootstrap>:626)
	at <python>._load_unlocked(<frozen importlib._bootstrap>:656)
	at <python>._find_and_load_unlocked(<frozen importlib._bootstrap>:955)
	at <python>._find_and_load(<frozen importlib._bootstrap>:971)
	at <python>.java.chaquopy.import_override(import.pxi:18)
	at <python>.<module>(/android_asset/chaquopy/app.zip/electroncash/contacts.py:32)
	at <python>.load_module_impl(/data/user/0/org.electroncash.wallet/files/chaquopy/bootstrap.zip/java/android/importer.py:435)
	at <python>.load_module(/data/user/0/org.electroncash.wallet/files/chaquopy/bootstrap.zip/java/android/importer.py:353)
	at <python>._load_backward_compatible(<frozen importlib._bootstrap>:626)
	at <python>._load_unlocked(<frozen importlib._bootstrap>:656)
	at <python>._find_and_load_unlocked(<frozen importlib._bootstrap>:955)
	at <python>._find_and_load(<frozen importlib._bootstrap>:971)
	at <python>.java.chaquopy.import_override(import.pxi:18)
	at <python>.<module>(/android_asset/chaquopy/app.zip/electroncash/wallet.py:67)
	at <python>.load_module_impl(/data/user/0/org.electroncash.wallet/files/chaquopy/bootstrap.zip/java/android/importer.py:435)
	at <python>.load_module(/data/user/0/org.electroncash.wallet/files/chaquopy/bootstrap.zip/java/android/importer.py:353)
	at <python>._load_backward_compatible(<frozen importlib._bootstrap>:626)
	at <python>._load_unlocked(<frozen importlib._bootstrap>:656)
	at <python>._find_and_load_unlocked(<frozen importlib._bootstrap>:955)
	at <python>._find_and_load(<frozen importlib._bootstrap>:971)
	at <python>.java.chaquopy.import_override(import.pxi:18)
	at <python>.<module>(/android_asset/chaquopy/app.zip/electroncash/__init__.py:3)
	at <python>.load_module_impl(/data/user/0/org.electroncash.wallet/files/chaquopy/bootstrap.zip/java/android/importer.py:435)
	at <python>.load_module(/data/user/0/org.electroncash.wallet/files/chaquopy/bootstrap.zip/java/android/importer.py:353)
	at <python>._load_backward_compatible(<frozen importlib._bootstrap>:626)
	at <python>._load_unlocked(<frozen importlib._bootstrap>:656)
	at <python>._find_and_load_unlocked(<frozen importlib._bootstrap>:955)
	at <python>._find_and_load(<frozen importlib._bootstrap>:971)
	at <python>._gcd_import(<frozen importlib._bootstrap>:994)
	at <python>._call_with_frames_removed(<frozen importlib._bootstrap>:219)
	at <python>._find_and_load_unlocked(<frozen importlib._bootstrap>:941)
	at <python>._find_and_load(<frozen importlib._bootstrap>:971)
	at <python>._gcd_import(<frozen importlib._bootstrap>:994)
	at <python>.import_module(stdlib/importlib/__init__.py:126)
	at <python>.chaquopy_java.Java_com_chaquo_python_Python_getModule(chaquopy_java.pyx:153)
	at com.chaquo.python.Python.getModule(Native Method)
	at org.electroncash.electroncash3.DaemonKt.libMod(Daemon.kt:15)
	at org.electroncash.electroncash3.NetworkKt$libNetwork$2.invoke(Network.kt:30)
	at org.electroncash.electroncash3.NetworkKt$libNetwork$2.invoke(Network.kt)
	at kotlin.SynchronizedLazyImpl.getValue(LazyJVM.kt:74)
	at org.electroncash.electroncash3.NetworkKt.getLibNetwork(Network.kt)
	at org.electroncash.electroncash3.SettingsKt.setDefaultValues(Settings.kt:38)
	at org.electroncash.electroncash3.SettingsKt.initSettings(Settings.kt:23)
	at org.electroncash.electroncash3.App.onCreate(App.kt:47)
	at android.app.Instrumentation.callApplicationOnCreate(Instrumentation.java:1025)
	at android.app.ActivityThread.handleBindApplication(ActivityThread.java:5715)
	... 8 more
java.lang.RuntimeException: Unable to create application org.electroncash.electroncash3.App: com.chaquo.python.PyException: FileNotFoundError: [Errno 2] No such file or directory: '/data/user/0/org.electroncash.wallet/cache/chaquopy/tmp/tmphbyi5bc8'
```

Reporter
------------

This issue was reported by 1 user(s):

| Electron Cash Version  | Python Version | Operating System  | Wallet Type  | Locale |
|---|---|---|---|---|
| 4.0.9-0  | 3.6.5 (default, Dec  7 2018, 14:03:01)  [GCC 4.9] | Android 7.1.1 on OPPO CPH1801 (CPH1801) | unknown | en_US | 

Additional Information
------------------------

The reporting user(s) did not provide additional information.

**Comment by cculianu** [comment] 2019-09-02 19:50
Fixed in #1605

**Comment by mhsmith** [comment] 2019-09-02 20:36
Actually no, this is something different. Looks like another instance of a disappearing cache, which will be fixed by upgrading to the newest version of Chaquopy (#1566).

**Comment by cculianu** [comment] 2019-09-03 16:12
Ok, will just leave it open until Jonald acts.

**Comment by mhsmith** [comment] 2019-09-20 10:27
Probable duplicate of #1566, please close.

**Closed** 2019-09-22 13:17 UTC
Labels: android, duplicate
