### ISSUE TITLE
com.chaquo.python.PyException: AssertionError: 

### ISSUE THREAD

**Issue by ProfessorVenkman** [Electron-Cash/Electron-Cash#1038] opened 2018-12-13 10:54 UTC
Crash Report
============

This crash report was reported through the automatic crash reporting system 🤖

Traceback
--------------

```Python traceback
	at <python>.get_header_at_height(/data/user/0/org.electroncash.wallet/cache/chaquopy/AssetFinder/app.zip/electroncash/blockchain.py:184)
	at <python>.connect_chunk(/data/user/0/org.electroncash.wallet/cache/chaquopy/AssetFinder/app.zip/electroncash/blockchain.py:563)
	at <python>.on_block_headers(/data/user/0/org.electroncash.wallet/cache/chaquopy/AssetFinder/app.zip/electroncash/network.py:925)
	at <python>.process_response(/data/user/0/org.electroncash.wallet/cache/chaquopy/AssetFinder/app.zip/electroncash/network.py:610)
	at <python>.process_responses(/data/user/0/org.electroncash.wallet/cache/chaquopy/AssetFinder/app.zip/electroncash/network.py:667)
	at <python>.wait_on_sockets(/data/user/0/org.electroncash.wallet/cache/chaquopy/AssetFinder/app.zip/electroncash/network.py:1170)
	at <python>.run(/data/user/0/org.electroncash.wallet/cache/chaquopy/AssetFinder/app.zip/electroncash/network.py:1196)
	at <python>.run(/android_asset/chaquopy/app.zip/electroncash_gui/android/daemon.py:34)
	at <python>.reraise(/android_asset/chaquopy/requirements-common.zip/six.py:693)
	at <python>.run(/android_asset/chaquopy/app.zip/electroncash_gui/android/daemon.py:25)
	at <python>.chaquopy_java.call(chaquopy_java.pyx:274)
	at <python>.chaquopy_java.Java_com_chaquo_python_PyObject_callAttrThrows(chaquopy_java.pyx:246)
	at com.chaquo.python.PyObject.callAttrThrows(Native Method)
	at com.chaquo.python.PyInvocationHandler.invoke(PyInvocationHandler.java:31)
	at java.lang.reflect.Proxy.invoke(Proxy.java:813)
	at $Proxy4.run(Unknown Source)
	at android.os.Handler.handleCallback(Handler.java:751)
	at android.os.Handler.dispatchMessage(Handler.java:95)
	at android.os.Looper.loop(Looper.java:154)
	at android.app.ActivityThread.main(ActivityThread.java:6186)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:889)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:779)
com.chaquo.python.PyException: AssertionError: 
```

Reporter
------------

This issue was reported by 1 user(s):

| Electron Cash Version  | Python Version | Operating System  | Wallet Type  | Locale |
|---|---|---|---|---|
| 3.3.2-1  | 3.6.5 (default, Dec  7 2018, 13:59:54)  [GCC 4.9] | Android 7.1.2 on Meizu M2Note (m2note) | unknown | pl_PL | 

Additional Information
------------------------

> initial wallet synchronization of imported seed. lineage os.

---

**Comment by mhsmith** [comment] 2018-12-13 12:54
The version number and the line numbers both indicate that this build is from *before* https://github.com/Electron-Cash/Electron-Cash/pull/1033 was merged, so that isn't the cause.

**Comment by mhsmith** [comment] 2018-12-13 13:08
The code says `base_height != self.height() + 1`, but it's only valid for `base_height < self.height() + 1`. I guess the crash happened when `base_height > self.height() + 1`, i.e. the entire chunk is too high to be connected to the blockchain.

https://github.com/Electron-Cash/Electron-Cash/blob/007a106c4d4964eb369308e2c3ac7257e9da771c/lib/blockchain.py#L537

https://github.com/Electron-Cash/Electron-Cash/blob/007a106c4d4964eb369308e2c3ac7257e9da771c/lib/blockchain.py#L553-L558

**Comment by mhsmith** [comment] 2018-12-13 13:09
Hope that helps someone: I'm pretty sure I didn't cause this so I won't be pursuing it any further.

**Comment by cculianu** [comment] 2019-01-17 17:21
I'm wondering if this is fixed now that we synch to a single blockchain.  Maybe it was our bad fork code.  Regardless I'm closing...

**Closed by cculianu** 2019-01-17 17:21 UTC
