### ISSUE TITLE
FileExistsError: [WinError 183] Cannot create a file when that file already exists: 'C:\\Users\\coinstash\\AppData\\Roaming\\ElectronCash\\certs\\abc1.hsmiths.com.temp' -> 'C:\\Users\\coinstash\\AppData\\Roaming\\ElectronCash\\certs\\abc1.hsmiths.com'

### ISSUE THREAD

**Issue by ProfessorVenkman** [Electron-Cash/Electron-Cash#1011] opened 2018-12-04 00:44 UTC
Crash Report
============

This crash report was reported through the automatic crash reporting system 🤖

Traceback
--------------

```Python traceback
  File "site-packages\electron_cash-3.3.2-py3.5.egg\electroncash\util.py", line 609, in run_with_except_hook
  File "site-packages\electron_cash-3.3.2-py3.5.egg\electroncash\interface.py", line 240, in run
  File "site-packages\electron_cash-3.3.2-py3.5.egg\electroncash\interface.py", line 235, in get_socket

FileExistsError: [WinError 183] Cannot create a file when that file already exists: 'C:\\Users\\coinstash\\AppData\\Roaming\\ElectronCash\\certs\\abc1.hsmiths.com.temp' -> 'C:\\Users\\coinstash\\AppData\\Roaming\\ElectronCash\\certs\\abc1.hsmiths.com'
```

Reporter
------------

This issue was reported by 1 user(s):

| Electron Cash Version  | Python Version | Operating System  | Wallet Type  | Locale |
|---|---|---|---|---|
| 3.3.2  | 3.5.4 (v3.5.4:3f56838, Aug  8 2017, 02:07:06) [MSC v.1900 32 bit (Intel)] | Windows-7-6.1.7601-SP1 | standard | en_US | 

Additional Information
------------------------

The reporting user(s) did not provide additional information.

**Comment by cculianu** [comment] 2019-01-17 17:38
I've seen a bunch of these. I have no idea.

**Comment by cculianu** [comment] 2019-01-18 02:43
Dupe of #631

**Closed by cculianu** 2019-01-18 02:43 UTC
Labels: observation required
