### ISSUE TITLE
java.lang.RuntimeException: java.lang.reflect.InvocationTargetException

### ISSUE THREAD

**Issue by ProfessorVenkman** [Electron-Cash/Electron-Cash#2104] opened 2020-12-21 23:43 UTC
Crash Report
============

This crash report was reported through the automatic crash reporting system 🤖

Traceback
--------------

```Python traceback
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:714)
Caused by: java.lang.reflect.InvocationTargetException
	at java.lang.reflect.Method.invoke(Native Method)
	at java.lang.reflect.Method.invoke(Method.java:372)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:919)
	... 1 more
Caused by: org.electroncash.electroncash3.ToastException: Electron Cash is generating your addresses, please wait.
	at org.electroncash.electroncash3.SendDialog.<init>(Send.kt:45)
	at org.electroncash.electroncash3.MainActivity.onOptionsItemSelected(Main.kt:255)
	at android.app.Activity.onMenuItemSelected(Activity.java:2969)
	at androidx.fragment.app.FragmentActivity.onMenuItemSelected(FragmentActivity.java:384)
	at androidx.appcompat.app.AppCompatActivity.onMenuItemSelected(AppCompatActivity.java:219)
	at androidx.appcompat.view.WindowCallbackWrapper.onMenuItemSelected(WindowCallbackWrapper.java:109)
	at androidx.appcompat.view.WindowCallbackWrapper.onMenuItemSelected(WindowCallbackWrapper.java:109)
	at androidx.appcompat.app.ToolbarActionBar$2.onMenuItemClick(ToolbarActionBar.java:64)
	at androidx.appcompat.widget.Toolbar$1.onMenuItemClick(Toolbar.java:207)
	at androidx.appcompat.widget.ActionMenuView$MenuBuilderCallback.onMenuItemSelected(ActionMenuView.java:781)
	at androidx.appcompat.view.menu.MenuBuilder.dispatchMenuItemSelected(MenuBuilder.java:840)
	at androidx.appcompat.view.menu.MenuItemImpl.invoke(MenuItemImpl.java:158)
	at androidx.appcompat.view.menu.MenuBuilder.performItemAction(MenuBuilder.java:991)
	at androidx.appcompat.view.menu.MenuPopup.onItemClick(MenuPopup.java:128)
	at android.widget.AdapterView.performItemClick(AdapterView.java:305)
	at android.widget.AbsListView.performItemClick(AbsListView.java:1204)
	at android.widget.AbsListView$PerformClick.run(AbsListView.java:3169)
	at android.widget.AbsListView.onTouchUp(AbsListView.java:4033)
	at android.widget.AbsListView.onTouchEvent(AbsListView.java:3769)
	at androidx.appcompat.widget.DropDownListView.onTouchEvent(DropDownListView.java:217)
	at androidx.appcompat.widget.MenuPopupWindow$MenuDropDownListView.onTouchEvent(MenuPopupWindow.java:135)
	at android.view.View.dispatchTouchEvent(View.java:8502)
	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2439)
	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2109)
	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2445)
	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2123)
	at android.widget.PopupWindow$PopupViewContainer.dispatchTouchEvent(PopupWindow.java:1840)
	at android.view.View.dispatchPointerEvent(View.java:8709)
	at android.view.ViewRootImpl$ViewPostImeInputStage.processPointerEvent(ViewRootImpl.java:4236)
	at android.view.ViewRootImpl$ViewPostImeInputStage.onProcess(ViewRootImpl.java:4090)
	at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:3618)
	at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:3684)
	at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:3644)
	at android.view.ViewRootImpl$AsyncInputStage.forward(ViewRootImpl.java:3773)
	at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:3652)
	at android.view.ViewRootImpl$AsyncInputStage.apply(ViewRootImpl.java:3830)
	at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:3618)
	at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:3684)
	at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:3644)
	at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:3652)
	at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:3618)
	at android.view.ViewRootImpl.deliverInputEvent(ViewRootImpl.java:5955)
	at android.view.ViewRootImpl.doProcessInputEvents(ViewRootImpl.java:5929)
	at android.view.ViewRootImpl.enqueueInputEvent(ViewRootImpl.java:5896)
	at android.view.ViewRootImpl$WindowInputEventReceiver.onInputEvent(ViewRootImpl.java:6052)
	at android.view.InputEventReceiver.dispatchInputEvent(InputEventReceiver.java:193)
	at android.os.MessageQueue.nativePollOnce(Native Method)
	at android.os.MessageQueue.next(MessageQueue.java:143)
	at android.os.Looper.loop(Looper.java:122)
	at android.app.ActivityThread.main(ActivityThread.java:5401)
	... 4 more
java.lang.RuntimeException: java.lang.reflect.InvocationTargetException
```

Reporter
------------

This issue was reported by 1 user(s):

| Electron Cash Version  | Python Version | Operating System  | Wallet Type  | Locale |
|---|---|---|---|---|
| 4.2.0-0  | 3.6.5 (default, Sep 11 2019, 15:30:12)  [GCC 4.9] | Android 5.1.1 on vivo vivo Y51 (PD1510) | unknown | en_US | 

Additional Information
------------------------

The reporting user(s) did not provide additional information.

**Comment by mhsmith** [comment] 2020-12-23 14:24
Duplicate of #2032.

**Closed by mhsmith** 2020-12-23 14:24 UTC
