### ISSUE TITLE
KeyError: 'validity'

### ISSUE THREAD

**Issue by ProfessorVenkman** [Electron-Cash/Electron-Cash#1367] opened 2019-05-20 05:37 UTC
Crash Report
============

This crash report was reported through the automatic crash reporting system 🤖

Traceback
--------------

```Python traceback
  File "electron-cash", line 391, in <module>
  File "site-packages\electron_cash-3.4.1-py3.5.egg\electroncash\daemon.py", line 305, in init_gui
  File "site-packages\electron_cash-3.4.1-py3.5.egg\electroncash_gui\qt\__init__.py", line 260, in main
  File "site-packages\electron_cash-3.4.1-py3.5.egg\electroncash_gui\qt\__init__.py", line 221, in start_new_window
  File "site-packages\electron_cash-3.4.1-py3.5.egg\electroncash_gui\qt\__init__.py", line 180, in create_window_for_wallet
  File "site-packages\electron_cash-3.4.1-py3.5.egg\electroncash_gui\qt\main_window.py", line 241, in __init__
  File "site-packages\electron_cash-3.4.1-py3.5.egg\electroncash_gui\qt\main_window.py", line 424, in load_wallet
  File "site-packages\electron_cash-3.4.1-py3.5.egg\electroncash\wallet.py", line 323, in enable_slp
  File "site-packages\electron_cash-3.4.1-py3.5.egg\electroncash\wallet.py", line 950, in slp_check_validation

KeyError: 'validity'
```

Reporter
------------

This issue was reported by 1 user(s):

| Electron Cash Version  | Python Version | Operating System  | Wallet Type  | Locale |
|---|---|---|---|---|
| 3.4.1  | 3.5.4 (v3.5.4:3f56838, Aug  8 2017, 02:07:06) [MSC v.1900 32 bit (Intel)] | Windows-10-10.0.17134 | imported_privkey | en_US | 

Additional Information
------------------------

The reporting user(s) did not provide additional information.

**Comment by jcramer** [comment] 2019-06-12 23:20
I would close this.  It isn't reproducible and a lot has changed since it occurred.

**Comment by cculianu** [comment] 2019-06-13 00:40
Thanks for telling me. I want issue count down! :)

**Closed by cculianu** 2019-06-13 00:40 UTC
Labels: SLP
