### ISSUE TITLE
java.lang.IllegalArgumentException: reportSizeConfigurations: ActivityRecord not found for: Token{9105b3 ActivityRecord{8ee2770 u0 org.electroncash.wallet/org.electroncash.electroncash3.MainActivity t-1}}

### ISSUE THREAD

**Issue by ProfessorVenkman** [Electron-Cash/Electron-Cash#2419] opened 2022-04-07 21:11 UTC
Crash Report
============

This crash report was reported through the automatic crash reporting system 🤖

Traceback
--------------

```Python traceback
	at android.os.Parcel.createExceptionOrNull(Parcel.java:2389)
	at android.os.Parcel.createException(Parcel.java:2369)
	at android.os.Parcel.readException(Parcel.java:2352)
	at android.os.Parcel.readException(Parcel.java:2294)
	at android.app.IActivityTaskManager$Stub$Proxy.reportSizeConfigurations(IActivityTaskManager.java:7026)
	at android.app.ActivityThread.reportSizeConfigurations(ActivityThread.java:4071)
	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:4026)
	at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:85)
	at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135)
	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2336)
	at android.os.Handler.dispatchMessage(Handler.java:106)
	at android.os.Looper.loop(Looper.java:246)
	at android.app.ActivityThread.main(ActivityThread.java:8653)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:602)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1130)
Caused by: android.os.RemoteException: Remote stack trace:
	at com.android.server.wm.ActivityTaskManagerService.reportSizeConfigurations(ActivityTaskManagerService.java:5024)
	at android.app.IActivityTaskManager$Stub.onTransact(IActivityTaskManager.java:3328)
	at android.os.Binder.execTransactInternal(Binder.java:1190)
	at android.os.Binder.execTransact(Binder.java:1159)
java.lang.IllegalArgumentException: reportSizeConfigurations: ActivityRecord not found for: Token{9105b3 ActivityRecord{8ee2770 u0 org.electroncash.wallet/org.electroncash.electroncash3.MainActivity t-1}}
```

Reporter
------------

This issue was reported by 1 user(s):

| Electron Cash Version  | Python Version | Operating System  | Wallet Type  | Locale |
|---|---|---|---|---|
| 4.2.5-5  | 3.8.6 (default, Jan 17 2021, 16:49:54)  [Clang 7.0.2 (https://android.googlesource.com/toolchain/clang 003100370607242d | Android 11 on samsung SM-A136U (a13x) | unknown | en_US | 

Additional Information
------------------------

> java.lang.IllegalStateException: report.get("USER_COMMENT") must not be null

---

**Comment by mhsmith** [comment] 2022-04-10 20:47
Duplicate of #1653.

**Closed by mhsmith** 2022-04-10 20:47 UTC
