### ISSUE TITLE
java.lang.RuntimeException: java.lang.reflect.InvocationTargetException

### ISSUE THREAD

**Issue by ProfessorVenkman** [Electron-Cash/Electron-Cash#2105] opened 2020-12-25 16:16 UTC
Crash Report
============

This crash report was reported through the automatic crash reporting system 🤖

Traceback
--------------

```Python traceback
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1374)
Caused by: java.lang.reflect.InvocationTargetException
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:327)
	... 1 more
Caused by: org.electroncash.electroncash3.ToastException: Tato peněženka je pouze na prohlížení.
	at org.electroncash.electroncash3.SendDialog.<init>(Send.kt:41)
	at org.electroncash.electroncash3.MainActivity.onOptionsItemSelected(Main.kt:255)
	at android.app.Activity.onMenuItemSelected(Activity.java:3527)
	at androidx.fragment.app.FragmentActivity.onMenuItemSelected(FragmentActivity.java:384)
	at androidx.appcompat.app.AppCompatActivity.onMenuItemSelected(AppCompatActivity.java:219)
	at androidx.appcompat.view.WindowCallbackWrapper.onMenuItemSelected(WindowCallbackWrapper.java:109)
	at androidx.appcompat.view.WindowCallbackWrapper.onMenuItemSelected(WindowCallbackWrapper.java:109)
	at androidx.appcompat.app.ToolbarActionBar$2.onMenuItemClick(ToolbarActionBar.java:64)
	at androidx.appcompat.widget.Toolbar$1.onMenuItemClick(Toolbar.java:207)
	at androidx.appcompat.widget.ActionMenuView$MenuBuilderCallback.onMenuItemSelected(ActionMenuView.java:781)
	at androidx.appcompat.view.menu.MenuBuilder.dispatchMenuItemSelected(MenuBuilder.java:840)
	at androidx.appcompat.view.menu.MenuItemImpl.invoke(MenuItemImpl.java:158)
	at androidx.appcompat.view.menu.MenuBuilder.performItemAction(MenuBuilder.java:991)
	at androidx.appcompat.view.menu.MenuPopup.onItemClick(MenuPopup.java:128)
	at android.widget.AdapterView.performItemClick(AdapterView.java:350)
	at android.widget.AbsListView.performItemClick(AbsListView.java:1683)
	at android.widget.AbsListView$PerformClick.run(AbsListView.java:4094)
	at android.widget.AbsListView.onTouchUp(AbsListView.java:6598)
	at android.widget.AbsListView.onTouchEvent(AbsListView.java:6345)
	at android.widget.ListView.onTouchEvent(ListView.java:1700)
	at androidx.appcompat.widget.DropDownListView.onTouchEvent(DropDownListView.java:217)
	at androidx.appcompat.widget.MenuPopupWindow$MenuDropDownListView.onTouchEvent(MenuPopupWindow.java:135)
	at android.view.View.dispatchTouchEvent(View.java:12540)
	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3153)
	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2829)
	at android.widget.AbsListView.dispatchTouchEvent(AbsListView.java:6257)
	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3159)
	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2844)
	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3159)
	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2844)
	at android.widget.PopupWindow$PopupDecorView.dispatchTouchEvent(PopupWindow.java:2686)
	at android.view.View.dispatchPointerEvent(View.java:12788)
	at android.view.ViewRootImpl$ViewPostImeInputStage.processPointerEvent(ViewRootImpl.java:5670)
	at android.view.ViewRootImpl$ViewPostImeInputStage.onProcess(ViewRootImpl.java:5465)
	at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:4958)
	at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:5011)
	at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:4977)
	at android.view.ViewRootImpl$AsyncInputStage.forward(ViewRootImpl.java:5114)
	at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:4985)
	at android.view.ViewRootImpl$AsyncInputStage.apply(ViewRootImpl.java:5171)
	at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:4958)
	at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:5011)
	at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:4977)
	at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:4985)
	at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:4958)
	at android.view.ViewRootImpl.deliverInputEvent(ViewRootImpl.java:7736)
	at android.view.ViewRootImpl.doProcessInputEvents(ViewRootImpl.java:7676)
	at android.view.ViewRootImpl.enqueueInputEvent(ViewRootImpl.java:7637)
	at android.view.ViewRootImpl$WindowInputEventReceiver.onInputEvent(ViewRootImpl.java:7847)
	at android.view.InputEventReceiver.dispatchInputEvent(InputEventReceiver.java:197)
	at android.os.MessageQueue.nativePollOnce(Native Method)
	at android.os.MessageQueue.next(MessageQueue.java:325)
	at android.os.Looper.loop(Looper.java:142)
	at android.app.ActivityThread.main(ActivityThread.java:6944)
	... 3 more
java.lang.RuntimeException: java.lang.reflect.InvocationTargetException
```

Reporter
------------

This issue was reported by 1 user(s):

| Electron Cash Version  | Python Version | Operating System  | Wallet Type  | Locale |
|---|---|---|---|---|
| 4.2.0-0  | 3.6.5 (default, Sep 11 2019, 15:39:45)  [GCC 4.9] | Android 8.0.0 on samsung SM-G935F (hero2lte) | unknown | cs_CZ | 

Additional Information
------------------------

The reporting user(s) did not provide additional information.

**Comment by mhsmith** [comment] 2020-12-29 17:10
Duplicate of #2032.

**Closed** 2020-12-29 17:10 UTC
