### ISSUE TITLE
java.lang.RuntimeException: java.lang.reflect.InvocationTargetException

### ISSUE THREAD

**Issue by ProfessorVenkman** [Electron-Cash/Electron-Cash#2034] opened 2020-11-06 22:32 UTC
Crash Report
============

This crash report was reported through the automatic crash reporting system 🤖

Traceback
--------------

```Python traceback
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:502)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:964)
Caused by: java.lang.reflect.InvocationTargetException
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:492)
	... 1 more
Caused by: org.electroncash.electroncash3.ToastException: This wallet is watching-only.
	at org.electroncash.electroncash3.SendDialog.<init>(Send.kt:41)
	at org.electroncash.electroncash3.MainActivity.onOptionsItemSelected(Main.kt:255)
	at android.app.Activity.onMenuItemSelected(Activity.java:4147)
	at androidx.fragment.app.FragmentActivity.onMenuItemSelected(FragmentActivity.java:384)
	at androidx.appcompat.app.AppCompatActivity.onMenuItemSelected(AppCompatActivity.java:219)
	at androidx.appcompat.view.WindowCallbackWrapper.onMenuItemSelected(WindowCallbackWrapper.java:109)
	at androidx.appcompat.view.WindowCallbackWrapper.onMenuItemSelected(WindowCallbackWrapper.java:109)
	at androidx.appcompat.app.ToolbarActionBar$2.onMenuItemClick(ToolbarActionBar.java:64)
	at androidx.appcompat.widget.Toolbar$1.onMenuItemClick(Toolbar.java:207)
	at androidx.appcompat.widget.ActionMenuView$MenuBuilderCallback.onMenuItemSelected(ActionMenuView.java:781)
	at androidx.appcompat.view.menu.MenuBuilder.dispatchMenuItemSelected(MenuBuilder.java:840)
	at androidx.appcompat.view.menu.MenuItemImpl.invoke(MenuItemImpl.java:158)
	at androidx.appcompat.view.menu.MenuBuilder.performItemAction(MenuBuilder.java:991)
	at androidx.appcompat.view.menu.MenuPopup.onItemClick(MenuPopup.java:128)
	at android.widget.AdapterView.performItemClick(AdapterView.java:330)
	at android.widget.AbsListView.performItemClick(AbsListView.java:1255)
	at android.widget.AbsListView$PerformClick.run(AbsListView.java:3270)
	at android.os.Handler.handleCallback(Handler.java:883)
	at android.os.Handler.dispatchMessage(Handler.java:100)
	at android.os.Looper.loop(Looper.java:214)
	at android.app.ActivityThread.main(ActivityThread.java:7615)
	... 3 more
java.lang.RuntimeException: java.lang.reflect.InvocationTargetException
```

Reporter
------------

This issue was reported by 1 user(s):

| Electron Cash Version  | Python Version | Operating System  | Wallet Type  | Locale |
|---|---|---|---|---|
| 4.2.0-0  | 3.6.5 (default, Sep 11 2019, 15:39:45)  [GCC 4.9] | Android 10 on LGE LM-V600 (timelm) | unknown | en_US | 

Additional Information
------------------------

The reporting user(s) did not provide additional information.

**Comment by mhsmith** [comment] 2020-11-10 13:44
Duplicate of #2032.

**Closed by mhsmith** 2020-11-10 13:44 UTC

**Comment by ProfessorVenkman** [comment] 2025-01-17 21:44
Good evening @mhsmith,

I just received another crash report related to this issue. The crash occured on Electron Cash 4.4.1-3.
I'm not sure which versions of Electron Cash include the fix but this is the first report from anything
newer than 4.2.0-0 since you closed the issue.

Could you please check if this issue really is resolved? Here is the traceback that I just collected:

```Python traceback
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:502)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:980)
Caused by: java.lang.reflect.InvocationTargetException
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:492)
	... 1 more
Caused by: org.electroncash.electroncash3.ToastException: This wallet is watching-only.
	at org.electroncash.electroncash3.SendDialog.<init>(Send.kt:109)
	at org.electroncash.electroncash3.TokenTransactionsFragment.onViewCreated$lambda$6(TokenTransactions.kt:47)
	at org.electroncash.electroncash3.TokenTransactionsFragment.$r8$lambda$LTUupZDg5PqsZ5StldVi_K5lI9c(Unknown Source:0)
	at org.electroncash.electroncash3.TokenTransactionsFragment$$ExternalSyntheticLambda1.onClick(Unknown Source:2)
	at android.view.View.performClick(View.java:7150)
	at android.view.View.performClickInternal(View.java:7123)
	at android.view.View.access$3500(View.java:807)
	at android.view.View$PerformClick.run(View.java:27540)
	at android.os.Handler.handleCallback(Handler.java:883)
	at android.os.Handler.dispatchMessage(Handler.java:100)
	at android.os.Looper.loop(Looper.java:214)
	at android.app.ActivityThread.main(ActivityThread.java:7554)
	... 3 more
java.lang.RuntimeException: java.lang.reflect.InvocationTargetException
```


~ _With robotic wishes_
