### ISSUE TITLE
java.lang.RuntimeException: android.os.DeadSystemException

### ISSUE THREAD

**Issue by ProfessorVenkman** [Electron-Cash/Electron-Cash#2337] opened 2021-09-10 20:48 UTC
Crash Report
============

This crash report was reported through the automatic crash reporting system 🤖

Traceback
--------------

```Python traceback
	at android.app.ContextImpl.startServiceCommon(ContextImpl.java:1462)
	at android.app.ContextImpl.startService(ContextImpl.java:1404)
	at android.content.ContextWrapper.startService(ContextWrapper.java:673)
	at org.electroncash.electroncash3.CaptionKt$initCaption$2.onChanged(Caption.kt:44)
	at org.electroncash.electroncash3.CaptionKt$initCaption$2.onChanged(Caption.kt)
	at androidx.lifecycle.LiveData.considerNotify(LiveData.java:131)
	at androidx.lifecycle.LiveData.dispatchingValue(LiveData.java:149)
	at androidx.lifecycle.LiveData.setValue(LiveData.java:307)
	at androidx.lifecycle.MutableLiveData.setValue(MutableLiveData.java:50)
	at org.electroncash.electroncash3.BackgroundLiveData.refreshDone(LiveData.kt:105)
	at org.electroncash.electroncash3.BackgroundLiveData.access$refreshDone(LiveData.kt:47)
	at org.electroncash.electroncash3.BackgroundLiveData$refreshNow$1$1.invoke(LiveData.kt:99)
	at org.electroncash.electroncash3.BackgroundLiveData$refreshNow$1$1.invoke(LiveData.kt:47)
	at org.electroncash.electroncash3.AppKt$runOnUiThread$1.run(App.kt:63)
	at android.os.Handler.handleCallback(Handler.java:751)
	at android.os.Handler.dispatchMessage(Handler.java:95)
	at android.os.Looper.loop(Looper.java:154)
	at android.app.ActivityThread.main(ActivityThread.java:6816)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1563)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1451)
Caused by: android.os.DeadSystemException
	... 21 more
java.lang.RuntimeException: android.os.DeadSystemException
```

Reporter
------------

This issue was reported by 1 user(s):

| Electron Cash Version  | Python Version | Operating System  | Wallet Type  | Locale |
|---|---|---|---|---|
| N/A  | 3.8.6 (default, Jan 17 2021, 16:48:53)  [Clang 7.0.2 (https://android.googlesource.com/toolchain/clang 003100370607242d | Android 7.1.1 on samsung SM-J510FN (j5xnlte) | unknown | es_ES | 

Additional Information
------------------------

> java.lang.IllegalStateException: report.get("USER_COMMENT") must not be null

---

**Comment by mhsmith** [comment] 2021-09-10 21:42
Duplicate of #2320.

**Closed by mhsmith** 2021-09-10 21:42 UTC
