### ISSUE TITLE
java.lang.RuntimeException: java.lang.reflect.InvocationTargetException

### ISSUE THREAD

**Issue by ProfessorVenkman** [Electron-Cash/Electron-Cash#2112] opened 2020-12-29 14:52 UTC
Crash Report
============

This crash report was reported through the automatic crash reporting system 🤖

Traceback
--------------

```Python traceback
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:924)
Caused by: java.lang.reflect.InvocationTargetException
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1063)
	... 1 more
Caused by: org.electroncash.electroncash3.ToastException: Not connected
	at org.electroncash.electroncash3.ColdLoadDialog.onOK(ColdLoad.kt:76)
	at org.electroncash.electroncash3.ColdLoadDialog$onShowDialog$2.onClick(ColdLoad.kt:46)
	at android.view.View.performClick(View.java:5675)
	at android.view.View$PerformClick.run(View.java:22641)
	at android.os.Handler.handleCallback(Handler.java:836)
	at android.os.Handler.dispatchMessage(Handler.java:103)
	at android.os.Looper.loop(Looper.java:203)
	at android.app.ActivityThread.main(ActivityThread.java:6251)
	... 3 more
java.lang.RuntimeException: java.lang.reflect.InvocationTargetException
```

Reporter
------------

This issue was reported by 2 user(s):

| Electron Cash Version  | Python Version | Operating System  | Wallet Type  | Locale |
|---|---|---|---|---|
| 4.2.0-0  | 3.6.5 (default, Sep 11 2019, 15:39:45)  [GCC 4.9] | Android 7.0 on LENOVO Lenovo TB-7304F (TB-7304F) | unknown | en_AU | 
| 4.2.0-0  | 3.6.5 (default, Sep 11 2019, 15:39:45)  [GCC 4.9] | Android 7.0 on LENOVO Lenovo TB-7304F (TB-7304F) | unknown | en_AU | 

Additional Information
------------------------

> qz2fx22m42j9f0760evn6jsyexv3z5n6tvw2vz8cgl

---

> qz2fx22m42j9f0760evn6jsyexv3z5n6tvw2vz8cgl

---

**Comment by mhsmith** [comment] 2020-12-29 17:11
Duplicate of #2032.

**Closed by mhsmith** 2020-12-29 17:11 UTC
