### ISSUE TITLE
java.util.FormatFlagsConversionMismatchException: Conversion = s, Flags =  

### ISSUE THREAD

**Issue by ProfessorVenkman** [Electron-Cash/Electron-Cash#1912] opened 2020-07-15 14:34 UTC
Crash Report
============

This crash report was reported through the automatic crash reporting system 🤖

Traceback
--------------

```Python traceback
	at java.util.Formatter$FormatSpecifier.failMismatch(Formatter.java:4399)
	at java.util.Formatter$FormatSpecifier.checkBadFlags(Formatter.java:3092)
	at java.util.Formatter$FormatSpecifier.checkGeneral(Formatter.java:3050)
	at java.util.Formatter$FormatSpecifier.<init>(Formatter.java:2817)
	at java.util.Formatter$FormatSpecifierParser.<init>(Formatter.java:2625)
	at java.util.Formatter.parse(Formatter.java:2558)
	at java.util.Formatter.format(Formatter.java:2505)
	at java.util.Formatter.format(Formatter.java:2459)
	at java.lang.String.format(String.java:2911)
	at android.content.res.Resources.getString(Resources.java:500)
	at androidx.fragment.app.Fragment.getString(Fragment.java:873)
	at org.electroncash.electroncash3.WalletDeleteConfirmDialog.onBuildDialog(Main.kt:443)
	at org.electroncash.electroncash3.AlertDialogFragment.onCreateDialog(Dialog.kt:39)
	at org.electroncash.electroncash3.AlertDialogFragment.onCreateDialog(Dialog.kt:27)
	at androidx.fragment.app.DialogFragment.onGetLayoutInflater(DialogFragment.java:380)
	at androidx.fragment.app.Fragment.performGetLayoutInflater(Fragment.java:1412)
	at androidx.fragment.app.FragmentManagerImpl.moveToState(FragmentManagerImpl.java:881)
	at androidx.fragment.app.FragmentManagerImpl.moveFragmentToExpectedState(FragmentManagerImpl.java:1238)
	at androidx.fragment.app.FragmentManagerImpl.moveToState(FragmentManagerImpl.java:1303)
	at androidx.fragment.app.BackStackRecord.executeOps(BackStackRecord.java:439)
	at androidx.fragment.app.FragmentManagerImpl.executeOps(FragmentManagerImpl.java:2079)
	at androidx.fragment.app.FragmentManagerImpl.executeOpsTogether(FragmentManagerImpl.java:1869)
	at androidx.fragment.app.FragmentManagerImpl.removeRedundantOperationsAndExecute(FragmentManagerImpl.java:1824)
	at androidx.fragment.app.FragmentManagerImpl.execSingleAction(FragmentManagerImpl.java:1696)
	at androidx.fragment.app.BackStackRecord.commitNow(BackStackRecord.java:293)
	at androidx.fragment.app.DialogFragment.showNow(DialogFragment.java:192)
	at org.electroncash.electroncash3.UtilKt.showDialog(Util.kt:73)
	at org.electroncash.electroncash3.UtilKt.showDialog$default(Util.kt:66)
	at org.electroncash.electroncash3.WalletOpenDialog$onShowDialog$3.onClick(Main.kt:431)
	at android.view.View.performClick(View.java:7870)
	at android.widget.TextView.performClick(TextView.java:14959)
	at android.view.View.performClickInternal(View.java:7839)
	at android.view.View.access$3600(View.java:886)
	at android.view.View$PerformClick.run(View.java:29363)
	at android.os.Handler.handleCallback(Handler.java:883)
	at android.os.Handler.dispatchMessage(Handler.java:100)
	at android.os.Looper.loop(Looper.java:237)
	at android.app.ActivityThread.main(ActivityThread.java:7814)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1047)
java.util.FormatFlagsConversionMismatchException: Conversion = s, Flags =  
```

Reporter
------------

This issue was reported by 5 user(s):

| Electron Cash Version  | Python Version | Operating System  | Wallet Type  | Locale |
|---|---|---|---|---|
| 4.0.14-0  | 3.6.5 (default, Sep 11 2019, 15:39:45)  [GCC 4.9] | Android 10 on samsung SM-A715F (a71) | unknown | fr_FR | 
| 4.0.14-0  | 3.6.5 (default, Sep 11 2019, 15:39:45)  [GCC 4.9] | Android 10 on HUAWEI EML-L29 (HWEML) | unknown | fr_CO | 
| 4.0.14-0  | 3.6.5 (default, Sep 11 2019, 15:39:45)  [GCC 4.9] | Android 10 on samsung SM-A705FN (a70q) | unknown | fr_FR | 
| 4.0.14-0  | 3.6.5 (default, Sep 11 2019, 15:39:45)  [GCC 4.9] | Android 10 on samsung SM-N975W (d2q) | unknown | fr_CA | 
| 4.0.14-0  | 3.6.5 (default, Sep 11 2019, 15:30:12)  [GCC 4.9] | Android 10 on samsung SM-A105FN (a10) | unknown | fr_FR | 

Additional Information
------------------------

The reporting user(s) did not provide additional information.

**Comment by mhsmith** [comment] 2020-09-27 22:49
Duplicate of #1899.

**Closed by mhsmith** 2020-09-27 22:49 UTC
