### ISSUE TITLE
java.lang.RuntimeException: <Daemon(Thread-2, stopped 538445024448)> unexpectedly stopped

### ISSUE THREAD

**Issue by ProfessorVenkman** [Electron-Cash/Electron-Cash#2387] opened 2022-01-11 02:03 UTC
Crash Report
============

This crash report was reported through the automatic crash reporting system 🤖

Traceback
--------------

```Python traceback
	at org.electroncash.electroncash3.DaemonModel$2.run(Daemon.kt:55)
	at android.os.Handler.handleCallback(Handler.java:938)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loop(Looper.java:236)
	at android.app.ActivityThread.main(ActivityThread.java:7889)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:600)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:967)
java.lang.RuntimeException: <Daemon(Thread-2, stopped 538445024448)> unexpectedly stopped
```

Reporter
------------

This issue was reported by 2 user(s):

| Electron Cash Version  | Python Version | Operating System  | Wallet Type  | Locale |
|---|---|---|---|---|
| 4.2.5-5  | 3.8.6 (default, Jan 17 2021, 16:48:53)  [Clang 7.0.2 (https://android.googlesource.com/toolchain/clang 003100370607242d | Android 11 on Xiaomi M2007J20CG (surya) | unknown | en_GB | 
| 4.2.5-5  | 3.8.6 (default, Jan 17 2021, 16:48:53)  [Clang 7.0.2 (https://android.googlesource.com/toolchain/clang 003100370607242d | Android 11 on Xiaomi M2007J20CG (surya) | unknown | en_GB | 

Additional Information
------------------------

The reporting user(s) did not provide additional information.

**Comment by mhsmith** [comment] 2022-01-14 09:57
Duplicate of #1741.

**Closed by mhsmith** 2022-01-14 09:57 UTC
