### ISSUE TITLE
Error running on MacOS 10.12.6 Sierra

### ISSUE THREAD

**Issue by sir-lebowski** [Electron-Cash/Electron-Cash#955] opened 2018-11-18 14:39 UTC
[26101] Error loading Python lib '/var/folders/g5/dxtgr_kj7k989t4hbp2vhmqw0000gn/T/_MEINnwouI/Python': dlopen: dlopen(/var/folders/g5/dxtgr_kj7k989t4hbp2vhmqw0000gn/T/_MEINnwouI/Python, 10): Symbol not found: _futimens
  Referenced from: /var/folders/g5/dxtgr_kj7k989t4hbp2vhmqw0000gn/T/_MEINnwouI/Python (which was built for Mac OS X 10.13)
  Expected in: /usr/lib/libSystem.B.dylib
 in /var/folders/g5/dxtgr_kj7k989t4hbp2vhmqw0000gn/T/_MEINnwouI/Python

**Comment by cculianu** [comment] 2018-11-18 14:56
Any chance you can upgrade to High Sierra?

The problem is I have to build on El Capitan or something to fix this and it’s a pain to do so.

**Comment by cculianu** [comment] 2018-11-18 15:48
Hey man -- I just rebuilt this for El Capitan and above. I contacted Jonald and he should be putting up a new build on the official site.

If you can't wait you can get it from my site. This is legit -- you have my word on it.  

https://www.c3-soft.com/downloads/BitcoinCash/Electron-Cash/

**Comment by cculianu** [comment] 2018-11-18 17:38
Ok, we updated the official link.  I'm closing this as it's now resolved.

**Closed by cculianu** 2018-11-18 17:38 UTC
