### ISSUE TITLE
java.lang.RuntimeException: android.os.TransactionTooLargeException: data parcel size 1151044 bytes

### ISSUE THREAD

**Issue by ProfessorVenkman** [Electron-Cash/Electron-Cash#2384] opened 2022-01-04 18:29 UTC
Crash Report
============

This crash report was reported through the automatic crash reporting system 🤖

Traceback
--------------

```Python traceback
	at android.app.servertransaction.PendingTransactionActions$StopInfo.run(PendingTransactionActions.java:161)
	at android.os.Handler.handleCallback(Handler.java:883)
	at android.os.Handler.dispatchMessage(Handler.java:100)
	at android.os.Looper.loop(Looper.java:214)
	at android.app.ActivityThread.main(ActivityThread.java:7386)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:492)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:982)
Caused by: android.os.TransactionTooLargeException: data parcel size 1151044 bytes
	at android.os.BinderProxy.transactNative(Native Method)
	at android.os.BinderProxy.transact(BinderProxy.java:510)
	at android.app.IActivityTaskManager$Stub$Proxy.activityStopped(IActivityTaskManager.java:4524)
	at android.app.servertransaction.PendingTransactionActions$StopInfo.run(PendingTransactionActions.java:145)
	... 7 more
java.lang.RuntimeException: android.os.TransactionTooLargeException: data parcel size 1151044 bytes
```

Reporter
------------

This issue was reported by 1 user(s):

| Electron Cash Version  | Python Version | Operating System  | Wallet Type  | Locale |
|---|---|---|---|---|
| 4.2.3-3  | 3.8.6 (default, Jan 17 2021, 16:49:54)  [Clang 7.0.2 (https://android.googlesource.com/toolchain/clang 003100370607242d | Android 10 on TCL 9032Z (Apollo_8_4G_TMO) | unknown | en_US | 

Additional Information
------------------------

The reporting user(s) did not provide additional information.

**Comment by mhsmith** [comment] 2022-01-07 09:12
Duplicate of #1604.

**Closed by mhsmith** 2022-01-07 09:12 UTC

**Comment by ProfessorVenkman** [comment] 2022-01-16 19:03
Good evening @mhsmith,

I just received another crash report related to this issue. The crash occured on Electron Cash 4.2.5-5.
I'm not sure which versions of Electron Cash include the fix but this is the first report from anything
newer than 4.2.3-3 since you closed the issue.

Could you please check if this issue really is resolved? Here is the traceback that I just collected:

```Python traceback
	at android.app.servertransaction.PendingTransactionActions$StopInfo.run(PendingTransactionActions.java:161)
	at android.os.Handler.handleCallback(Handler.java:938)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loop(Looper.java:236)
	at android.app.ActivityThread.main(ActivityThread.java:7889)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:600)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:967)
Caused by: android.os.TransactionTooLargeException: data parcel size 2199504 bytes
	at android.os.BinderProxy.transactNative(Native Method)
	at android.os.BinderProxy.transact(BinderProxy.java:540)
	at android.app.IActivityTaskManager$Stub$Proxy.activityStopped(IActivityTaskManager.java:4627)
	at android.app.servertransaction.PendingTransactionActions$StopInfo.run(PendingTransactionActions.java:145)
	... 7 more
java.lang.RuntimeException: android.os.TransactionTooLargeException: data parcel size 2199504 bytes
```


~ _With robotic wishes_
