### ISSUE TITLE
com.chaquo.python.PyException: TypeError: '<' not supported between instances of 'NoneType' and 'int'

### ISSUE THREAD

**Issue by ProfessorVenkman** [Electron-Cash/Electron-Cash#1165] opened 2019-02-18 08:09 UTC
Crash Report
============

This crash report was reported through the automatic crash reporting system 🤖

Traceback
--------------

```Python traceback
	at <python>.__init__(/android_asset/chaquopy/requirements-common.zip/ecdsa/ecdsa.py:89)
	at <python>.__init__(/android_asset/chaquopy/app.zip/electroncash/bitcoin.py:601)
	at <python>.from_WIF_privkey(/android_asset/chaquopy/app.zip/electroncash/address.py:168)
	at <python>.import_privkey(/android_asset/chaquopy/app.zip/electroncash/keystore.py:174)
	at <python>.import_private_key(/android_asset/chaquopy/app.zip/electroncash/wallet.py:1762)
	at <python>.from_text(/android_asset/chaquopy/app.zip/electroncash/wallet.py:1715)
	at <python>.create(/android_asset/chaquopy/app.zip/electroncash_gui/android/console.py:153)
	at <python>.chaquopy_java.call(chaquopy_java.pyx:282)
	at <python>.chaquopy_java.Java_com_chaquo_python_PyObject_callAttrThrows(chaquopy_java.pyx:254)
	at com.chaquo.python.PyObject.callAttrThrows(Native Method)
	at com.chaquo.python.PyObject.callAttr(PyObject.java:207)
	at org.electroncash.electroncash3.DaemonModel.createWallet(Daemon.kt:121)
	at org.electroncash.electroncash3.NewWalletImportDialog.onCreateWallet(Wallets.kt:324)
	at org.electroncash.electroncash3.NewWalletDialog2$onShowDialog$1$1.run(Wallets.kt:248)
	at java.lang.Thread.run(Thread.java:764)
com.chaquo.python.PyException: TypeError: '<' not supported between instances of 'NoneType' and 'int'
```

Reporter
------------

This issue was reported by 1 user(s):

| Electron Cash Version  | Python Version | Operating System  | Wallet Type  | Locale |
|---|---|---|---|---|
| 3.3.5-1  | 3.6.5 (default, Dec  7 2018, 13:59:54)  [GCC 4.9] | Android 8.1.0 on samsung SM-G610F (on7xelte) | unknown | en_GB | 

Additional Information
------------------------

The reporting user(s) did not provide additional information.

**Comment by mhsmith** [comment] 2019-02-18 12:01
Doesn't appear to be the UI code's fault, because by this point it's already checked whether the private key is valid (Wallets.kt:311). So either `is_private_key` is returning true for an invalid key, or there's some other bug in the import process.

**Comment by cculianu** [comment] 2019-02-18 12:38
It might be related to something I saw on iOS #933 .  If it makes you feel better, this got me too in my coding.  Basically `is_private_key` I think checks for both WIF **and** simple hex-encoded raw private keys, and returns `True` for either one.  However, from_WIF_privkey obviously only accepts the subset that is WIF, and not raw.  It got me too... :/  You may want to use a different function to test or.. like I did.. just catch the exception and reject the raw key (since raw keys aren't particularly resilient to user input errors).

Up to you... 

(The fact that both of us made this mistake makes me feel a little better -- this API could be a lot clearer and better documented).

**Comment by cculianu** [comment] 2019-02-18 12:42
#813 is the iOS crash which looks eerily similar.  :)

**Comment by mhsmith** [comment] 2019-02-24 22:15
Actually it looks like `is_private_key` accepts only minikey and WIF formats. `from_WIF_privkey`, despite its name, accepts exactly the same two formats. 

Testing the app with some example keys from [here](https://en.bitcoin.it/wiki/Mini_private_key_format), I found it can import a minikey no problem. Trying to import a SHA256 gives an appropriate error message and does not crash.

Do you have any examples of inputs which reproduced this on iOS?

**Comment by cculianu** [comment] 2019-02-24 22:40
You're absolutely right on all counts.  I stand corrected.  I was given bad advice. And no, I don't have a key this fails on (would be nice if I did). 

I elected to just catch the TypeError and call it a day.  In retrospect I misunderstood the problem (I thought it was minikey vs WIF key -- and you are right, it most certainly is not).

So this must be a bug in ecdsa... or something else is wrong in the bitcoin.py/address.py code.

Very mysterious.  I can't reproduce it and I can't think of why it would happen.

Sorry I couldn't be more helpful... :/

Should I close this?  Or will you do the band-aid approach and just catch the TypeError and reject the key?

**Comment by cculianu** [comment] 2019-02-24 22:51
FWIW it annoys me that I got original exceptions in `from_WIF_privkey` indicating that the input wasn't a key when `is_private_key` accepted the same input as being a key.

So there may also be something funny going on in this code.. :/  See #933 (these guys weren't very helpful -- they were just being jerks to me :/  )

**Comment by mhsmith** [comment] 2019-02-24 22:56
Since this seems to be a rare problem which isn't caused by any of my code, I'm not going to pursue it. If someone else wants to put on the "band-aid" then that's fine with me.

**Comment by cculianu** [comment] 2019-02-25 11:15
You got it. Closed.

**Closed by cculianu** 2019-02-25 11:15 UTC
Labels: android

**Comment by mhsmith** [comment] 2021-01-29 03:34
Duplicate of #2133.
