### ISSUE TITLE
Can not handle 35000 txouts on same address

### ISSUE THREAD

**Issue by slanted3** [Electron-Cash/Electron-Cash#848] opened 2018-09-03 16:03 UTC
Version 3.3.1, Linux

Hangs (does nothing) with "synchronizing" in the lower left of wallet window
Started electron cash with 

    ./electron-cash  --verbose

And got

    [bch0.kister.net] connected
    [Synchronizer] response error: {'jsonrpc': '2.0', 'error': {'code': -32600, 'message': 'response too large (at least 1020631 bytes)'}, 'id': 24, 'method': 'blockchain.scripthash.get_history', 'params': ['c4e655c7f944733fe4bf9590cedc6299be529cdaa6d1d12219be3e1d4ac9b3fd']}
    [shsmithgoggryfbx.onion] connected
    [electron-cash.dragon.zone] failed to connect Socket error: timed out

**Comment by cculianu** [comment] 2018-09-10 20:58
Cool. Thanks for filing this report.  I'd like to reproduce it.  What address? I decoded that script to: qpftg47wedwv3jfhamxpw3f9r3efhscyavskss02qr (legacy: 18YJTBX4nPmc7Cf4FtyAp2fWHYptXAvCdH)

I can't find any tx's for that address...

**Comment by slanted3** [comment] 2018-09-10 21:26
The address: qzrzu47ra008ryl3vg3rzwz3edzjpntmhuy5kvxcn3

One of the transactions: fd8d847ddf69a6bc763d08203e56ed4d9dbe72f0d7a5bd7150c2a4fcc503f600

I could probably give you the private key too, it is not much, each transaction is just above dust

**Comment by cculianu** [comment] 2018-09-10 22:16
Oh wow thanks for this.  Ok yeah this is a server-side issue.  The ElectrumX server doesn't like histories for an address > 10,000 tx. I guess the server side can be configured to support larger histories but the default is 1 MB.

@kyuupichan  -- thoughts on this?

**Comment by kyuupichan** [comment] 2018-09-11 05:48
I will be updating ElectrumX to use paginated requests for history.  It'll probably be in the next protocol bump.  It would be handy if someone did the client side work for Electron Cash

**Comment by cculianu** [comment] 2018-09-11 09:57
I would like to take a stab at it, time permitting.  Do let me know when that happens.

I need to understand the network code.  Right now I get what's happening conceptually but getting my hands dirty would be nice.

**Comment by cculianu** [comment] 2018-10-04 10:57
For now you can connect to: blackie.c3-soft.com if you want to use this wallet.  I set my msg size to 4MB on that server.

**Comment by slanted3** [comment] 2018-10-04 21:40
Thank you. I evenually managed to consolidate the outputs using bitcoin
unlimited, but it is good to know that your electron cash server can handle
it for the future. together we will make bitcoin cash sound money for the
world, so thak you.

**Comment by slanted3** [comment] 2018-10-06 10:05
sent a small tip to the server

**Comment by cculianu** [comment] 2018-10-06 10:29
HA! That was you? Thanks man.  I just noticed it.. about 2 hours ago right?  Thanks!! 🗡

**Comment by slanted3** [comment] 2018-10-06 10:33
Ah, you deserved a little bit more

**Comment by cculianu** [comment] 2018-10-06 15:42
@slanted3 hey thanks for the donation.  I went out and bought a UPS and a better SSD drive for the server.  I'll install them later today and/or tonight.  I love you man! Thanks!

**Comment by slanted3** [comment] 2018-10-06 19:41
great

**Comment by cculianu** [comment] 2019-08-15 23:30
This has since been addressed in newer versions of Electron Cash, which can handle large wallets much better. I just synched a watching only wallet on this address and it synchs ok after 10 minutes. Closing this issue...

**Closed by cculianu** 2019-08-15 23:30 UTC
Labels: enhancement
