### ISSUE TITLE
Load transaction from text crashes client

### ISSUE THREAD

**Issue by ghost** [Electron-Cash/Electron-Cash#604] opened 2018-03-17 17:20 UTC
OSX 10.13.1
Electrum Client Version 3.1.2 with `--testnet` flag

Reproduce

1. Tools > Load Transaction From Text
2. Paste below

```
010000000166909a9b5fee761294240e393cf8653823ec7291970870523941e3ac29a08c0f00000000b400473044022074ab24f1c5281c5469cf710a081a473ed7c4f16e0015ff3256b5c047f44eb843022016935b56936cb5989b7750c30aba2d3664baba041a061aafb9fb2037215f7778414c695221024a5f606cdd0e51e2c46084600d0727ae6cd6a14065594e367636698908eb4d0c21025dc3ea5714154895661abbdd41db799ec9acda94a58ad302b7bf5004adf776112103e341b1d50d3bef7d4975f4c3dba3d1d3c151c103197453eb8a12d18b10e81ba753aeffffffff0240a5ae02000000001976a9149666de90f18da87dcb3d61e7f30dda43ecbdd40d88aca0c44a00000000001976a91462191ee66cbf09540e83880761b156c3be8a0c8988ac00000000
```

3. Crashes with error

```
Traceback (most recent call last):
  File "/Applications/Electron-Cash.app/Contents/Resources/lib/python36.zip/electroncash_gui/qt/main_window.py", line 2203, in do_process_from_text
    self.show_transaction(tx)
  File "/Applications/Electron-Cash.app/Contents/Resources/lib/python36.zip/electroncash_gui/qt/main_window.py", line 766, in show_transaction
    show_transaction(tx, self, tx_desc)
  File "/Applications/Electron-Cash.app/Contents/Resources/lib/python36.zip/electroncash_gui/qt/transaction_dialog.py", line 46, in show_transaction
    d = TxDialog(tx, parent, desc, prompt_if_unsaved)
  File "/Applications/Electron-Cash.app/Contents/Resources/lib/python36.zip/electroncash_gui/qt/transaction_dialog.py", line 129, in __init__
    self.update()
  File "/Applications/Electron-Cash.app/Contents/Resources/lib/python36.zip/electroncash_gui/qt/transaction_dialog.py", line 188, in update
    (self.wallet.can_sign(self.tx) or bool(self.main_window.tx_external_keypairs))
  File "/Applications/Electron-Cash.app/Contents/Resources/lib/python36.zip/electroncash/wallet.py", line 1098, in can_sign
    if k.can_sign(tx):
  File "/Applications/Electron-Cash.app/Contents/Resources/lib/python36.zip/electroncash/keystore.py", line 74, in can_sign
    return bool(self.get_tx_derivations(tx))
  File "/Applications/Electron-Cash.app/Contents/Resources/lib/python36.zip/electroncash/keystore.py", line 62, in get_tx_derivations
    if x_signatures[k] is not None:
IndexError: list index out of range
[1]    86463 abort      ./Electron-Cash --testnet
```

**Comment by coinflippa** [comment] 2018-10-01 12:04
Also getting this on testnet for a multisig 2/3 transaction signed by 1 party.

```
Traceback (most recent call last):
  File "Electron_Cash-3.2-py3.6.egg/electroncash_gui/qt/main_window.py", line 2219, in do_process_from_text
  File "Electron_Cash-3.2-py3.6.egg/electroncash_gui/qt/main_window.py", line 775, in show_transaction
  File "Electron_Cash-3.2-py3.6.egg/electroncash_gui/qt/transaction_dialog.py", line 46, in show_transaction
  File "Electron_Cash-3.2-py3.6.egg/electroncash_gui/qt/transaction_dialog.py", line 129, in __init__
  File "Electron_Cash-3.2-py3.6.egg/electroncash_gui/qt/transaction_dialog.py", line 188, in update
  File "Electron_Cash-3.2-py3.6.egg/electroncash/wallet.py", line 1163, in can_sign
  File "Electron_Cash-3.2-py3.6.egg/electroncash/keystore.py", line 78, in can_sign
  File "Electron_Cash-3.2-py3.6.egg/electroncash/keystore.py", line 66, in get_tx_derivations
IndexError: list index out of range
```

**Comment by dagurval** [comment] 2019-01-09 23:14
Looks like a transaction parsing issue:
```
> /home/dagurval/Electron-Cash/lib/keystore.py(67)get_tx_derivations()
-> num_sig = txin.get('num_sig')
(Pdb) p txin
{
'prevout_hash': '0f8ca029ace34139527008979172ec233865f83c390e24941276ee5f9b9a9066', 
'prevout_n': 0, 
'sequence': 4294967295, 
'address': <Address prvwyx2wnstqm4fham6wcn0yxvsy7hq7j5n0xyaa48>, 
'x_pubkeys': ['024a5f606cdd0e51e2c46084600d0727ae6cd6a14065594e367636698908eb4d0c', '025dc3ea5714154895661abbdd41db799ec9acda94a58ad302b7bf5004adf77611', '03e341b1d50d3bef7d4975f4c3dba3d1d3c151c103197453eb8a12d18b10e81ba7'], 
'pubkeys': ['024a5f606cdd0e51e2c46084600d0727ae6cd6a14065594e367636698908eb4d0c', '025dc3ea5714154895661abbdd41db799ec9acda94a58ad302b7bf5004adf77611', '03e341b1d50d3bef7d4975f4c3dba3d1d3c151c103197453eb8a12d18b10e81ba7'], 
'signatures': ['3044022074ab24f1c5281c5469cf710a081a473ed7c4f16e0015ff3256b5c047f44eb843022016935b56936cb5989b7750c30aba2d3664baba041a061aafb9fb2037215f777841'], 
'type': 'p2sh', 
'num_sig': 2, 
'scriptSig': '00473044022074ab24f1c5281c5469cf710a081a473ed7c4f16e0015ff3256b5c047f44eb843022016935b56936cb5989b7750c30aba2d3664baba041a061aafb9fb2037215f7778414c695221024a5f606cdd0e51e2c46084600d0727ae6cd6a14065594e367636698908eb4d0c21025dc3ea5714154895661abbdd41db799ec9acda94a58ad302b7bf5004adf776112103e341b1d50d3bef7d4975f4c3dba3d1d3c151c103197453eb8a12d18b10e81ba753ae', 
'redeemScript': b"R!\x02J_`l\xdd\x0eQ\xe2\xc4`\x84`\r\x07'\xael\xd6\xa1@eYN6v6i\x89\x08\xebM\x0c!\x02]\xc3\xeaW\x14\x15H\x95f\x1a\xbb\xddA\xdby\x9e\xc9\xac\xda\x94\xa5\x8a\xd3\x02\xb7\xbfP\x04\xad\xf7v\x11!\x03\xe3A\xb1\xd5\r;\xef}Iu\xf4\xc3\xdb\xa3\xd1\xd3\xc1Q\xc1\x03\x19tS\xeb\x8a\x12\xd1\x8b\x10\xe8\x1b\xa7S\xae", 'value': 11520000002
}
```

The code in `get_tx_derivations` expects there to be equal amount of elements in `txin.signatures` as there are `txin.x_pubkeys`. The missing signatures should be `None` elements.

It also looks like outputs aren't parsed. So source of the issue is maybe in `lib/transaction.py`.

Upstream `Electrum` also crashes on this transaction.

**Comment by cculianu** [comment] 2019-08-15 22:44
This has been fixed by a commit a couple of months ago (I forget which one -- the one that detects extra junk at the end).

**Closed by cculianu** 2019-08-15 22:44 UTC
Labels: bug
