### ISSUE TITLE
Android app does not seem to honor custom server config

### ISSUE THREAD

**Issue by samr7** [Electron-Cash/Electron-Cash#1636] opened 2019-09-30 17:32 UTC
Installed Electron Cash android app version 4.0.11-0.4001100.
Open the Settings pane, un-check "Select server automatically," enter a custom address on the Server line.
Open the Network pane
Status: Connected to 10 nodes.
Server: bchx.disdev.org:50002  (not the server I entered)

Same behavior after creating a wallet.

If I'm not misreading or misinterpreting what the app is doing, it seems like I asked it to use a specific server that I control, and works fine with the desktop version of Electron Cash, yet it uses another randomly selected server to which it effectively discloses all of my addresses.

**Comment by mhsmith** [comment] 2019-10-06 11:55
I've just tried this with several addresses from https://github.com/Electron-Cash/Electron-Cash/blob/master/lib/servers.json and it works fine for me. If the server is online, the app connects to it immediately. If the server is offline, the app indicates "offline" and doesn't connect to any other server, though it remains connected to the other nodes.

In the Network screen, what happens if you touch the currently active server and choose Disconnect?

If you're concerned about disclosing addresses, you can experiment with no wallet loaded.

**Comment by cculianu** [comment] 2019-10-06 12:38
Yeah I'd be surprised if this was a bug since it's enforce by the `lib/` .. rather than by the UI. So unless the Android UI forgot to tell the `network.py` subsystem.. it should "just work".

Since you confirmed it does -- I am going to close this.  The user can provide more information if he feels it's still an issue and it can be re-opened at that point.

**Comment by samr7** [comment] 2019-10-07 21:33
I think I see what's going on now.
When I go to the console and:
`setconfig('whitelist_servers_only',False)`
It connects to my specified custom server.
Perhaps if a custom server is specified, this setting should be inferred?
Or at the very least, there should be a GUI toggle for it?
Thanks.

**Comment by mhsmith** [comment] 2019-10-08 16:02
Thanks for the investigation. A similar issue has already occurred elsewhere (#1222). 

@cculianu: Isn't the point of the whitelist to prevent connecting to servers which we've learned about indirectly from other servers? It shouldn't be used to exclude a server which the user has explicitly chosen.

**Comment by cculianu** [comment] 2019-10-08 18:34
Well.. the point was it was designed along a GUI option (which doesn't even exist on iOS and this bug occurs on iOS now that I think about it) to enable/disable white-list only ("Preferred server" is the UI parlance for it).  With it selected (the default), you can't even switch to a non-whitelisted server in the Qt UI.

I admit I should have told you about this on Android and that it does impact your android app. iOS suffers from this now too!

Manually specifying the server by picking it/entering it could still be a DoS vector, or so it was thought.... to really be aggressive there.

When this feature was added we were on horrible attack. 95% of the servers in the list were bad actors.  So we wanted to be sure users can't make a mistake.  Money was on the line.

Just the existence of this feature causes the attackers to give up and focus on BTC & Electrum.  There are 0 phishers now.

Maybe the Android app should just disable this option or disable it if user inputs a server manually?

The lib itself does no such thing and instead relies on the GUI ...

**Closed** 2019-10-09 10:51 UTC
Labels: android
