### ISSUE TITLE
RuntimeError: wrapped C/C++ object of type StatusBarButton has been deleted

### ISSUE THREAD

**Issue by ProfessorVenkman** [Electron-Cash/Electron-Cash#1531] opened 2019-07-21 08:46 UTC
Crash Report
============

This crash report was reported through the automatic crash reporting system 🤖

Traceback
--------------

```Python traceback
  File "/home/ago/src/Electron-Cash/gui/qt/main_window.py", line 3661, in update_cashaddr_icon
    self.addr_converter_button.setIcon(self.cashaddr_icon())

RuntimeError: wrapped C/C++ object of type StatusBarButton has been deleted
```

Reporter
------------

This issue was reported by 1 user(s):

| Electron Cash Version  | Python Version | Operating System  | Wallet Type  | Locale |
|---|---|---|---|---|
| 4.0.8  | 3.7.3 (default, Jun 24 2019, 04:54:02)  [GCC 9.1.0] | Linux-5.2.1-arch1-1-ARCH-x86_64-with-arch | standard | de_DE | 

Additional Information
------------------------

> ichundes here, got this when clicking the cashaddr toggle button

---

**Comment by cculianu** [comment] 2019-07-21 11:28
I saw. Too bad the crash reporter doesn't include information like Qt version. I can't reproduce this here. I even installed Python 3.7.3.  Can you tell me how it happened? What steps? Or does it just happen right way? Do you need to first open a window then close it?

This points to a bug in PyQt5 actually. That signal/slot is to a deleted object -- it's being called on a deleted object.  The connection was made using `self.method` which means it should auto-disconnect on object deletion (PyQt looks at the bound method and extracts the instance, and if it's a QObject, applies Qt rules to auto-disconnect on object death).

I wrote some workaround code to deal with the situation in this branch:

https://github.com/Electron-Cash/Electron-Cash/tree/fix_disconnect_signals

1. See if you can reliably reproduce this.
2. If so, then would you mind trying that branch `fix_disconnect_signals` as well and tell me  if that makes the situation better?
3. Also see if it happens in AppImage (which is Python 3.6.8). If not, it may be Python 3.7.3 + PyQt5.12-specific.

*Sigh*.

Let me know! This has me nervous!  I rely on the auto-disconnect of slots on object deletion behavior of PyQt5 quite a lot.  I assumed it worked perfectly.  Apparently not!

**Closed** 2019-07-21 14:49 UTC
Labels: High Priority, Qt, bug, observation required

**Comment by cculianu** [comment] 2019-07-21 15:32
Ok, I managed to reproduce it and I can confirm latest commit fixes it.  The issue is as follows:

0. Go to commit tag 4.0.8-dev5.

1. Open 2 wallet windows. Make the second window shuffle and have coins in the shuffle queue. This creates lots of python references that will keep the window alive for a time after close.

2. Close the second window.. observe the debug console that the window didn't get "Finalized"

3. Toggle the cashaddr button. The Qt signal is delivered to an object what was deleted on the C++ side but which the PyQt side thinks is still alive.  

This is definitely a bug in PyQt.  It is dropping the ball on realizing when Qt objects are deleted and assumes they're still alive.  

The workaround is to just explicitly disconnect signals to the object in window close code.

This didn't happen before because previously the cashaddr toggle signal was a per-window signal (even though it was a global concept).
