### ISSUE TITLE
java.lang.RuntimeException: java.lang.reflect.InvocationTargetException

### ISSUE THREAD

**Issue by ProfessorVenkman** [Electron-Cash/Electron-Cash#2286] opened 2021-05-31 04:46 UTC
Crash Report
============

This crash report was reported through the automatic crash reporting system 🤖

Traceback
--------------

```Python traceback
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:612)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1130)
Caused by: java.lang.reflect.InvocationTargetException
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:602)
	... 1 more
Caused by: org.electroncash.electroncash3.ToastException: Not connected
	at org.electroncash.electroncash3.ColdLoadDialog.onOK(ColdLoad.kt:76)
	at org.electroncash.electroncash3.ColdLoadDialog$onShowDialog$2.onClick(ColdLoad.kt:46)
	at android.view.View.performClick(View.java:8160)
	at android.widget.TextView.performClick(TextView.java:16221)
	at android.view.View.performClickInternal(View.java:8137)
	at android.view.View.access$3700(View.java:888)
	at android.view.View$PerformClick.run(View.java:30236)
	at android.os.Handler.handleCallback(Handler.java:938)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loop(Looper.java:246)
	at android.app.ActivityThread.main(ActivityThread.java:8506)
	... 3 more
java.lang.RuntimeException: java.lang.reflect.InvocationTargetException
```

Reporter
------------

This issue was reported by 1 user(s):

| Electron Cash Version  | Python Version | Operating System  | Wallet Type  | Locale |
|---|---|---|---|---|
| 4.2.0-0  | 3.6.5 (default, Sep 11 2019, 15:39:45)  [GCC 4.9] | Android 11 on samsung SM-G973F (beyond1) | unknown | en_ZA | 

Additional Information
------------------------

The reporting user(s) did not provide additional information.

**Comment by mhsmith** [comment] 2021-07-06 16:49
Duplicate of #2032.

**Closed by mhsmith** 2021-07-06 16:49 UTC

**Comment by ProfessorVenkman** [comment] 2024-12-21 16:25
Good afternoon @mhsmith,

I just received another crash report related to this issue. The crash occured on Electron Cash 4.4.1-3.
I'm not sure which versions of Electron Cash include the fix but this is the first report from anything
newer than 4.2.0-0 since you closed the issue.

Could you please check if this issue really is resolved? Here is the traceback that I just collected:

```Python traceback
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:612)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1130)
Caused by: java.lang.reflect.InvocationTargetException
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:602)
	... 1 more
Caused by: org.electroncash.electroncash3.ToastException: This wallet is watching-only.
	at org.electroncash.electroncash3.SendDialog.<init>(Send.kt:109)
	at org.electroncash.electroncash3.TokenTransactionsFragment.onViewCreated$lambda$6(TokenTransactions.kt:47)
	at org.electroncash.electroncash3.TokenTransactionsFragment.$r8$lambda$LTUupZDg5PqsZ5StldVi_K5lI9c(Unknown Source:0)
	at org.electroncash.electroncash3.TokenTransactionsFragment$$ExternalSyntheticLambda1.onClick(Unknown Source:2)
	at android.view.View.performClick(View.java:8160)
	at android.view.View.performClickInternal(View.java:8137)
	at android.view.View.access$3700(View.java:888)
	at android.view.View$PerformClick.run(View.java:30236)
	at android.os.Handler.handleCallback(Handler.java:938)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loop(Looper.java:246)
	at android.app.ActivityThread.main(ActivityThread.java:8653)
	... 3 more
java.lang.RuntimeException: java.lang.reflect.InvocationTargetException
```


~ _With robotic wishes_
