### ISSUE TITLE
com.chaquo.python.PyException: AttributeError: 'NoneType' object has no attribute 'connect_chunk'

### ISSUE THREAD

**Issue by ProfessorVenkman** [Electron-Cash/Electron-Cash#1140] opened 2019-01-31 05:14 UTC
Crash Report
============

This crash report was reported through the automatic crash reporting system 🤖

Traceback
--------------

```Python traceback
	at <python>.on_block_headers(/android_asset/chaquopy/app.zip/electroncash/network.py:986)
	at <python>.process_response(/android_asset/chaquopy/app.zip/electroncash/network.py:669)
	at <python>.process_responses(/android_asset/chaquopy/app.zip/electroncash/network.py:729)
	at <python>.wait_on_sockets(/android_asset/chaquopy/app.zip/electroncash/network.py:1261)
	at <python>.run(/android_asset/chaquopy/app.zip/electroncash/network.py:1287)
	at <python>.run(/android_asset/chaquopy/app.zip/electroncash_gui/android/daemon.py:34)
	at <python>.reraise(/android_asset/chaquopy/requirements-common.zip/six.py:693)
	at <python>.run(/android_asset/chaquopy/app.zip/electroncash_gui/android/daemon.py:25)
	at <python>.chaquopy_java.call(chaquopy_java.pyx:282)
	at <python>.chaquopy_java.Java_com_chaquo_python_PyObject_callAttrThrows(chaquopy_java.pyx:254)
	at com.chaquo.python.PyObject.callAttrThrows(Native Method)
	at com.chaquo.python.PyInvocationHandler.invoke(PyInvocationHandler.java:31)
	at java.lang.reflect.Proxy.invoke(Proxy.java:813)
	at $Proxy4.run(Unknown Source)
	at android.os.Handler.handleCallback(Handler.java:751)
	at android.os.Handler.dispatchMessage(Handler.java:95)
	at android.os.Looper.loop(Looper.java:154)
	at android.app.ActivityThread.main(ActivityThread.java:6103)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:865)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:755)
com.chaquo.python.PyException: AttributeError: 'NoneType' object has no attribute 'connect_chunk'
```

Reporter
------------

This issue was reported by 1 user(s):

| Electron Cash Version  | Python Version | Operating System  | Wallet Type  | Locale |
|---|---|---|---|---|
| 3.3.5-1  | 3.6.5 (default, Dec  7 2018, 13:59:54)  [GCC 4.9] | Android 7.0 on ZTE Amazing A30 (P809F20) | unknown | zh_CN | 

Additional Information
------------------------

The reporting user(s) did not provide additional information.

**Comment by cculianu** [comment] 2019-02-01 19:00
Looks to be a dupe of #1079.

**Closed by cculianu** 2019-02-01 19:00 UTC
Labels: duplicate
