### ISSUE TITLE
java.lang.RuntimeException: Unable to create application org.electroncash.electroncash3.App: com.chaquo.python.PyException: error: Error -3 while decompressing data: invalid distance too far back

### ISSUE THREAD

**Issue by ProfessorVenkman** [Electron-Cash/Electron-Cash#2371] opened 2021-12-06 11:46 UTC
Crash Report
============

This crash report was reported through the automatic crash reporting system 🤖

Traceback
--------------

```Python traceback
	at android.app.ActivityThread.handleBindApplication(ActivityThread.java:7403)
	at android.app.ActivityThread.access$2400(ActivityThread.java:251)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2280)
	at android.os.Handler.dispatchMessage(Handler.java:110)
	at android.os.Looper.loop(Looper.java:219)
	at android.app.ActivityThread.main(ActivityThread.java:8387)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:513)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1055)
Caused by: com.chaquo.python.PyException: error: Error -3 while decompressing data: invalid distance too far back
	at <python>.importlib._bootstrap_external.spec_from_file_location(<frozen importlib._bootstrap_external>:544)
	at <python>.importlib._bootstrap.spec_from_loader(<frozen importlib._bootstrap>:441)
	at <python>.importlib._bootstrap_external._legacy_get_spec(<frozen importlib._bootstrap_external>:1112)
	at <python>.importlib._bootstrap_external._get_spec(<frozen importlib._bootstrap_external>:1131)
	at <python>.importlib._bootstrap_external.find_spec(<frozen importlib._bootstrap_external>:1157)
	at <python>.importlib._bootstrap._find_spec(<frozen importlib._bootstrap>:894)
	at <python>.importlib._bootstrap._find_and_load_unlocked(<frozen importlib._bootstrap>:951)
	at <python>.importlib._bootstrap._find_and_load(<frozen importlib._bootstrap>:971)
	at <python>.java.chaquopy.import_override(import.pxi:20)
	at <python>.java.chaquopy.import_override(import.pxi:26)
	at <python>.electroncash.util.<module>(util.py:673)
	at <python>.java.chaquopy.import_override(import.pxi:26)
	at <python>.electroncash.<module>(__init__.py:2)
	at <python>.importlib._bootstrap._call_with_frames_removed(<frozen importlib._bootstrap>:219)
	at <python>.importlib._bootstrap_external.exec_module(<frozen importlib._bootstrap_external>:678)
	at <python>.java.android.importer.exec_module(importer.py:346)
	at <python>.importlib._bootstrap._load_unlocked(<frozen importlib._bootstrap>:665)
	at <python>.importlib._bootstrap._find_and_load_unlocked(<frozen importlib._bootstrap>:955)
	at <python>.importlib._bootstrap._find_and_load(<frozen importlib._bootstrap>:971)
	at <python>.importlib._bootstrap._gcd_import(<frozen importlib._bootstrap>:994)
	at <python>.importlib._bootstrap._call_with_frames_removed(<frozen importlib._bootstrap>:219)
	at <python>.importlib._bootstrap._find_and_load_unlocked(<frozen importlib._bootstrap>:941)
	at <python>.importlib._bootstrap._find_and_load(<frozen importlib._bootstrap>:971)
	at <python>.importlib._bootstrap._gcd_import(<frozen importlib._bootstrap>:994)
	at <python>.importlib.import_module(__init__.py:126)
	at <python>.chaquopy_java.Java_com_chaquo_python_Python_getModule(chaquopy_java.pyx:154)
	at com.chaquo.python.Python.getModule(Native Method)
	at org.electroncash.electroncash3.AppKt.libMod(App.kt:26)
	at org.electroncash.electroncash3.NetworkKt$libNetwork$2.invoke(Network.kt:27)
	at org.electroncash.electroncash3.NetworkKt$libNetwork$2.invoke(Unknown Source:0)
	at kotlin.SynchronizedLazyImpl.getValue(LazyJVM.kt:74)
	at org.electroncash.electroncash3.NetworkKt.getLibNetwork(Unknown Source:7)
	at org.electroncash.electroncash3.SettingsKt.setDefaultValues(Settings.kt:38)
	at org.electroncash.electroncash3.SettingsKt.initSettings(Settings.kt:23)
	at org.electroncash.electroncash3.App.onCreate(App.kt:62)
	at android.app.Instrumentation.callApplicationOnCreate(Instrumentation.java:1202)
	at android.app.ActivityThread.handleBindApplication(ActivityThread.java:7387)
	... 8 more
java.lang.RuntimeException: Unable to create application org.electroncash.electroncash3.App: com.chaquo.python.PyException: error: Error -3 while decompressing data: invalid distance too far back
```

Reporter
------------

This issue was reported by 1 user(s):

| Electron Cash Version  | Python Version | Operating System  | Wallet Type  | Locale |
|---|---|---|---|---|
| 4.0.11-0  | 3.6.5 (default, Sep 11 2019, 15:39:45)  [GCC 4.9] | Android 10 on HUAWEI LYA-L29 (HWLYA) | unknown | en_CA | 

Additional Information
------------------------

The reporting user(s) did not provide additional information.

**Comment by mhsmith** [comment] 2021-12-11 11:55
Duplicate of #2350.

**Closed by mhsmith** 2021-12-11 11:55 UTC
