### ISSUE TITLE
java.lang.IllegalStateException: Can not perform this action after onSaveInstanceState

### ISSUE THREAD

**Issue by ProfessorVenkman** [Electron-Cash/Electron-Cash#2023] opened 2020-10-21 02:15 UTC
Crash Report
============

This crash report was reported through the automatic crash reporting system 🤖

Traceback
--------------

```Python traceback
	at androidx.fragment.app.FragmentManagerImpl.checkStateLoss(FragmentManagerImpl.java:1536)
	at androidx.fragment.app.FragmentManagerImpl.ensureExecReady(FragmentManagerImpl.java:1672)
	at androidx.fragment.app.FragmentManagerImpl.execSingleAction(FragmentManagerImpl.java:1692)
	at androidx.fragment.app.BackStackRecord.commitNow(BackStackRecord.java:293)
	at org.electroncash.electroncash3.MainActivity.showFragment(Main.kt:326)
	at org.electroncash.electroncash3.MainActivity$onCreate$3.onNavigationItemSelected(Main.kt:86)
	at com.google.android.material.bottomnavigation.BottomNavigationView$1.onMenuItemSelected(BottomNavigationView.java:204)
	at androidx.appcompat.view.menu.MenuBuilder.dispatchMenuItemSelected(MenuBuilder.java:840)
	at androidx.appcompat.view.menu.MenuItemImpl.invoke(MenuItemImpl.java:158)
	at androidx.appcompat.view.menu.MenuBuilder.performItemAction(MenuBuilder.java:991)
	at com.google.android.material.bottomnavigation.BottomNavigationMenuView$1.onClick(BottomNavigationMenuView.java:115)
	at android.view.View.performClick(View.java:4853)
	at android.view.View$PerformClick.run(View.java:20272)
	at android.os.Handler.handleCallback(Handler.java:815)
	at android.os.Handler.dispatchMessage(Handler.java:104)
	at android.os.Looper.loop(Looper.java:194)
	at android.app.ActivityThread.main(ActivityThread.java:5631)
	at java.lang.reflect.Method.invoke(Native Method)
	at java.lang.reflect.Method.invoke(Method.java:372)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:959)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:754)
java.lang.IllegalStateException: Can not perform this action after onSaveInstanceState
```

Reporter
------------

This issue was reported by 3 user(s):

| Electron Cash Version  | Python Version | Operating System  | Wallet Type  | Locale |
|---|---|---|---|---|
| 4.0.14-0  | 3.6.5 (default, Sep 11 2019, 15:30:12)  [GCC 4.9] | Android 10.0 on Android M90'20' (M90'20') | unknown | fa_IR | 
| 4.2.3-3  | 3.8.6 (default, Jan 17 2021, 16:48:53)  [Clang 7.0.2 (https://android.googlesource.com/toolchain/clang 003100370607242d | Android 5.1.1 on OPPO A37fw (A37f) | unknown | ms_MY | 
| 4.2.4-5  | 3.8.6 (default, Jan 17 2021, 16:48:53)  [Clang 7.0.2 (https://android.googlesource.com/toolchain/clang 003100370607242d | Android 5.1.1 on OPPO A37f (A37f) | unknown | in_ID | 

Additional Information
------------------------

> may i know how to check our wallet address?

---

**Comment by mhsmith** [comment] 2020-10-30 19:47
Duplicate of #1091, which should have been fixed, and hasn't been reported by any other device for over a year. This is a really weird device name, so my guess is that it's some off-brand device which has somehow broken the implementation of cancelPendingInputEvents.

**Comment by ProfessorVenkman** [comment] 2021-05-05 06:07
Good morning @mhsmith,

I just received another crash report related to this issue. The crash occured on Electron Cash 4.2.3-3.
I'm not sure which versions of Electron Cash include the fix but this is the first report from anything
newer than 4.0.14-0 since you closed the issue.

Could you please check if this issue really is resolved? Here is the traceback that I just collected:

```Python traceback
	at androidx.fragment.app.FragmentManagerImpl.checkStateLoss(FragmentManagerImpl.java:1536)
	at androidx.fragment.app.FragmentManagerImpl.ensureExecReady(FragmentManagerImpl.java:1672)
	at androidx.fragment.app.FragmentManagerImpl.execSingleAction(FragmentManagerImpl.java:1692)
	at androidx.fragment.app.BackStackRecord.commitNow(BackStackRecord.java:293)
	at androidx.fragment.app.DialogFragment.showNow(DialogFragment.java:192)
	at org.electroncash.electroncash3.UtilKt.showDialog(Util.kt:112)
	at org.electroncash.electroncash3.UtilKt.showDialog(Util.kt:102)
	at org.electroncash.electroncash3.ListAdapter$onBindViewHolder$1.onClick(ListFragment.kt:87)
	at android.view.View.performClick(View.java:4781)
	at android.view.View$PerformClick.run(View.java:19907)
	at android.os.Handler.handleCallback(Handler.java:739)
	at android.os.Handler.dispatchMessage(Handler.java:95)
	at android.os.Looper.loop(Looper.java:160)
	at android.app.ActivityThread.main(ActivityThread.java:5541)
	at java.lang.reflect.Method.invoke(Native Method)
	at java.lang.reflect.Method.invoke(Method.java:372)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:964)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:759)
java.lang.IllegalStateException: Can not perform this action after onSaveInstanceState
```


~ _With robotic wishes_

**Comment by ProfessorVenkman** [comment] 2021-07-28 12:10
Good afternoon @mhsmith,

I just received another crash report related to this issue. The crash occured on Electron Cash 4.2.4-5.
I'm not sure which versions of Electron Cash include the fix but this is the first report from anything
newer than 4.2.3-3 since you closed the issue.

Could you please check if this issue really is resolved? Here is the traceback that I just collected:

```Python traceback
	at androidx.fragment.app.FragmentManagerImpl.checkStateLoss(FragmentManagerImpl.java:1536)
	at androidx.fragment.app.FragmentManagerImpl.ensureExecReady(FragmentManagerImpl.java:1672)
	at androidx.fragment.app.FragmentManagerImpl.execSingleAction(FragmentManagerImpl.java:1692)
	at androidx.fragment.app.BackStackRecord.commitNow(BackStackRecord.java:293)
	at androidx.fragment.app.DialogFragment.showNow(DialogFragment.java:192)
	at org.electroncash.electroncash3.UtilKt.showDialog(Util.kt:117)
	at org.electroncash.electroncash3.UtilKt.showDialog$default(Util.kt:110)
	at org.electroncash.electroncash3.MainActivity.onDrawerItemSelected(Main.kt:198)
	at org.electroncash.electroncash3.MainActivity$onCreate$3.onDrawerClosed(Main.kt:102)
	at androidx.drawerlayout.widget.DrawerLayout.dispatchOnDrawerClosed(DrawerLayout.java:859)
	at androidx.drawerlayout.widget.DrawerLayout.updateDrawerState(DrawerLayout.java:829)
	at androidx.drawerlayout.widget.DrawerLayout$ViewDragCallback.onViewDragStateChanged(DrawerLayout.java:2174)
	at androidx.customview.widget.ViewDragHelper.setDragState(ViewDragHelper.java:891)
	at androidx.customview.widget.ViewDragHelper$2.run(ViewDragHelper.java:343)
	at android.os.Handler.handleCallback(Handler.java:739)
	at android.os.Handler.dispatchMessage(Handler.java:95)
	at android.os.Looper.loop(Looper.java:160)
	at android.app.ActivityThread.main(ActivityThread.java:5541)
	at java.lang.reflect.Method.invoke(Native Method)
	at java.lang.reflect.Method.invoke(Method.java:372)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:964)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:759)
java.lang.IllegalStateException: Can not perform this action after onSaveInstanceState
```


~ _With robotic wishes_

**Comment by mhsmith** [comment] 2021-07-31 08:55
Like #2311, this appears to be limited to Android 5.1, so I'm closing it for the reasons discussed there.

**Closed by mhsmith** 2021-07-31 08:55 UTC
Labels: android

**Comment by ProfessorVenkman** [comment] 2022-04-09 15:19
Good afternoon @mhsmith,

I just received another crash report related to this issue. The crash occured on Electron Cash 4.2.5-5.
I'm not sure which versions of Electron Cash include the fix but this is the first report from anything
newer than 4.2.4-5 since you closed the issue.

Could you please check if this issue really is resolved? Here is the traceback that I just collected:

```Python traceback
	at androidx.fragment.app.FragmentManagerImpl.checkStateLoss(FragmentManagerImpl.java:1536)
	at androidx.fragment.app.FragmentManagerImpl.ensureExecReady(FragmentManagerImpl.java:1672)
	at androidx.fragment.app.FragmentManagerImpl.execSingleAction(FragmentManagerImpl.java:1692)
	at androidx.fragment.app.BackStackRecord.commitNow(BackStackRecord.java:293)
	at androidx.fragment.app.DialogFragment.showNow(DialogFragment.java:192)
	at org.electroncash.electroncash3.UtilKt.showDialog(Util.kt:117)
	at org.electroncash.electroncash3.UtilKt.showDialog(Util.kt:107)
	at org.electroncash.electroncash3.TransactionsFragment$onViewCreated$1.onClick(Transactions.kt:29)
	at android.view.View.performClick(View.java:4858)
	at android.view.View$PerformClick.run(View.java:20272)
	at android.os.Handler.handleCallback(Handler.java:815)
	at android.os.Handler.dispatchMessage(Handler.java:104)
	at android.os.Looper.loop(Looper.java:194)
	at android.app.ActivityThread.main(ActivityThread.java:5743)
	at java.lang.reflect.Method.invoke(Native Method)
	at java.lang.reflect.Method.invoke(Method.java:372)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1077)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:843)
java.lang.IllegalStateException: Can not perform this action after onSaveInstanceState
```


~ _With robotic wishes_

**Comment by ProfessorVenkman** [comment] 2023-04-28 14:29
Good afternoon @mhsmith,

I just received another crash report related to this issue. The crash occured on Electron Cash 4.2.14-6.
I'm not sure which versions of Electron Cash include the fix but this is the first report from anything
newer than 4.2.5-5 since you closed the issue.

Could you please check if this issue really is resolved? Here is the traceback that I just collected:

```Python traceback
	at androidx.fragment.app.FragmentManagerImpl.checkStateLoss(FragmentManagerImpl.java:1536)
	at androidx.fragment.app.FragmentManagerImpl.ensureExecReady(FragmentManagerImpl.java:1672)
	at androidx.fragment.app.FragmentManagerImpl.execSingleAction(FragmentManagerImpl.java:1692)
	at androidx.fragment.app.BackStackRecord.commitNow(BackStackRecord.java:293)
	at androidx.fragment.app.DialogFragment.showNow(DialogFragment.java:192)
	at org.electroncash.electroncash3.UtilKt.showDialog(Util.kt:117)
	at org.electroncash.electroncash3.UtilKt.showDialog$default(Util.kt:110)
	at org.electroncash.electroncash3.MainActivity.onBackPressed(Main.kt:161)
	at android.app.Activity.onKeyUp(Activity.java:2576)
	at android.view.KeyEvent.dispatch(KeyEvent.java:3171)
	at androidx.core.view.KeyEventDispatcher.activitySuperDispatchKeyEventPre28(KeyEventDispatcher.java:137)
	at androidx.core.view.KeyEventDispatcher.dispatchKeyEvent(KeyEventDispatcher.java:87)
	at androidx.core.app.ComponentActivity.dispatchKeyEvent(ComponentActivity.java:133)
	at androidx.appcompat.app.AppCompatActivity.dispatchKeyEvent(AppCompatActivity.java:558)
	at androidx.appcompat.view.WindowCallbackWrapper.dispatchKeyEvent(WindowCallbackWrapper.java:59)
	at androidx.appcompat.app.AppCompatDelegateImpl$AppCompatWindowCallback.dispatchKeyEvent(AppCompatDelegateImpl.java:2814)
	at androidx.appcompat.view.WindowCallbackWrapper.dispatchKeyEvent(WindowCallbackWrapper.java:59)
	at com.android.internal.policy.impl.PhoneWindow$DecorView.dispatchKeyEvent(PhoneWindow.java:2438)
	at android.view.ViewRootImpl$ViewPostImeInputStage.processKeyEvent(ViewRootImpl.java:4582)
	at android.view.ViewRootImpl$ViewPostImeInputStage.onProcess(ViewRootImpl.java:4537)
	at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:4068)
	at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:4121)
	at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:4087)
	at android.view.ViewRootImpl$AsyncInputStage.forward(ViewRootImpl.java:4201)
	at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:4095)
	at android.view.ViewRootImpl$AsyncInputStage.apply(ViewRootImpl.java:4258)
	at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:4068)
	at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:4121)
	at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:4087)
	at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:4095)
	at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:4068)
	at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:4121)
	at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:4087)
	at android.view.ViewRootImpl$AsyncInputStage.forward(ViewRootImpl.java:4234)
	at android.view.ViewRootImpl$ImeInputStage.onFinishedInputEvent(ViewRootImpl.java:4421)
	at android.view.inputmethod.InputMethodManager$PendingEvent.run(InputMethodManager.java:2480)
	at android.view.inputmethod.InputMethodManager.invokeFinishedInputEventCallback(InputMethodManager.java:2074)
	at android.view.inputmethod.InputMethodManager.finishedInputEvent(InputMethodManager.java:2065)
	at android.view.inputmethod.InputMethodManager$ImeInputEventSender.onInputEventFinished(InputMethodManager.java:2457)
	at android.view.InputEventSender.dispatchInputEventFinished(InputEventSender.java:141)
	at android.os.MessageQueue.nativePollOnce(Native Method)
	at android.os.MessageQueue.next(MessageQueue.java:143)
	at android.os.Looper.loop(Looper.java:130)
	at android.app.ActivityThread.main(ActivityThread.java:5951)
	at java.lang.reflect.Method.invoke(Native Method)
	at java.lang.reflect.Method.invoke(Method.java:372)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1400)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1195)
java.lang.IllegalStateException: Can not perform this action after onSaveInstanceState
```


~ _With robotic wishes_
