### ISSUE TITLE
Wrong transaction with Ledger Nano S when amount >= 0.05

### ISSUE THREAD

**Issue by btielen** [Electron-Cash/Electron-Cash#602] opened 2018-03-16 17:29 UTC
Today I encountered this strange and serious issue. Everything works fine for amounts smaller than 0.05 BCH. But when you try to make a transaction of 0.05 BCH and bigger, the address and the amount to confirm on the Ledger Nano S are wrong! Of course I didn't approved the transaction, because I don't want to lose my funds.

I checked this issue on two different PC's (windows 10 & windows 8) and on both machines this issue showed up. 

- ElectronCash-3.1.5.exe
- Windows 10 & 8
- Confirmed the hash [7170a833ace395de5b301b195223965cf09226625dbd3a0651ba378c8321d8c0](https://github.com/fyookball/keys-n-hashes/blob/master/sigs-and-sums/3.1.5/win-linux/SHA256.ElectronCash-3.1.5.exe.txt)
- Ledger Nano S firmware 1.4.1

Can anyone reproduce?

**Comment by marceloneil** [comment] 2018-03-16 17:48
I'll check this out later today, I agree that is very serious.

**Comment by marceloneil** [comment] 2018-03-17 01:38
I'm unable to reproduce this. When you click "preview", and then "sign" do the inputs/outputs not match what is shown on your ledger. Additionally, cashaddr is not currently supported on the ledger, so if you're comparing addresses you need to use legacy addresses.

**Comment by btielen** [comment] 2018-03-17 08:47
After clicking on the "preview" button I could further point down the problem. Instead of the showing the destination address on the Ledger Nano S, is shows one of my change addresses, which causes confusion. 

So if I wanna send an amount x to B.  Electron generates a transaction with two output addresses A and B. I expect to confirm a transaction of x to B on the Ledger Nano S. But instead it lets me sometimes confirm a transaction to A. Depending on x, the preview transaction output order is A, B or B, A.

**Comment by btielen** [comment] 2018-03-17 10:14
I guess the problem is in [/plugins/ledger/ledger.py on line 316](https://github.com/fyookball/electrum/blob/master/plugins/ledger/ledger.py#L316)
` if (info is not None) and (len(tx.outputs()) != 1):`

and or in [/lib/wallet.py on line 1202](https://github.com/fyookball/electrum/blob/master/lib/wallet.py#L1202)
`info[addr] = index, sorted_xpubs, self.m if isinstance(self, Multisig_Wallet) else None`

**Comment by marceloneil** [comment] 2018-03-17 15:06
So is the problem the order of the transaction preview?

**Comment by btielen** [comment] 2018-03-18 19:41
I think the problem is that the change address is not recognized correctly. I am not able to test it, but I suppose the problem should be here:

` if not p2shTransaction:
            for _type, address, amount in tx.outputs():
                assert _type == TYPE_ADDRESS
                info = tx.output_info.get(address)
                if (info is not None) and (len(tx.outputs()) != 1):
                    index, xpubs, m = info
                    changePath = self.get_derivation()[2:] + "/%d/%d"%index
                    changeAmount = amount
                else:
                    output = address
                    outputAmount = amount `

[https://github.com/fyookball/electrum/blob/master/plugins/ledger/ledger.py#L311](https://github.com/fyookball/electrum/blob/master/plugins/ledger/ledger.py#L311)

**Comment by marceloneil** [comment] 2018-05-02 22:41
Have you tried 3.2?

**Comment by rt121212121** [comment] 2018-06-08 07:50
@btielen Any update?

**Comment by rt121212121** [comment] 2018-06-18 20:50
@btielen Can you let us know if this is fixed or not with the latest version please?

**Comment by btielen** [comment] 2018-07-19 18:24
I found some time to test it again. I have the same problem in version 3.3. 

It let's me confirm "output #1" "change amount" to my change address instead of the actual important output. This bug only shows up in some cases.

**Comment by cculianu** [comment] 2019-04-02 19:38
Is this still an extant issue? Can you try latest github head?

**Comment by cculianu** [comment] 2019-09-08 17:03
Since user hasn't replied in some time -- and in my testing everything works ok on my Ledger Nano X, and @EchteraAgo has had no problems on his Ledger Nano S of this sort, we are closing this.

**Closed by cculianu** 2019-09-08 17:03 UTC
Labels: blocked on user, hardware wallets
