### ISSUE TITLE
java.lang.RuntimeException: Unable to create application org.electroncash.electroncash3.App: java.lang.RuntimeException: java.io.FileNotFoundException: chaquopy/bootstrap-native/x86/java/__init__.py

### ISSUE THREAD

**Issue by ProfessorVenkman** [Electron-Cash/Electron-Cash#2138] opened 2021-01-28 01:40 UTC
Crash Report
============

This crash report was reported through the automatic crash reporting system 🤖

Traceback
--------------

```Python traceback
	at android.app.ActivityThread.handleBindApplication(ActivityThread.java:6135)
	at android.app.ActivityThread.access$1100(ActivityThread.java:201)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1725)
	at android.os.Handler.dispatchMessage(Handler.java:106)
	at android.os.Looper.loop(Looper.java:193)
	at android.app.ActivityThread.main(ActivityThread.java:6971)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:865)
Caused by: java.lang.RuntimeException: java.io.FileNotFoundException: chaquopy/bootstrap-native/x86/java/__init__.py
	at com.chaquo.python.android.AndroidPlatform.getPath(AndroidPlatform.java:111)
	at com.chaquo.python.Python.start(Python.java:53)
	at org.electroncash.electroncash3.AppKt$py$2.invoke(App.kt:18)
	at org.electroncash.electroncash3.AppKt$py$2.invoke(Unknown Source:0)
	at kotlin.SynchronizedLazyImpl.getValue(LazyJVM.kt:74)
	at org.electroncash.electroncash3.AppKt.getPy(Unknown Source:7)
	at org.electroncash.electroncash3.AppKt.libMod(App.kt:21)
	at org.electroncash.electroncash3.NetworkKt$libNetwork$2.invoke(Network.kt:27)
	at org.electroncash.electroncash3.NetworkKt$libNetwork$2.invoke(Unknown Source:0)
	at kotlin.SynchronizedLazyImpl.getValue(LazyJVM.kt:74)
	at org.electroncash.electroncash3.NetworkKt.getLibNetwork(Unknown Source:7)
	at org.electroncash.electroncash3.SettingsKt.setDefaultValues(Settings.kt:63)
	at org.electroncash.electroncash3.SettingsKt.initSettings(Settings.kt:28)
	at org.electroncash.electroncash3.App.onCreate(App.kt:53)
	at android.app.Instrumentation.callApplicationOnCreate(Instrumentation.java:1167)
	at android.app.ActivityThread.handleBindApplication(ActivityThread.java:6130)
	... 8 more
Caused by: java.io.FileNotFoundException: chaquopy/bootstrap-native/x86/java/__init__.py
	at android.content.res.AssetManager.nativeOpenAsset(Native Method)
	at android.content.res.AssetManager.open(AssetManager.java:744)
	at android.content.res.AssetManager.open(AssetManager.java:721)
	at com.chaquo.python.android.AndroidPlatform.extractAsset(AndroidPlatform.java:194)
	at com.chaquo.python.android.AndroidPlatform.extractAssets(AndroidPlatform.java:149)
	at com.chaquo.python.android.AndroidPlatform.getPath(AndroidPlatform.java:108)
	... 23 more
java.lang.RuntimeException: Unable to create application org.electroncash.electroncash3.App: java.lang.RuntimeException: java.io.FileNotFoundException: chaquopy/bootstrap-native/x86/java/__init__.py
```

Reporter
------------

This issue was reported by 3 user(s):

| Electron Cash Version  | Python Version | Operating System  | Wallet Type  | Locale |
|---|---|---|---|---|
| 4.2.3-2  | java.lang.IllegalStateException: Python startup previously failed, and cannot be retried | Android 9 on Google HP Chromebook 11 G5 (setzer_cheets) | unknown | en_US | 
| 4.2.3-2  | java.lang.IllegalStateException: Python startup previously failed, and cannot be retried | Android 9 on Google HP Chromebook 11 G5 (setzer_cheets) | unknown | en_US | 
| 4.2.3-2  | java.lang.IllegalStateException: Python startup previously failed, and cannot be retried | Android 9 on Google HP Chromebook 11 G5 (setzer_cheets) | unknown | en_US | 

Additional Information
------------------------

The reporting user(s) did not provide additional information.

**Comment by mhsmith** [comment] 2021-01-28 12:08
Duplicate of #2136.

**Closed by mhsmith** 2021-01-28 12:08 UTC
