### ISSUE TITLE
MemoryError: 

### ISSUE THREAD

**Issue by ProfessorVenkman** [Electron-Cash/Electron-Cash#1759] opened 2020-01-06 08:22 UTC
Crash Report
============

This crash report was reported through the automatic crash reporting system 🤖

Traceback
--------------

```Python traceback
  File "site-packages\electron_cash_slp-3.6.1-py3.6.egg\electroncash_gui\qt\main_window.py", line 1461, in save_payment_request
  File "site-packages\electron_cash_slp-3.6.1-py3.6.egg\electroncash\wallet.py", line 2718, in add_payment_request
  File "site-packages\electron_cash_slp-3.6.1-py3.6.egg\electroncash\wallet.py", line 2700, in save_payment_requests
  File "site-packages\electron_cash_slp-3.6.1-py3.6.egg\electroncash\util.py", line 344, in <lambda>
  File "site-packages\electron_cash_slp-3.6.1-py3.6.egg\electroncash\util.py", line 340, in do_profile
  File "site-packages\electron_cash_slp-3.6.1-py3.6.egg\electroncash\storage.py", line 183, in write
  File "site-packages\electron_cash_slp-3.6.1-py3.6.egg\electroncash\storage.py", line 191, in _write
  File "json\__init__.py", line 238, in dumps
  File "json\encoder.py", line 202, in encode

MemoryError: 
```

Reporter
------------

This issue was reported by 23 user(s):

| Electron Cash Version  | Python Version | Operating System  | Wallet Type  | Locale |
|---|---|---|---|---|
| 3.6.1  | 3.6.8 (tags/v3.6.8:3c6b436a57, Dec 23 2018, 23:31:17) [MSC v.1916 32 bit (Intel)] | Windows-10-10.0.18362-SP0 | imported_addr | de_DE | 
| 4.0.12  | 3.6.8 (tags/v3.6.8:3c6b436a57, Dec 23 2018, 23:31:17) [MSC v.1916 32 bit (Intel)] | Windows-10-10.0.18362-SP0 | imported_addr | de_DE | 
| 4.0.12  | 3.6.8 (tags/v3.6.8:3c6b436a57, Dec 23 2018, 23:31:17) [MSC v.1916 32 bit (Intel)] | Windows-10-10.0.18362-SP0 | imported_addr | de_DE | 
| 4.0.12  | 3.6.8 (tags/v3.6.8:3c6b436a57, Dec 23 2018, 23:31:17) [MSC v.1916 32 bit (Intel)] | Windows-10-10.0.18362-SP0 | imported_addr | de_DE | 
| 4.0.12  | 3.6.8 (tags/v3.6.8:3c6b436a57, Dec 23 2018, 23:31:17) [MSC v.1916 32 bit (Intel)] | Windows-10-10.0.18362-SP0 | imported_addr | de_DE | 
| 4.0.12  | 3.6.8 (tags/v3.6.8:3c6b436a57, Dec 23 2018, 23:31:17) [MSC v.1916 32 bit (Intel)] | Windows-10-10.0.18362-SP0 | imported_addr | de_DE | 
| 3.6.5  | 3.6.8 (tags/v3.6.8:3c6b436a57, Dec 23 2018, 23:31:17) [MSC v.1916 32 bit (Intel)] | Windows-10-10.0.19041-SP0 | slp_standard | en_NL | 
| 3.6.6  | 3.6.8 (tags/v3.6.8:3c6b436a57, Dec 23 2018, 23:31:17) [MSC v.1916 32 bit (Intel)] | Windows-10-10.0.19041-SP0 | slp_imported_privkey | en_US | 
| 3.6.6  | 3.6.8 (tags/v3.6.8:3c6b436a57, Dec 23 2018, 23:31:17) [MSC v.1916 32 bit (Intel)] | Windows-10-10.0.19041-SP0 | slp_imported_privkey | en_US | 
| 3.6.6  | 3.6.8 (tags/v3.6.8:3c6b436a57, Dec 23 2018, 23:31:17) [MSC v.1916 32 bit (Intel)] | Windows-10-10.0.19041-SP0 | slp_imported_privkey | en_US | 
| 3.6.6  | 3.6.8 (tags/v3.6.8:3c6b436a57, Dec 23 2018, 23:31:17) [MSC v.1916 32 bit (Intel)] | Windows-10-10.0.19041-SP0 | slp_imported_privkey | en_US | 
| 3.6.6  | 3.6.8 (tags/v3.6.8:3c6b436a57, Dec 23 2018, 23:31:17) [MSC v.1916 32 bit (Intel)] | Windows-10-10.0.19041-SP0 | slp_standard | en_NL | 
| 3.6.6  | 3.6.8 (tags/v3.6.8:3c6b436a57, Dec 23 2018, 23:31:17) [MSC v.1916 32 bit (Intel)] | Windows-10-10.0.19041-SP0 | slp_standard | en_NL | 
| 3.6.6  | 3.6.8 (tags/v3.6.8:3c6b436a57, Dec 23 2018, 23:31:17) [MSC v.1916 32 bit (Intel)] | Windows-10-10.0.19041-SP0 | slp_standard | en_NL | 
| 4.2.4  | 3.8.7 (tags/v3.8.7:6503f05, Dec 21 2020, 17:43:54) [MSC v.1928 32 bit (Intel)] | Windows-10-10.0.19041-SP0 | imported_privkey | ru_RU | 
| 3.6.6  | 3.6.8 (tags/v3.6.8:3c6b436a57, Dec 23 2018, 23:31:17) [MSC v.1916 32 bit (Intel)] | Windows-10-10.0.19041-SP0 | slp_imported_privkey | nl_NL | 
| 3.6.6  | 3.6.8 (tags/v3.6.8:3c6b436a57, Dec 23 2018, 23:31:17) [MSC v.1916 32 bit (Intel)] | Windows-10-10.0.19041-SP0 | slp_imported_privkey | nl_NL | 
| 4.2.5  | 3.8.9 (tags/v3.8.9:a743f81, Apr  6 2021, 13:22:56) [MSC v.1928 32 bit (Intel)] | Windows-10-10.0.19041-SP0 | imported_addr,standard | en_US | 
| 4.2.5  | 3.8.9 (tags/v3.8.9:a743f81, Apr  6 2021, 13:22:56) [MSC v.1928 32 bit (Intel)] | Windows-10-10.0.19041-SP0 | standard,imported_addr | en_US | 
| 4.2.5  | 3.8.9 (tags/v3.8.9:a743f81, Apr  6 2021, 13:22:56) [MSC v.1928 32 bit (Intel)] | Windows-10-10.0.19041-SP0 | standard,imported_addr | en_US | 
| 3.6.6  | 3.6.8 (tags/v3.6.8:3c6b436a57, Dec 23 2018, 23:31:17) [MSC v.1916 32 bit (Intel)] | Windows-10-10.0.19041-SP0 | slp_standard | en_NL | 
| 3.6.6  | 3.6.8 (tags/v3.6.8:3c6b436a57, Dec 23 2018, 23:31:17) [MSC v.1916 32 bit (Intel)] | Windows-10-10.0.19041-SP0 | slp_standard | en_NL | 
| 3.6.6  | 3.6.8 (tags/v3.6.8:3c6b436a57, Dec 23 2018, 23:31:17) [MSC v.1916 32 bit (Intel)] | Windows-10-10.0.19041-SP0 | slp_standard | en_NL | 

Additional Information
------------------------

> baby636@outlook.de

---

> BABY636@outlook.de

---

> baby636@outlook.de

---

> ICH KANN NICHT MEIN GELD VERSCHICKEN ßß BABYW@OULOOK.DE

---

> baby636@outlook.de

---

> baby636@outlook.de

---

> Wallet was painfully slow when validating slp transactions.

---

> I tried to create my first NFT but after creating it I couldn't find it between my tokens so I created a new one. After saving I got this bugreport. So I gues something ain't alright here?

---

> don't know wtf it keeps popping up bugreports but this shit is buggy as hell

---

**Comment by cculianu** [comment] 2020-02-02 09:34
Possible dupe of #1740

**Closed** 2024-09-15 19:02 UTC
Labels: observation required, SLP

**Comment by ProfessorVenkman** [comment] 2024-12-19 16:17
Good afternoon @fyookball,

I just received another crash report related to this issue. The crash occured on Electron Cash 4.4.2.
I'm not sure which versions of Electron Cash include the fix but this is the first report from anything
newer than 4.2.5 since you closed the issue.

Could you please check if this issue really is resolved? Here is the traceback that I just collected:

```Python traceback
  File "electroncash_gui\qt\main_window.py", line 5107, in closeEvent
  File "electroncash_gui\qt\main_window.py", line 5227, in clean_up
  File "electroncash\daemon.py", line 299, in stop_wallet
  File "electroncash\wallet.py", line 3055, in stop_threads
  File "electroncash\wallet.py", line 3067, in save_network_state
  File "electroncash\util.py", line 362, in <lambda>
  File "electroncash\util.py", line 357, in do_profile
  File "electroncash\storage.py", line 187, in write
  File "electroncash\storage.py", line 195, in _write
  File "json\__init__.py", line 238, in dumps
  File "json\encoder.py", line 202, in encode

MemoryError: 
```


~ _With robotic wishes_
