### ISSUE TITLE
java.lang.RuntimeException: <Daemon(Thread-2, stopped 2377787760)> unexpectedly stopped

### ISSUE THREAD

**Issue by ProfessorVenkman** [Electron-Cash/Electron-Cash#2292] opened 2021-06-10 11:38 UTC
Crash Report
============

This crash report was reported through the automatic crash reporting system 🤖

Traceback
--------------

```Python traceback
	at org.electroncash.electroncash3.DaemonModel$2.run(Daemon.kt:49)
	at android.os.Handler.handleCallback(Handler.java:873)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loop(Looper.java:215)
	at android.app.ActivityThread.main(ActivityThread.java:6939)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:870)
java.lang.RuntimeException: <Daemon(Thread-2, stopped 2377787760)> unexpectedly stopped
```

Reporter
------------

This issue was reported by 14 user(s):

| Electron Cash Version  | Python Version | Operating System  | Wallet Type  | Locale |
|---|---|---|---|---|
| 4.2.3-3  | 3.8.6 (default, Jan 17 2021, 16:49:54)  [Clang 7.0.2 (https://android.googlesource.com/toolchain/clang 003100370607242d | Android 9 on motorola moto e6 (XT2005DL) (surfna) | unknown | en_US | 
| 4.2.3-3  | 3.8.6 (default, Jan 17 2021, 16:49:54)  [Clang 7.0.2 (https://android.googlesource.com/toolchain/clang 003100370607242d | Android 10 on LGE LM-K500 (mdh30xlm) | unknown | en_US | 
| 4.2.3-3  | 3.8.6 (default, Jan 17 2021, 16:49:54)  [Clang 7.0.2 (https://android.googlesource.com/toolchain/clang 003100370607242d | Android 10 on LGE LM-K500 (mdh30xlm) | unknown | en_US | 
| 4.2.3-3  | 3.8.6 (default, Jan 17 2021, 16:49:54)  [Clang 7.0.2 (https://android.googlesource.com/toolchain/clang 003100370607242d | Android 10 on LGE LM-K500 (mdh30xlm) | unknown | en_US | 
| 4.2.3-3  | 3.8.6 (default, Jan 17 2021, 16:49:54)  [Clang 7.0.2 (https://android.googlesource.com/toolchain/clang 003100370607242d | Android 10 on LGE LM-K500 (mdh30xlm) | unknown | en_US | 
| 4.2.3-3  | 3.8.6 (default, Jan 17 2021, 16:49:54)  [Clang 7.0.2 (https://android.googlesource.com/toolchain/clang 003100370607242d | Android 10 on LGE LM-K500 (mdh30xlm) | unknown | en_US | 
| 4.2.3-3  | 3.8.6 (default, Jan 17 2021, 16:49:54)  [Clang 7.0.2 (https://android.googlesource.com/toolchain/clang 003100370607242d | Android 10 on LGE LM-K500 (mdh30xlm) | unknown | en_US | 
| 4.2.3-3  | 3.8.6 (default, Jan 17 2021, 16:49:54)  [Clang 7.0.2 (https://android.googlesource.com/toolchain/clang 003100370607242d | Android 10 on LGE LM-K500 (mdh30xlm) | unknown | en_US | 
| 4.2.3-3  | 3.8.6 (default, Jan 17 2021, 16:49:54)  [Clang 7.0.2 (https://android.googlesource.com/toolchain/clang 003100370607242d | Android 10 on LGE LM-K500 (mdh30xlm) | unknown | en_US | 
| 4.2.3-3  | 3.8.6 (default, Jan 17 2021, 16:49:54)  [Clang 7.0.2 (https://android.googlesource.com/toolchain/clang 003100370607242d | Android 10 on LGE LM-K500 (mdh30xlm) | unknown | en_US | 
| 4.2.3-3  | 3.8.6 (default, Jan 17 2021, 16:49:54)  [Clang 7.0.2 (https://android.googlesource.com/toolchain/clang 003100370607242d | Android 10 on LGE LM-K500 (mdh30xlm) | unknown | en_US | 
| 4.2.3-3  | 3.8.6 (default, Jan 17 2021, 16:49:54)  [Clang 7.0.2 (https://android.googlesource.com/toolchain/clang 003100370607242d | Android 10 on LGE LM-K500 (mdh30xlm) | unknown | en_US | 
| 4.2.3-3  | 3.8.6 (default, Jan 17 2021, 16:49:54)  [Clang 7.0.2 (https://android.googlesource.com/toolchain/clang 003100370607242d | Android 10 on LGE LM-K500 (mdh30xlm) | unknown | en_US | 
| 4.2.3-3  | 3.8.6 (default, Jan 17 2021, 16:49:54)  [Clang 7.0.2 (https://android.googlesource.com/toolchain/clang 003100370607242d | Android 10 on LGE LM-K500 (mdh30xlm) | unknown | en_US | 

Additional Information
------------------------

> Wallet:98ce188d14ba46bbc9f78dd6de46a3db9971

---

> data/data/org.electroncash.wallet/files/data/wallets/98ce188d14ba46bbc9f78dd6de46a3db9971

---

**Comment by mhsmith** [comment] 2021-07-06 16:46
Duplicate of #1741.

**Closed by mhsmith** 2021-07-06 16:46 UTC
