### ISSUE TITLE
OSError: [Errno 28] No space left on device

### ISSUE THREAD

**Issue by ProfessorVenkman** [Electron-Cash/Electron-Cash#794] opened 2018-07-14 14:36 UTC
Crash Report
============

This crash report was reported through the automatic crash reporting system 🤖

Traceback
--------------

```Python traceback
  File "/private/var/containers/Bundle/Application/4FCAE8E3-6C2A-49B6-B7C3-76F40AD07F22/Electron-Cash.app/Library/Application Support/com.c3-soft.ElectronCash/app/ElectronCash/electroncash_gui/ios_native/utils.py", line 261, in run_with_except_hook
    run_original(*args2, **kwargs2)
  File "/private/var/containers/Bundle/Application/4FCAE8E3-6C2A-49B6-B7C3-76F40AD07F22/Electron-Cash.app/Library/Application Support/com.c3-soft.ElectronCash/app/ElectronCash/electroncash/interface.py", line 240, in run
    socket = self.get_socket()
  File "/private/var/containers/Bundle/Application/4FCAE8E3-6C2A-49B6-B7C3-76F40AD07F22/Electron-Cash.app/Library/Application Support/com.c3-soft.ElectronCash/app/ElectronCash/electroncash/interface.py", line 182, in get_socket
    os.fsync(f.fileno())

OSError: [Errno 28] No space left on device
```

Reporter
------------

This issue was reported by 1 user(s):

| Electrum Version  | Operating System  | Wallet Type  | Locale |
|---|---|---|---|
| 3.3 (iOS Build: 301)  | Darwin-17.6.0-iPhone8,2-64bit iOS 11.4 iPhone (967AA971-465B-4399-A4F9-A7777C9E3AFA) | unknown | en_UK |

Additional Information
------------------------

The reporting user(s) did not provide additional information.

**Comment by cculianu** [comment] 2018-07-14 15:51
This is iOS.  

Hmm.  I may want to warn user of device is full that app won't work ok.

**Comment by rt121212121** [comment] 2018-07-14 20:57
I'm sort of wondering if we should have a wallet mode where it disconnects from the network and stops all processing if it is "inaccessible" as these random errors in various file-system places just pop up all over the place.  We have similar ones where users remove their usb device without closing the wallet first.

**Comment by cculianu** [comment] 2018-07-15 11:16
That's not a bad idea -- but be sure to close down the daemon too because that writes to the filesystem as well ..

I actually have this mode in iOS but -- I attempt to start the daemon when the user foregrounds the app and .. well.. this is what happens if no space left on device.

I'm going to put a check for this in there.

iOS already warns users when they are out of space... but running out of space on the device is surprisingly common, especially if you just recorded a long video.

**Comment by cculianu** [comment] 2019-01-18 02:31
Dupe of #1072 . Fixed.

**Closed by cculianu** 2019-01-18 02:31 UTC
Labels: duplicate, enhancement, ios
