### ISSUE TITLE
bug: pay to field can have the cursor and content disappear

### ISSUE THREAD

**Issue by emergent-reasons** [Electron-Cash/Electron-Cash#1521] opened 2019-07-15 16:34 UTC
Using `Electron-Cash-4.0.8-dev1-x86_64.AppImage`

Expected: stuff in pay-to field does not disappear and cursor stays visible
Actual: content and cursor both disappear

[capture](https://i.imgur.com/2Sxham3.mp4)

Steps:

1. paste a valid cashaccount (e.g. Calin#27806)
1. tab to leave the pay-to field.
1. The cashaccount is validated and the rest of the information is filled in
1. Highlight something in the pay-to field and while still clicking, drag the mouse off the bottom of the pay-to field
4. Everything in pay-to disappears. Can't see a cursor.

At this point, you can actually move the cursor and type. You just can't see anything in the field.

**Comment by cculianu** [comment] 2019-07-15 16:36
Yeah I've seen this too on macOS.  Thanks for the detailed info. It's identical to how you can reproduce it on macOS -- which means there's hope to fix it because it's likely a mis-use of Qt in the PayToEdit class ... Will fix.

**Comment by EchterAgo** [comment] 2019-07-15 16:39
Maybe try to revert my recent change to this.

**Comment by cculianu** [comment] 2019-07-15 16:39
@EchterAgo No.. it's been there forever.... before your most recent change definitely.  I don't think it's related...

**Comment by cculianu** [comment] 2019-07-15 16:40
It may be related to the changes you did a couple of months ago when you overhauled it to use the generic `OverlayControlMixin`... however.

**Comment by cculianu** [comment] 2019-07-16 12:46
Hey @emergent-reasons .. this has been fixed in latest master.  If you can try and reproduce it again and let me know if it's gone for you too.

It definitely was easily reproduced here and my fix addresses it.

Let me know!

**Closed** 2019-07-16 12:45 UTC
Labels: Qt, UX and usability, bug

**Comment by emergent-reasons** [comment] 2019-07-16 13:45
Fixed it for me! Nice one.
