### ISSUE TITLE
Password with single quote opens wallet but is "incorrect" for any action

### ISSUE THREAD

**Issue by DaneWeber** [Electron-Cash/Electron-Cash#1480] opened 2019-06-23 13:39 UTC
_I've managed to recover my BCH, so this is only a bug report and help for anyone else who might have the same problem._

**I believe that the password checker/evaluator chokes on single quotes (`'`), even though the wallet can be successfully opened with the same password.**

I've seen https://github.com/Electron-Cash/Electron-Cash/issues/431 and related issues.

Using Electron Cash 3.1.2 portable for Windows I created a wallet by importing private keys (has the "[imported_privkey]" label in the window title and the "Seed" menu item disabled), but then encrypted the wallet with a random password. After doing so, that password could be used to open the wallet, but errored with "incorrect password" whenever trying to send BCH or change the password.

I investigated but gave up for awhile. I decided to try again yesterday with Electron Cash 4.0.7 portable for Windows. I had the same behavior. After trying things with changing the password, I managed to reset the password and send BCH. As best I can tell, these are the steps that I used to fix it:

Let's say my password was `xxx'xxx"xxx`,

```
p = 'xxx\'xxx"xxx'
wallet.update_password(p,'')
```

I had to close and re-open the wallet afterward.

**Comment by cculianu** [comment] 2019-06-23 19:32
Hi,

I wasn't around for issue #431 but it appears to have since been fixed.  I was unable to reproduce it.

I am leaving this issue here as a "workaround" and closing it, since it's not currently an active bug.  Can you reproduce it with a modern (4.0+) Electron Cash?

I'm closing it until then.. thanks for reporting and writing this here.  Hopefully this issue helps others in a search.   Cheers.

**Closed by cculianu** 2019-06-23 19:32 UTC
