### ISSUE TITLE
TypeError: unsupported operand type(s) for /: 'str' and 'int'

### ISSUE THREAD

**Issue by ProfessorVenkman** [Electron-Cash/Electron-Cash#1691] opened 2019-11-19 10:41 UTC
Crash Report
============

This crash report was reported through the automatic crash reporting system 🤖

Traceback
--------------

```Python traceback
  File "Electron_Cash_SLP-3.5.1-py3.6.egg/electroncash_gui/qt/main_window.py", line 1568, in update_receive_qr
  File "Electron_Cash_SLP-3.5.1-py3.6.egg/electroncash_gui/qt/qrwindow.py", line 91, in set_content
  File "Electron_Cash_SLP-3.5.1-py3.6.egg/electroncash_gui/qt/main_window.py", line 849, in format_amount
  File "Electron_Cash_SLP-3.5.1-py3.6.egg/electroncash/util.py", line 508, in format_satoshis

TypeError: unsupported operand type(s) for /: 'str' and 'int'
```

Reporter
------------

This issue was reported by 4 user(s):

| Electron Cash Version  | Python Version | Operating System  | Wallet Type  | Locale |
|---|---|---|---|---|
| 3.5.1  | 3.6.9 (default, Sep 11 2019, 22:58:33)  [GCC 4.2.1 Compatible Apple LLVM 8.0.0 (clang-800.0.42.1)] | Darwin-19.0.0-x86_64-i386-64bit | slp_standard |  | 
| 3.5.1  | 3.6.9 (default, Sep 11 2019, 22:58:33)  [GCC 4.2.1 Compatible Apple LLVM 8.0.0 (clang-800.0.42.1)] | Darwin-19.0.0-x86_64-i386-64bit | slp_standard |  | 
| 3.5.1  | 3.6.9 (default, Sep 11 2019, 22:58:33)  [GCC 4.2.1 Compatible Apple LLVM 8.0.0 (clang-800.0.42.1)] | Darwin-19.0.0-x86_64-i386-64bit | slp_standard |  | 
| 3.5.1  | 3.6.9 (default, Sep 11 2019, 22:58:33)  [GCC 4.2.1 Compatible Apple LLVM 8.0.0 (clang-800.0.42.1)] | Darwin-19.0.0-x86_64-i386-64bit | slp_standard |  | 

Additional Information
------------------------

> Scan Beyond Gap

---

**Comment by cculianu** [comment] 2019-11-24 13:38
Probably something with SLP not ensuring the amount is numeric.

**Comment by jcramer** [comment] 2020-10-10 18:29
Closing this because I could not reproduce and this issue hasn't happened since version 3.5.1, so its most likely not an issue anymore.

**Closed by jcramer** 2020-10-10 18:29 UTC
Labels: SLP, bug

**Comment by ProfessorVenkman** [comment] 2022-01-20 21:30
Good evening @jcramer,

I just received another crash report related to this issue. The crash occured on Electron Cash 3.6.6.
I'm not sure which versions of Electron Cash include the fix but this is the first report from anything
newer than 3.5.1 since you closed the issue.

Could you please check if this issue really is resolved? Here is the traceback that I just collected:

```Python traceback
  File "site-packages\electron_cash_slp-3.6.6-py3.6.egg\electroncash_gui\qt\main_window.py", line 1718, in update_receive_qr
  File "site-packages\electron_cash_slp-3.6.6-py3.6.egg\electroncash_gui\qt\qrwindow.py", line 91, in set_content
  File "site-packages\electron_cash_slp-3.6.6-py3.6.egg\electroncash_gui\qt\main_window.py", line 1008, in format_amount
  File "site-packages\electron_cash_slp-3.6.6-py3.6.egg\electroncash\util.py", line 510, in format_satoshis

TypeError: unsupported operand type(s) for /: 'str' and 'int'
```


~ _With robotic wishes_
